### ISSUE TITLE
error installing realm 0.15.4 on mac 

### ISSUE THREAD

**Issue by amanthegreatone** [realm/realm-js#1040]
Hi,

I am having issues installing realm on my mac. Can someone help me troubleshoot the issue.

```
[SyookPro (nav)]$ npm i
npm WARN prefer global marked@0.3.6 should be installed with -g

> realm@0.15.4 install /Users/Arjun/SyookPro/node_modules/realm
> node scripts/install.js

node-pre-gyp
 ERR! install error
node-pre-gyp ERR! stack TypeError: Cannot read property 'version' of null
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/Users/Arjun/SyookPro/node_modules/node-pre-gyp/lib/util/versioning.js:270:32)
node-pre-gyp ERR! stack     at install (/Users/Arjun/SyookPro/node_modules/node-pre-gyp/lib/install.js:168:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/Users/Arjun/SyookPro/node_modules/node-pre-gyp/lib/node-pre-gyp.js:50:37)
node-pre-gyp ERR! stack     at run (/Users/Arjun/SyookPro/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/Users/Arjun/SyookPro/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:569:30)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:580:10)
node-pre-gyp ERR! stack     at Module.load (module.js:503:32)
node-pre-gyp ERR! stack     at tryModuleLoad (module.js:466:12)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:458:3)
node-pre-gyp ERR! System Darwin 16.6.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/Arjun/SyookPro/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/Arjun/SyookPro/node_modules/realm
node-pre-gyp ERR! node -v v8.0.0
node-pre-gyp ERR! node-pre-gyp -v vhttps://registry.npmjs.org/node-pre-gyp/-/node-pre-gyp-0.6.34.tgz
node-pre-gyp ERR! not ok

Cannot read property 'version' of null

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! realm@0.15.4 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the realm@0.15.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Arjun/.npm/_logs/2017-06-01T08_48_46_105Z-debug.log
```

**Comment by amanthegreatone** [comment]
downgraded to node v6.10.3 and npm 3.10.10 and it works!
