### ISSUE TITLE
Realm not building

### ISSUE THREAD

**Issue by ShMcK** [realm/realm-js#1092]
Having the following error when building realm for release. This issue is not happening in debug mode.

Node: 8.1.0
Realm versions: 1.3.1 & 1.8.1

Any help would be much appreciated.

See logs:

```
error /tmp/sandbox/workspace/node_modules/realm: Command failed.
45
    Exit code: 1
46
    Command: sh
47
    Arguments: -c node-pre-gyp install --fallback-to-build
48
    Directory: /tmp/sandbox/workspace/node_modules/realm
49
    Output:
50
    node-pre-gyp info it worked if it ends with ok
51
    node-pre-gyp info using node-pre-gyp@0.6.36
52
    node-pre-gyp info using node@8.1.0 | linux | x64
53
    node-pre-gyp info check checked for "/tmp/sandbox/workspace/node_modules/realm/compiled/node-v57_linux_x64/realm.node" (not found)
54
    node-pre-gyp http GET https://static.realm.io/node-pre-gyp/realm-v1.3.1-node-v57-linux-x64.tar.gz
55
    node-pre-gyp http 404 https://static.realm.io/node-pre-gyp/realm-v1.3.1-node-v57-linux-x64.tar.gz
56
    node-pre-gyp ERR! Tried to download(404): https://static.realm.io/node-pre-gyp/realm-v1.3.1-node-v57-linux-x64.tar.gz 
57
    node-pre-gyp ERR! Pre-built binaries not found for realm@1.3.1 and node@8.1.0 (node-v57 ABI) (falling back to source compile with node-gyp) 
58
    node-pre-gyp http 404 status code downloading tarball https://static.realm.io/node-pre-gyp/realm-v1.3.1-node-v57-linux-x64.tar.gz 
59
    gyp info it worked if it ends with ok
60
    gyp info using node-gyp@3.6.2
61
    gyp info using node@8.1.0 | linux | x64
62
    gyp info ok 
63
    gyp info it worked if it ends with ok
64
    gyp info using node-gyp@3.6.2
65
    gyp info using node@8.1.0 | linux | x64
66
    gyp http GET https://nodejs.org/download/release/v8.1.0/node-v8.1.0-headers.tar.gz
67
    gyp http 200 https://nodejs.org/download/release/v8.1.0/node-v8.1.0-headers.tar.gz
68
    gyp http GET https://nodejs.org/download/release/v8.1.0/SHASUMS256.txt
69
    gyp http 200 https://nodejs.org/download/release/v8.1.0/SHASUMS256.txt
70
    gyp info spawn /usr/local/bin/python2
71
    gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
72
    gyp info spawn args   'binding.gyp',
73
    gyp info spawn args   '-f',
74
    gyp info spawn args   'make',
75
    gyp info spawn args   '-I',
76
    gyp info spawn args   '/tmp/sandbox/workspace/node_modules/realm/build/config.gypi',
77
    gyp info spawn args   '-I',
78
    gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
79
    gyp info spawn args   '-I',
80
    gyp info spawn args   '/Users/buddybuild/.node-gyp/8.1.0/include/node/common.gypi',
81
    gyp info spawn args   '-Dlibrary=shared_library',
82
    gyp info spawn args   '-Dvisibility=default',
83
    gyp info spawn args   '-Dnode_root_dir=/Users/buddybuild/.node-gyp/8.1.0',
84
    gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
85
    gyp info spawn args   '-Dnode_lib_file=/Users/buddybuild/.node-gyp/8.1.0/<(target_arch)/node.lib',
86
    gyp info spawn args   '-Dmodule_root_dir=/tmp/sandbox/workspace/node_modules/realm',
87
    gyp info spawn args   '-Dnode_engine=v8',
88
    gyp info spawn args   '--depth=.',
89
    gyp info spawn args   '--no-parallel',
90
    gyp info spawn args   '--generator-output',
91
    gyp info spawn args   'build',
92
    gyp info spawn args   '-Goutput_dir=.' ]
93
    gyp info ok 
94
    gyp info it worked if it ends with ok
95
    gyp info using node-gyp@3.6.2
96
    gyp info using node@8.1.0 | linux | x64
97
    gyp info spawn make
98
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
99
    make: Entering directory '/tmp/sandbox/workspace/node_modules/realm/build'
100
      ACTION binding_gyp_vendored_realm_target_download_realm /tmp/sandbox/workspace/node_modules/realm/vendor/realm-node
101
    Downloading dependency: realm-node 2.6.0
102
    https://static.realm.io/downloads/core/realm-core-node-linux-2.6.0.tar.gz
103
    Skipping the sync download because ENABLE_SYNC is false.
104
      TOUCH Release/obj.target/vendored-realm.stamp
105
      TOUCH Release/obj.target/realm-core.stamp
106
      CXX(target) Release/obj.target/object-store/src/object-store/src/binding_callback_thread_observer.o
107
      CXX(target) Release/obj.target/object-store/src/object-store/src/collection_notifications.o
108
      CXX(target) Release/obj.target/object-store/src/object-store/src/index_set.o
109
      CXX(target) Release/obj.target/object-store/src/object-store/src/list.o
110
      CXX(target) Release/obj.target/object-store/src/object-store/src/object.o
111
      CXX(target) Release/obj.target/object-store/src/object-store/src/object_schema.o
112
      CXX(target) Release/obj.target/object-store/src/object-store/src/object_store.o
113
      CXX(target) Release/obj.target/object-store/src/object-store/src/results.o
114
      CXX(target) Release/obj.target/object-store/src/object-store/src/schema.o
115
      CXX(target) Release/obj.target/object-store/src/object-store/src/shared_realm.o
116
      CXX(target) Release/obj.target/object-store/src/object-store/src/thread_safe_reference.o
117
      CXX(target) Release/obj.target/object-store/src/object-store/src/impl/collection_change_builder.o
118
      CXX(target) Release/obj.target/object-store/src/object-store/src/impl/collection_notifier.o
119
      CXX(target) Release/obj.target/object-store/src/object-store/src/impl/list_notifier.o
120
      CXX(target) Release/obj.target/object-store/src/object-store/src/impl/object_notifier.o
121
      CXX(target) Release/obj.target/object-store/src/object-store/src/impl/realm_coordinator.o
122
      CXX(target) Release/obj.target/object-store/src/object-store/src/impl/results_notifier.o
123
      CXX(target) Release/obj.target/object-store/src/object-store/src/impl/transact_log_handler.o
124
      CXX(target) Release/obj.target/object-store/src/object-store/src/impl/weak_realm_notifier.o
125
    In file included from ../src/object-store/src/impl/weak_realm_notifier.cpp:22:0:
126
    ../src/object-store/src/util/event_loop_signal.hpp:38:7: warning: "REALM_USE_CF" is not defined [-Wundef]
127
     #elif REALM_USE_CF
128
           ^
129
    ../src/object-store/src/util/event_loop_signal.hpp:40:7: warning: "REALM_USE_ALOOPER" is not defined [-Wundef]
130
     #elif REALM_USE_ALOOPER
131
           ^
132
      CXX(target) Release/obj.target/object-store/src/object-store/src/parser/parser.o
133
      CXX(target) Release/obj.target/object-store/src/object-store/src/parser/query_builder.o
134
      CXX(target) Release/obj.target/object-store/src/object-store/src/util/format.o
135
      CXX(target) Release/obj.target/object-store/src/object-store/src/impl/epoll/external_commit_helper.o
136
      AR(target) Release/obj.target/object-store.a
137
      COPY Release/object-store.a
138
      CXX(target) Release/obj.target/realm/src/node/platform.o
139
      CXX(target) Release/obj.target/realm/src/js_realm.o
140
      CXX(target) Release/obj.target/realm/src/node/node_init.o
141
    In file included from /Users/buddybuild/.node-gyp/8.1.0/include/node/v8.h:26:0,
142
                     from /Users/buddybuild/.node-gyp/8.1.0/include/node/node.h:63,
143
                     from ../../nan/nan.h:49,
144
                     from ../src/node/node_types.hpp:28,
145
                     from ../src/node/node_string.hpp:21,
146
                     from ../src/node/node_init.hpp:21,
147
                     from ../src/node/node_init.cpp:19:
148
    /Users/buddybuild/.node-gyp/8.1.0/include/node/v8config.h:294:26: warning: "V8_HAS___FORCEINLINE" is not defined [-Wundef]
149
     #elif !defined(DEBUG) && V8_HAS___FORCEINLINE
150
                              ^
151
    /Users/buddybuild/.node-gyp/8.1.0/include/node/v8config.h:307:26: warning: "V8_HAS_DECLSPEC_NOINLINE" is not defined [-Wundef]
152
     #elif !defined(DEBUG) && V8_HAS_DECLSPEC_NOINLINE
153
                              ^
154
    /Users/buddybuild/.node-gyp/8.1.0/include/node/v8config.h:319:7: warning: "HAS_DECLSPEC_NORETURN" is not defined [-Wundef]
155
     #elif HAS_DECLSPEC_NORETURN
156
           ^
157
    /Users/buddybuild/.node-gyp/8.1.0/include/node/v8config.h:333:43: warning: "V8_HAS_DECLSPEC_DEPRECATED" is not defined [-Wundef]
158
     #elif defined(V8_DEPRECATION_WARNINGS) && V8_HAS_DECLSPEC_DEPRECATED
159
                                               ^
160
    /Users/buddybuild/.node-gyp/8.1.0/include/node/v8config.h:373:7: warning: "V8_HAS_DECLSPEC_ALIGN" is not defined [-Wundef]
161
     #elif V8_HAS_DECLSPEC_ALIGN
162
           ^
163
    /Users/buddybuild/.node-gyp/8.1.0/include/node/v8config.h:405:7: warning: "V8_HAS___ALIGNOF" is not defined [-Wundef]
164
     #elif V8_HAS___ALIGNOF
165
           ^
166
    /Users/buddybuild/.node-gyp/8.1.0/include/node/v8config.h:257:7: warning: "V8_CC_INTEL" is not defined [-Wundef]
167
         (!V8_CC_INTEL && V8_GNUC_PREREQ(4, 1, 0))
168
           ^
169
    /Users/buddybuild/.node-gyp/8.1.0/include/node/v8config.h:420:5: note: in expansion of macro ‘V8_HAS_ATTRIBUTE_WARN_UNUSED_RESULT’
170
     #if V8_HAS_ATTRIBUTE_WARN_UNUSED_RESULT
171
         ^
172
    In file included from ../../nan/nan.h:49:0,
173
                     from ../src/node/node_types.hpp:28,
174
                     from ../src/node/node_string.hpp:21,
175
                     from ../src/node/node_init.hpp:21,
176
                     from ../src/node/node_init.cpp:19:
177
    /Users/buddybuild/.node-gyp/8.1.0/include/node/node.h:199:5: warning: "HAVE_OPENSSL" is not defined [-Wundef]
178
     #if HAVE_OPENSSL
179
         ^
180
    In file included from ../src/node/node_init.cpp:20:0:
181
    ../src/js_realm.hpp: In instantiation of ‘static void realm::js::RealmClass<T>::wait_for_download_completion(realm::js::RealmClass<T>::ContextType, realm::js::RealmClass<T>::FunctionType, realm::js::RealmClass<T>::ObjectType, size_t, const ValueType*, realm::js::RealmClass<T>::ReturnValue&) [with T = realm::node::Types; realm::js::RealmClass<T>::ContextType = v8::Isolate*; realm::js::RealmClass<T>::FunctionType = v8::Local<v8::Function>; realm::js::RealmClass<T>::ObjectType = v8::Local<v8::Object>; size_t = long unsigned int; realm::js::RealmClass<T>::ValueType = v8::Local<v8::Value>; realm::js::RealmClass<T>::ReturnValue = realm::js::ReturnValue<realm::node::Types>]’:
182
    ../src/js_realm.hpp:152:7:   required from ‘realm::js::RealmClass<realm::node::Types> realm::node::ObjectWrap<realm::js::RealmClass<realm::node::Types> >::s_class’
183
    ../src/node/node_class.hpp:136:5:   required from ‘static v8::Local<v8::Function> realm::node::ObjectWrap<ClassType>::create_constructor(v8::Isolate*) [with ClassType = realm::js::RealmClass<realm::node::Types>]’
184
    ../src/js_realm.hpp:286:90:   required from ‘static typename T::Function realm::js::RealmClass<T>::create_constructor(realm::js::RealmClass<T>::ContextType) [with T = realm::node::Types; typename T::Function = v8::Local<v8::Function>; realm::js::RealmClass<T>::ContextType = v8::Isolate*]’
185
    ../src/node/node_init.cpp:27:72:   required from here
186
    ../src/js_realm.hpp:549:10: warning: variable ‘config_object’ set but not used [-Wunused-but-set-variable]
187
         auto config_object = Value::validated_to_object(ctx, arguments[0]);
188
              ^
189
    In file included from ../src/node/node_object_accessor.hpp:21:0,
190
                     from ../src/node/node_init.hpp:29,
191
                     from ../src/node/node_init.cpp:19:
192
    ../src/node/node_class.hpp: In instantiation of ‘static void realm::node::ObjectWrap<ClassType>::construct(const v8::FunctionCallbackInfo<v8::Value>&) [with ClassType = realm::js::RealmClass<realm::node::Types>]’:
193
    ../src/node/node_class.hpp:160:105:   required from ‘static v8::Local<v8::FunctionTemplate> realm::node::ObjectWrap<ClassType>::create_template() [with ClassType = realm::js::RealmClass<realm::node::Types>]’
194
    ../src/node/node_class.hpp:48:82:   required from ‘static v8::Local<v8::FunctionTemplate> realm::node::ObjectWrap<ClassType>::get_template() [with ClassType = realm::js::RealmClass<realm::node::Types>]’
195
    ../src/node/node_class.hpp:133:56:   required from ‘static v8::Local<v8::Function> realm::node::ObjectWrap<ClassType>::create_constructor(v8::Isolate*) [with ClassType = realm::js::RealmClass<realm::node::Types>]’
196
    ../src/js_realm.hpp:286:90:   required from ‘static typename T::Function realm::js::RealmClass<T>::create_constructor(realm::js::RealmClass<T>::ContextType) [with T = realm::node::Types; typename T::Function = v8::Local<v8::Function>; realm::js::RealmClass<T>::ContextType = v8::Isolate*]’
197
    ../src/node/node_init.cpp:27:72:   required from here
198
    ../src/node/node_class.hpp:230:5: warning: the address of ‘static void realm::js::RealmClass<T>::constructor(realm::js::RealmClass<T>::ContextType, realm::js::RealmClass<T>::ObjectType, size_t, const ValueType*) [with T = realm::node::Types; realm::js::RealmClass<T>::ContextType = v8::Isolate*; realm::js::RealmClass<T>::ObjectType = v8::Local<v8::Object>; size_t = long unsigned int; realm::js::RealmClass<T>::ValueType = v8::Local<v8::Value>]’ will always evaluate as ‘true’ [-Waddress]
199
         if (reinterpret_cast<void*>(s_class.constructor)) {
200
         ^
201
      SOLINK_MODULE(target) Release/obj.target/realm.node
202
    /usr/bin/ld: /tmp/sandbox/workspace/node_modules/realm/vendor/realm-node//librealm-node.a(file-node.o): unrecognized relocation (0x2a) in section `.text'
203
    /usr/bin/ld: final link failed: Bad value
204
    collect2: error: ld returned 1 exit status
205
    make: *** [Release/obj.target/realm.node] Error 1
206
    realm.target.mk:165: recipe for target 'Release/obj.target/realm.node' failed
207
    make: Leaving directory '/tmp/sandbox/workspace/node_modules/realm/build'
208
    gyp ERR! build error 
209
    gyp ERR! stack Error: `make` failed with exit code: 2
210
    gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
211
    gyp ERR! stack     at emitTwo (events.js:125:13)
212
    gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
213
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
214
    gyp ERR! System Linux 4.9.20-11.31.amzn1.x86_64
215
    gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/tmp/sandbox/workspace/node_modules/realm/compiled/node-v57_linux_x64/realm.node" "--module_name=realm" "--module_path=/tmp/sandbox/workspace/node_modules/realm/compiled/node-v57_linux_x64"
216
    gyp ERR! cwd /tmp/sandbox/workspace/node_modules/realm
217
    gyp ERR! node -v v8.1.0
218
    gyp ERR! node-gyp -v v3.6.2
219
    gyp ERR! not ok 
220
    node-pre-gyp ERR! build error 
221
    node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/tmp/sandbox/workspace/node_modules/realm/compiled/node-v57_linux_x64/realm.node --module_name=realm --module_path=/tmp/sandbox/workspace/node_modules/realm/compiled/node-v57_linux_x64' (1)
222
    node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/tmp/sandbox/workspace/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
223
    node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
224
    node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
225
    node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:887:16)
226
    node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
227
    node-pre-gyp ERR! System Linux 4.9.20-11.31.amzn1.x86_64
228
    node-pre-gyp ERR! command "/usr/local/bin/node" "/tmp/sandbox/workspace/node_modules/realm/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
229
    node-pre-gyp ERR! cwd /tmp/sandbox/workspace/node_modules/realm
230
    node-pre-gyp ERR! node -v v8.1.0
231
    node-pre-gyp ERR! node-pre-gyp -v v0.6.36
232
    node-pre-gyp ERR! not ok 
233
    Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/tmp/sandbox/workspace/node_modules/realm/compiled/node-v57_linux_x64/realm.node --module_name=realm --module_path=/tmp/sandbox/workspace/node_modules/realm/compiled/node-v57_linux_x64' (1)
234
    info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by ShMcK** [comment]
The [realm download link](https://static.realm.io/node-pre-gyp/realm-v1.3.1-node-v57-linux-x64.tar.gz) appears to be a 404.

**Comment by fealebenpae** [comment]
realm-js 1.3.1 doesn't have a pre-built binary compatible with Node.js 8.x. 1.8 and up do, however. It should be possible to build from source, but the linker error message is not being very clear on why it failed.

What happens when you try to install the latest realm package?

**Comment by wilomgfx** [comment]
Same error here.

**Comment by blagoev** [comment]
@ShMcK Is this issue resolved. Can I close it?
