### ISSUE TITLE
Indistinguishable Primary Key Error 

### ISSUE THREAD

**Issue by mbalex99** [realm/realm-js#1156]
## Goals

A clearer error message that says what the primary key is. 

## Expected Results

This should tell me what the real primary key is in the error 

## Actual Results

```text
Error: Attempting to create an object of type 'ClusterNode' with an existing primary key value 'not implemented'.
    at Error (native)
    at inTransaction (/Users/maximilianalexander/realm/realm-object-server/components/common/dist/dao/BaseCollection.js:110:29)
    at Realm.db.write (/Users/maximilianalexander/realm/realm-object-server/components/common/dist/dao/BaseDao.js:32:30)
    at AdminDao.inTransaction (/Users/maximilianalexander/realm/realm-object-server/components/common/dist/dao/BaseDao.js:31:25)
    at ClusterNodeCollection.inTransaction (/Users/maximilianalexander/realm/realm-object-server/components/common/dist/dao/BaseCollection.js:71:25)
    at ClusterNodeCollection.create (/Users/maximilianalexander/realm/realm-object-server/components/common/dist/dao/BaseCollection.js:109:21)
    at config.sync.servers.forEach.clusterNodeConfig (/Users/maximilianalexander/realm/realm-object-server/object-server/src/node/configuration.js:436:23)
    at Array.forEach (native)
    at Object.mirrorConfigToAdminRealm (/Users/maximilianalexander/realm/realm-object-server/object-server/src/node/configuration.js:434:23)
    at ProxyService.start (/Users/maximilianalexander/realm/realm-object-server/object-server/src/node/services/proxy.js:152:19)
```

## Steps to Reproduce

Create an object in a write transaction with a missing primary key value. 

Thanks to @bdash for the link. His comment: 

> In that context, `not implemented` appears due to realm-js not implementing `print` on its object accessor implementation: https://github.com/realm/realm-js/blob/master/src/js_object_accessor.hpp#L124 
> That makes it impossible to tell from that exception what the real primary key value was

## Version of Realm and Tooling

- Realm JS SDK Version: 1.8.3
- Node or React Nattve: Node
- Client OS & Version: MacOSX
- Which debugger for React Native: None

**Comment by cesargdm** [comment]
Happens the same to me...
