### ISSUE TITLE
Can't build on macOS following the README

### ISSUE THREAD

**Issue by simonask** [realm/realm-js#1281]
With Node.js 7.1 (and 8.4), I get the following when trying to build according to the instructions in the README.md:

```
$ npm install --build-from-source=realm
> realm@2.0.0-rc5 install /Volumes/Code/realm-js
> node-pre-gyp install --fallback-to-build

  TOUCH Release/obj.target/realm-core.stamp
  TOUCH Release/obj.target/realm-sync.stamp
  CXX(target) Release/obj.target/object-store/src/object-store/src/binding_callback_thread_observer.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/collection_notifications.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/index_set.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/list.o
In file included from ../src/object-store/src/list.cpp:22:
In file included from ../src/object-store/src/impl/realm_coordinator.hpp:22:
../src/object-store/src/shared_realm.hpp:29:10: fatal error: 'realm/sync/client.hpp' file not found
#include <realm/sync/client.hpp>
         ^
1 error generated.
make: *** [Release/obj.target/object-store/src/object-store/src/list.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/simon/.nvm/versions/node/v7.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Users/simon/.nvm/versions/node/v7.1.0/bin/node" "/Users/simon/.nvm/versions/node/v7.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Volumes/Code/realm-js/compiled/node-v51_darwin_x64/realm.node" "--module_name=realm" "--module_path=/Volumes/Code/realm-js/compiled/node-v51_darwin_x64"
gyp ERR! cwd /Volumes/Code/realm-js
gyp ERR! node -v v7.1.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/simon/.nvm/versions/node/v7.1.0/bin/node /Users/simon/.nvm/versions/node/v7.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Volumes/Code/realm-js/compiled/node-v51_darwin_x64/realm.node --module_name=realm --module_path=/Volumes/Code/realm-js/compiled/node-v51_darwin_x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Volumes/Code/realm-js/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:885:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Darwin 16.7.0
node-pre-gyp ERR! command "/Users/simon/.nvm/versions/node/v7.1.0/bin/node" "/Volumes/Code/realm-js/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Volumes/Code/realm-js
node-pre-gyp ERR! node -v v7.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute '/Users/simon/.nvm/versions/node/v7.1.0/bin/node /Users/simon/.nvm/versions/node/v7.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Volumes/Code/realm-js/compiled/node-v51_darwin_x64/realm.node --module_name=realm --module_path=/Volumes/Code/realm-js/compiled/node-v51_darwin_x64' (1)

npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/simon/.nvm/versions/node/v7.1.0/bin/node" "/Users/simon/.nvm/versions/node/v7.1.0/bin/npm" "install" "--build-from-source=realm"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! realm@2.0.0-rc5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the realm@2.0.0-rc5 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the realm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs realm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls realm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/Code/realm-js/npm-debug.log
```

**Comment by fealebenpae** [comment]
I don't suppose you have any of the `REALM_CORE_PREFIX` or `REALM_SYNC_PREFIX` variables exported in your shell? They will interfere with the automatic acquisition of the realm-core and realm-sync libraries.

I just tried to build the 2.0.0-rc5 tag and it works.

**Comment by simonask** [comment]
I do have those set. Unsetting them seems to work, except there are now other build issues associated with updating the dependency on Core to 3.0.0.

What is the proper way to use `REALM_CORE_PREFIX` and `REALM_SYNC_PREFIX` nowadays?

**Comment by blagoev** [comment]
for me it builds correctly so I assume something is off in the env you are using

**Comment by simonask** [comment]
Ah yes, the issue is that the `js-rc` branch in realm/realm-object-store is ancient.
