### ISSUE TITLE
Installation of realm fails on linux VM

### ISSUE THREAD

**Issue by iaaflaafc** [realm/realm-js#1785]
## Goals

Install realm on a linux VM using the command `npm install --save realm`

## Expected Results

Installation should be successful

## Actual Results

```
user@user-VirtualBox:~/tmp$ npm install --save realm

> realm@2.4.1 install /home/user/tmp/node_modules/realm
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://static.realm.io/node-pre-gyp/2.4.1/realm-v2.4.1-node-v64-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for realm@2.4.1 and node@10.1.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
make: Entering directory '/home/user/tmp/node_modules/realm/build'
  TOUCH Release/obj.target/OpenSSL.stamp
  ACTION binding_gyp_vendored_realm_target_download_realm /home/user/tmp/node_modules/realm/vendor/realm-linux-x64
(node:22909) ExperimentalWarning: The fs.promises API is experimental
Resolved requirements: { CORE_SERVER_FOLDER: 'core',
  CORE_ARCHIVE: 'realm-core-5.6.0.tgz',
  CORE_ARCHIVE_ROOT: 'realm-core-5.6.0' }
No lockfile found at the target, proceeding.
Download url: https://static.realm.io/downloads/core/realm-core-5.6.0.tgz
Extracting realm-core-5.6.0.tgz => /home/user/tmp/node_modules/realm/vendor/realm-linux-x64
Success
  TOUCH Release/obj.target/vendored-realm.stamp
  TOUCH Release/obj.target/realm-core.stamp
  CXX(target) Release/obj.target/object-store/src/object-store/src/binding_callback_thread_observer.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/collection_notifications.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/index_set.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/list.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/object.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/placeholder.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/object_schema.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/object_store.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/results.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/schema.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/shared_realm.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/thread_safe_reference.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/impl/collection_change_builder.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/impl/collection_notifier.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/impl/list_notifier.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/impl/object_notifier.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/impl/primitive_list_notifier.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/impl/realm_coordinator.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/impl/results_notifier.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/impl/transact_log_handler.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/impl/weak_realm_notifier.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/util/uuid.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/impl/epoll/external_commit_helper.o
  AR(target) Release/obj.target/object-store.a
  COPY Release/object-store.a
  CXX(target) Release/obj.target/realm/src/js_realm.o
In file included from ../src/js_realm.cpp:21:0:
../src/js_types.hpp: In constructor ‘realm::js::TypeErrorException::TypeErrorException(NativeAccessor&, realm::StringData, const realm::Property&, ValueType)’:
../src/js_types.hpp:91:51: error: expected unqualified-id before ‘typeof’
                                          accessor.typeof(value),
                                                   ^~~~~~
../src/js_types.hpp: At global scope:
../src/js_types.hpp:110:24: error: expected unqualified-id before ‘typeof’
     static const char *typeof(ContextType, const ValueType &);
                        ^~~~~~
../src/js_types.hpp:110:23: error: expected ‘;’ at end of member declaration
     static const char *typeof(ContextType, const ValueType &);
                       ^
../src/js_types.hpp:110:42: error: expected primary-expression before ‘,’ token
     static const char *typeof(ContextType, const ValueType &);
                                          ^
../src/js_types.hpp:110:44: error: expected primary-expression before ‘const’
     static const char *typeof(ContextType, const ValueType &);
                                            ^~~~~
../src/js_types.hpp:110:44: error: expected ‘)’ before ‘const’
realm.target.mk:124: recipe for target 'Release/obj.target/realm/src/js_realm.o' failed
make: *** [Release/obj.target/realm/src/js_realm.o] Error 1
make: Leaving directory '/home/user/tmp/node_modules/realm/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
gyp ERR! System Linux 4.15.0-20-generic
gyp ERR! command "/home/user/.nvm/versions/node/v10.1.0/bin/node" "/home/user/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/user/tmp/node_modules/realm/compiled/node-v64_linux_x64/realm.node" "--module_name=realm" "--module_path=/home/user/tmp/node_modules/realm/compiled/node-v64_linux_x64"
gyp ERR! cwd /home/user/tmp/node_modules/realm
gyp ERR! node -v v10.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/user/.nvm/versions/node/v10.1.0/bin/node /home/user/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/user/tmp/node_modules/realm/compiled/node-v64_linux_x64/realm.node --module_name=realm --module_path=/home/user/tmp/node_modules/realm/compiled/node-v64_linux_x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/user/tmp/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:957:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:5)
node-pre-gyp ERR! System Linux 4.15.0-20-generic
node-pre-gyp ERR! command "/home/user/.nvm/versions/node/v10.1.0/bin/node" "/home/user/tmp/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/user/tmp/node_modules/realm
node-pre-gyp ERR! node -v v10.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/home/user/.nvm/versions/node/v10.1.0/bin/node /home/user/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/user/tmp/node_modules/realm/compiled/node-v64_linux_x64/realm.node --module_name=realm --module_path=/home/user/tmp/node_modules/realm/compiled/node-v64_linux_x64' (1)
npm WARN tmp@1.0.0 No description
npm WARN tmp@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! realm@2.4.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the realm@2.4.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-05-09T10_26_29_556Z-debug.log
```

## Steps to Reproduce
Run the following commands
- `mdkir tmp`
- `npm init -y`
- `npm install --save realm`

## Version of Realm and Tooling

- Realm JS SDK Version: 2.4.1
- Node or React Native: Node
- Client OS & Version: Lubuntu 18.04

**Comment by fealebenpae** [comment]
We don't have pre-built binaries for Node.js 10 yet. I suggest downgrading to 9 or 8.

**Comment by iaaflaafc** [comment]
I tried with node version v8.11.1.

The issue is not seen. Installation is successful.

I will close this issue

**Comment by rodrigogs** [comment]
I'm having a related problem:
`Error: Cannot find module '/home/rodrigo/IdeaProjects/my-project/node_modules/realm/compiled/node-v64_linux_x64/realm.node'`

**Comment by batjko** [comment]
Fails for me on Node 10.15.2, with realm 2.12.0:

![image](https://user-images.githubusercontent.com/7287076/54028440-e2f63280-419c-11e9-9557-1743f146ecf1.png)

**Comment by fealebenpae** [comment]
What's your Linux distro and processor architecture?

**Comment by batjko** [comment]
I actually found out that it will work when I downgrade to Node 8 (like apparently others have seen as well). It's a shame since 10 has been LTS for a while now and 11 is stable so would be good not to have to downgrade.

For reference:

> What's your Linux distro and processor architecture? 

Linux Ubuntu 18.10 64bit

**Comment by fealebenpae** [comment]
2.12 doesn't have prebuilt binaries for Node.js 10, but you could try the latest version which should work out of the box. We added Node.js 10 binaries in 2.19.0.
