### ISSUE TITLE
node-pre-gyp ERR! build error

### ISSUE THREAD

**Issue by Dimous** [realm/realm-js#1809]
Hi!
I have a problem with installation.

```
yarn install --next
yarn install v1.6.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > react-native@0.55.4" has incorrect peer dependency "react@16.3.1".
warning "react-native > eslint-plugin-react-native@3.2.1" has unmet peer dependency "eslint@^3.17.0 || ^4.0.0".
warning " > react-navigation-mobx-helpers@1.0.0" has incorrect peer dependency "react-navigation@^1.x".
[4/4] Building fresh packages...
[1/1] ⠂ realm: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\kasim\AppData\Roaming\npm\node_modu
[-/1] ⠂ waiting...
[-/1] ⠄ waiting...
[-/1] ⠄ waiting...
error C:\Users\kasim\Desktop\Experiments\budget\node_modules\realm: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: C:\Users\kasim\Desktop\Experiments\budget\node_modules\realm
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@10.1.0 | win32 | x64
node-pre-gyp info check checked for "C:\Users\kasim\Desktop\Experiments\budget\node_modules\realm\compiled\node-v64_win32_x64\realm.node" (not found)
node-pre-gyp http GET https://static.realm.io/node-pre-gyp/2.6.0/realm-v2.6.0-node-v64-win32-x64.tar.gz
node-pre-gyp http 404 https://static.realm.io/node-pre-gyp/2.6.0/realm-v2.6.0-node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://static.realm.io/node-pre-gyp/2.6.0/realm-v2.6.0-node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for realm@2.6.0 and node@10.1.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://static.realm.io/node-pre-gyp/2.6.0/realm-v2.6.0-node-v64-win32-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@10.1.0 | win32 | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@10.1.0 | win32 | x64
gyp info spawn C:\Users\kasim\AppData\Local\Android\ndk\r15c\prebuilt\windows-x86_64\bin\python2.EXE
gyp info spawn args [ 'C:\\Users\\kasim\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\kasim\\Desktop\\Experiments\\budget\\node_modules\\realm\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\kasim\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\kasim\\.node-gyp\\10.1.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\kasim\\.node-gyp\\10.1.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\kasim\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\kasim\\.node-gyp\\10.1.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\kasim\\Desktop\\Experiments\\budget\\node_modules\\realm',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\kasim\\Desktop\\Experiments\\budget\\node_modules\\realm\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Warning: Missing input files:
C:\Users\kasim\Desktop\Experiments\budget\node_modules\realm\build\..\scripts\set-version.sh
C:\Users\kasim\Desktop\Experiments\budget\node_modules\realm\build\..\scripts\changelog-header.sh
C:\Users\kasim\Desktop\Experiments\budget\node_modules\realm\build\..\src\object-store\src\util\compiler.hpp
C:\Users\kasim\Desktop\Experiments\budget\node_modules\realm\build\..\scripts\test.sh
C:\Users\kasim\Desktop\Experiments\budget\node_modules\realm\build\..\scripts\publish.sh
C:\Users\kasim\Desktop\Experiments\budget\node_modules\realm\build\..\lib\browser\util.jsscripts\build-node-pre-gyp.ps1
C:\Users\kasim\Desktop\Experiments\budget\node_modules\realm\build\..\src\object-store\src\descriptor_ordering.hpp
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@10.1.0 | win32 | x64
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
�믮������ ��᫥����⥫쭠� ᡮઠ �஥�⮢ � �⮬ �襭��. �⮡� ������� ��ࠫ������ ᡮ��, ������� ��ࠬ��� "/m".
  download-realm
  (node:3324) ExperimentalWarning: The fs.promises API is experimental
  Resolved requirements: { CORE_SERVER_FOLDER: 'core/v5.6.0/windows/x64/nouwp/Release',
    CORE_ARCHIVE: 'realm-core-Release-v5.6.0-Windows-x64-devel.tar.gz' }
  No lockfile found at the target, proceeding.
  Download url: https://static.realm.io/downloads/core/v5.6.0/windows/x64/nouwp/Release/realm-core-Release-v5.6.0-Windows-x64-devel.tar.gz
  Extracting realm-core-Release-v5.6.0-Windows-x64-devel.tar.gz => C:\Users\kasim\Desktop\Experiments\budget\node_modules\realm\vendor\realm-win-x64
  Success
  binding_callback_thread_observer.cpp
  collection_notifications.cpp
  index_set.cpp
  list.cpp
  object.cpp
  placeholder.cpp
  object_schema.cpp
  object_store.cpp
  results.cpp
  schema.cpp
  shared_realm.cpp
  thread_safe_reference.cpp
  collection_change_builder.cpp
  collection_notifier.cpp
  list_notifier.cpp
  object_notifier.cpp
  primitive_list_notifier.cpp
  realm_coordinator.cpp
  results_notifier.cpp
  transact_log_handler.cpp
  weak_realm_notifier.cpp
  uuid.cpp
  external_commit_helper.cpp
  win_delay_load_hook.cc
  object-store.vcxproj -> C:\Users\kasim\Desktop\Experiments\budget\node_modules\realm\build\Release\\object-store.lib
  js_realm.cpp
  node_init.cpp
  platform.cpp
  win_delay_load_hook.cc
c:\users\kasim\desktop\experiments\budget\node_modules\realm\src\node\node_class.hpp(224): error C2664: "v8::Maybe<bool> v8::Object::SetAccessor(v8::Local<v8::Context>,v8::Local<v8::Name>,v8::AccessorNameGetterCallback,v8::AccessorNameSetterCallback,v8::MaybeLocal<v8::Value>,v8::AccessControl,v8::PropertyAttribute,v8::SideEffectType)": ���������� �८�ࠧ����� ��㬥�� 2 �� "const realm::node::Types::PropertyGetterCallback" � "v8::Local<v8::Name>" (������������ ��室�� 䠩� ..\src\node\node_init.cpp) [C:\Users\kasim\Desktop\Experiments\budget\node_modules\realm\build\realm.vcxproj]
  c:\users\kasim\desktop\experiments\budget\node_modules\realm\src\node\node_class.hpp(224): note: �� ���� ��������� �� ᬮ� �ਭ��� ��室�� ⨯, ���� ࠧ�襭�� ��ॣ�㧪� ��������� ���������筮 (������������ ��室�� 䠩� ..\src\node\node_init.cpp)
  c:\users\kasim\desktop\experiments\budget\node_modules\realm\src\node\node_class.hpp(139): note: �믮������ ��������� ��뫪� �� ��������� 蠡��� �㭪樨 "void realm::node::ObjectWrap<ClassType>::setup_property<v8::Object>(v8::Local<v8::Object>,const std::string &,const realm::node::PropertyType &)"
          with
          [
              ClassType=realm::js::RealmClass<realm::node::Types>
          ] (������������ ��室�� 䠩� ..\src\node\node_init.cpp)
  c:\users\kasim\desktop\experiments\budget\node_modules\realm\src\node\node_class.hpp(139): note: �믮������ ��������� ��뫪� �� ��������� 蠡��� �㭪樨 "void realm::node::ObjectWrap<ClassType>::setup_property<v8::Object>(v8::Local<v8::Object>,const std::string &,const realm::node::PropertyType &)"
          with
          [
              ClassType=realm::js::RealmClass<realm::node::Types>
          ] (������������ ��室�� 䠩� ..\src\node\node_init.cpp)
  c:\users\kasim\desktop\experiments\budget\node_modules\realm\src\node\node_class.hpp(132): note: �� �������樨 �㭪樨-童�� "<��� ������>" ����� ����� <��� ������> (������������ ��室�� 䠩� ..\src\node\node_init.cpp)
  c:\users\kasim\desktop\experiments\budget\node_modules\realm\src\js_realm.hpp(333): note: �믮������ ��������� ��뫪� �� ��������� 蠡��� �㭪樨 "v8::Local<v8::Function> realm::node::ObjectWrap<ClassType>::create_constructor(v8::Isolate *)"
          with
          [
              ClassType=realm::js::RealmClass<realm::node::Types>
          ] (������������ ��室�� 䠩� ..\src\node\node_init.cpp)
  c:\users\kasim\desktop\experiments\budget\node_modules\realm\src\node\node_class.hpp(297): note: �믮������ ��������� ��뫪� �� ��������� 蠡��� ����� "realm::node::ObjectWrap<ClassType>"
          with
          [
              ClassType=realm::js::RealmClass<realm::node::Types>
          ] (������������ ��室�� 䠩� ..\src\node\node_init.cpp)
  c:\users\kasim\desktop\experiments\budget\node_modules\realm\src\js_realm.hpp(333): note: �믮������ ��������� ��뫪� �� ��������� 蠡��� ����� "realm::js::ObjectWrap<T,realm::js::RealmClass<T>>"
          with
          [
              T=realm::node::Types
          ] (������������ ��室�� 䠩� ..\src\node\node_init.cpp)
  c:\users\kasim\desktop\experiments\budget\node_modules\realm\src\js_realm.hpp(332): note: �� �������樨 �㭪樨-童�� "<��� ������>" ����� ����� <��� ������> (������������ ��室�� 䠩� ..\src\node\node_init.cpp)
  c:\users\kasim\desktop\experiments\budget\node_modules\realm\src\node\node_init.cpp(27): note: �믮������ ��������� �� 뫪� �� ��������� 蠡��� �㭪樨 "v8::Local<v8::Function> realm::js::RealmClass<realm::node::Types>::create_constructor(v8::Isolate *)"
  c:\users\kasim\desktop\experiments\budget\node_modules\realm\src\node\node_init.cpp(27): note: �믮������ ��������� �� 뫪� �� ��������� 蠡��� ����� "realm::js::RealmClass<realm::node::Types>"
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\kasim\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\kasim\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\kasim\\Desktop\\Experiments\\budget\\node_modules\\realm\\compiled\\node-v64_win32_x64\\realm.node" "--module_name=realm" "--module_path=C:\\Users\\kasim\\Desktop\\Experiments\\budget\\node_modules\\realm\\compiled\\node-v64_win32_x64"
gyp ERR! cwd C:\Users\kasim\Desktop\Experiments\budget\node_modules\realm
gyp ERR! node -v v10.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\kasim\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\kasim\Desktop\Experiments\budget\node_modules\realm\compiled\node-v64_win32_x64\realm.node --module_name=realm --module_path=C:\Users\kasim\Desktop\Experiments\budget\node_modules\realm\compiled\node-v64_win32_x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\kasim\Desktop\Experiments\budget\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:957:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:5)
node-pre-gyp ERR! System Windows_NT 10.0.16299
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\kasim\\Desktop\\Experiments\\budget\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\kasim\Desktop\Experiments\budget\node_modules\realm
node-pre-gyp ERR! node -v v10.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\kasim\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gy
```

## Version of Realm and Tooling

- Realm JS SDK Version: 2.6.0
- Node or React Native: 0.55.4
- Client OS & Version: Windows 10 64
- Which debugger for React Native: None

**Comment by fealebenpae** [comment]
We don’t support Node.js 10 just yet - you can downgrade to 9 or 8.

**Comment by Dimous** [comment]
Ok. Thank you!
