### ISSUE TITLE
Realm fails to install on Mac. 'npm install --save realm' fails

### ISSUE THREAD

**Issue by FredOleary** [realm/realm-js#1853]
Hello, I'm having issues installing realm when following your getting started at: https://realm.io/docs/javascript/latest/#getting-started

Install realm 'npm install --save realm' is resulting in C++ compilation errors and the install fails. See details below:

I'm installing on a Mac, Xcode version 9.2

  CXX(target) Release/obj.target/realm/src/node/node_init.o
In file included from ../src/node/node_init.cpp:19:
In file included from ../src/node/node_init.hpp:29:
../src/node/node_class.hpp:306:25: error: no member named 'Callee' in 'v8::FunctionCallbackInfo<v8::Value>'
        F(isolate, info.Callee(), info.This(), arguments.size(), arguments.data(), return_value);

10 errors generated.
make: *** [Release/obj.target/realm/src/node/node_init.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
gyp ERR! System Darwin 17.3.0

**Comment by kneth** [comment]
Please fill out the issue template (the one, you deleted) to provide details on your environment.

**Comment by edzh1** [comment]
@kneth Hi, i think you can close this issue because it was recreated by original author here https://github.com/realm/realm-js/issues/1857
