### ISSUE TITLE
Appending `/auth` to login makes it fail even though it is the correct URL

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-js#1867]
Example:

```
Realm.Sync.User.registerWithProvider(URL + '/auth', { provider: PROVIDER, providerToken: USER_ID, userInfo: USER_INFO })
    .then(user => {
        console.log("User logged in: " + user.identity);
    })
    .catch(error => console.log(error));
```

Results in 

```
{ Error: Could not authenticate: Realm Object Server didn't respond with valid JSON
    at AuthError.Error (native)
    at new AuthError (/Users/cm/Realm/example-app/node_modules/realm/lib/errors.js:22:25)
    at response.text.then (/Users/cm/Realm/example-app/node_modules/realm/lib/user-methods.js:250:27)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  name: 'AuthError',
  message: 'Could not authenticate: Realm Object Server didn\'t respond with valid JSON',
  stack: 'Error: Could not authenticate: Realm Object Server didn\'t respond with valid JSON\n    at AuthError.Error (native)\n    at new AuthError (/Users/cm/Realm/twomen-query-test/node_modules/realm/lib/errors.js:22:25)\n    at response.text.then (/Users/cm/Realm/example-app/node_modules/realm/lib/user-methods.js:250:27)\n    at process._tickCallback (internal/process/next_tick.js:109:7)',
  title: 'Could not authenticate: Realm Object Server didn\'t respond with valid JSON',
  body: '<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot POST /auth/auth</pre>\n</body>\n</html>\n' }
```

We should detect that this is the correct auth URL and just use it instead of uncritically appending `auth`

**Comment by kneth** [comment]
`/auth` is unconditionally appended in https://github.com/realm/realm-js/blob/master/lib/user-methods.js#L237. The API doc says "server" and "url" but we might only append `/auth` if the parameter does not end with `/auth`.
