### ISSUE TITLE
cannot locate symbol "_ZN5realm8jni_util9hack_initEv" referenced by "/data/app/.../lib/x86/librealmreact.so"

### ISSUE THREAD

**Issue by Dimous** [realm/realm-js#1904]
## Actual Results

java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN5realm8jni_util9hack_initEv" referenced by "/data/app/appname/lib/x86/librealmreact.so"...
        at java.lang.Runtime.load0(Runtime.java:928)
        at java.lang.System.load(System.java:1621)
        at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:71)
        at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:247)
        at io.realm.react.RealmReactModule.<clinit>(RealmReactModule.java:59)
        at io.realm.react.RealmReactPackage.createNativeModules(RealmReactPackage.java:31)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1172)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1142)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1080)
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:113)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:911)
        at java.lang.Thread.run(Thread.java:764)

## Steps to Reproduce

Upgrade from 2.10.0, build and run application

> **2.10.0 is working, but 2.11.0 is not**

## Version of Realm and Tooling

- Realm JS SDK Version: 2.11.0
- Node or React Native: 0.55.4
- Client OS & Version: Windows 10 64x
- Which debugger for React Native: None

**Comment by kennygoff** [comment]
I ran into this issue as well. Project will build, then crashes on app open in simulator. Runs fine on device for me at least. Also tested on a fresh project `react-native init RealmTestApp` and installed npm's latest (2.11.0) to reproduce.

As mentioned above, downgrading to `2.10.0` fixed the problem.

**Comment by RoysyLee** [comment]
+1

**Comment by mortezaalizadeh** [comment]
I never managed to get the error on my simulator, but the app crashes once it is launched. I reverted the realmjs to version 2.10.0 and it is all working fine.

**Comment by Dimous** [comment]
2.11.0 is a monkeypatch for race condition which leads to crash on samsung devices, so not _fine_

**Comment by otaviogaiao** [comment]
I just got the same error on the simulator (I haven't tested on an actual device just yet). What to do now?

**Comment by TPXP** [comment]
Not sure if this helps, but I'm also facing this problem on Realm 2.3.5.

**Comment by behiunforgiven** [comment]
I have the same problem with 2.11.0.

**Comment by prayuditb** [comment]
I have the same error with 2.11.0.
I'm currently using react native 0.55 and I've tried to downgrade to react native 0.48 and got the same result.

**Comment by prayuditb** [comment]
Upgrading to 2.10.0 works for me, thanks

**Comment by kneth** [comment]
My mistake 😢 but luckily very easy to fix - see #1907.

I plan to do a release either today or tomorrow.

**Comment by vimalN1992** [comment]
Any update on this is the new release is done?

**Comment by kneth** [comment]
@vimalN1992 Sorry to mention it. I released 2.12.0 yesterday evening (CEST).
