### ISSUE TITLE
Improved docs on custom authentication

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#1978]
https://realm.io/docs/javascript/latest/#google shows examples on using `registerWithProvider` which throws errors when used.

## Gooogle
```
const googleAccessToken = 'acc3ssT0ken...';
Realm.Sync.User.registerWithProvider('http://my.realm-auth-server.com:9080', 'google', googleAccessToken, (error, user) => { /* ... */ });
```

## Facebook
```
const fbAccessToken = 'acc3ssT0ken...';
Realm.Sync.User.registerWithProvider('http://my.realm-auth-server.com:9080', 'facebook', fbAccessToken, (error, user) => { /* ... */ });
```

But it seems like these method signatures has been deprecated and removed, when I use this with:

```
Realm.Sync.User.registerWithProvider('http://my.realm-auth-server.com:9080', 'nickname', 'whatever');
```

It get

```
TypeError: param 1 must be of type object
    at checkTypes (/Users/kraenhansen/Repositories/my-first-realm-app/react-web/node_modules/realm/lib/user-methods.js:36:19)
    at Function.registerWithProvider (/Users/kraenhansen/Repositories/my-first-realm-app/react-web/node_modules/realm/lib/user-methods.js:368:17)
    at run (/Users/kraenhansen/Repositories/my-first-realm-app/react-web/scripts/create-realm.js:31:38)
    at Object.<anonymous> (/Users/kraenhansen/Repositories/my-first-realm-app/react-web/scripts/create-realm.js:40:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
```

**Comment by fxl5R** [comment]
the same issue here @kraenhansen did you get a solution?

**Comment by PatrickLambert1101** [comment]
Same Issue, any updates on Docs for JWT authentication with the Login Method
]
