### ISSUE TITLE
App crash on start

### ISSUE THREAD

**Issue by milanp93** [realm/realm-js#2015]
When i try to make release apk my app crash on the start of the app. in debug app everything work good.

Error:
```
FATAL EXCEPTION: Thread-8498
                                                   Process: com.coinatmradar, PID: 17875
                                                   Theme: themes:{default=overlay:com.cyngn.smartfren, iconPack:com.cyngn.smartfren, fontPkg:com.cyngn.hexo, com.android.systemui=overlay:com.cyngn.smartfren, com.android.systemui.navbar=overlay:com.cyngn.smartfren}
                                                   java.lang.ExceptionInInitializerError
                                                       at io.realm.react.RealmReactPackage.createNativeModules(RealmReactPackage.java:31)
                                                       at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106)
                                                       at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1172)
                                                       at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1142)
                                                       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1080)
                                                       at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:113)
                                                       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:911)
                                                       at java.lang.Thread.run(Thread.java:818)
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "io.realm.react.util.SSLHelper" on path: DexPathList[[zip file "/data/app/com.coinatmradar-1/base.apk"],nativeLibraryDirectories=[/data/app/com.coinatmradar-1/lib/arm, /data/app/com.coinatmradar-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                       at java.lang.Runtime.nativeLoad(Native Method)
                                                       at java.lang.Runtime.doLoad(Runtime.java:435)
                                                       at java.lang.Runtime.load(Runtime.java:330)
                                                       at java.lang.System.load(System.java:1069)
                                                       at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:71)
                                                       at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
                                                       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
                                                       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:247)
                                                       at io.realm.react.RealmReactModule.<clinit>(RealmReactModule.java:59)
                                                       at io.realm.react.RealmReactPackage.createNativeModules(RealmReactPackage.java:31) 
                                                       at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106) 
                                                       at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1172) 
                                                       at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1142) 
                                                       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1080) 
                                                       at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:113) 
                                                       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:911) 
                                                       at java.lang.Thread.run(Thread.java:818) 
                                                   	Suppressed: java.lang.ClassNotFoundException: io.realm.react.util.SSLHelper
                                                       at java.lang.Class.classForName(Native Method)
                                                       at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                       at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                       		... 18 more
                                                    Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

first i tred with: 
 "react": "16.0.0",
 "react-native": "0.55.0",
 "realm": "^2.2.8",
after that i tried with:
 "react": "16.4.1",
 "react-native": "0.55.4",
 "realm": "^2.13.0",

doesn't work too.

**Comment by brayanL** [comment]
**Hey - looks like you forgot to add a T:*** what does mean, i have the same issue with realmjs on react native any solution..?, thanks..!

**Comment by meysam-70** [comment]
i have this error too
did anyone solve this problem????????

**Comment by Shabnam-Veranloo** [comment]
i have this problem too !!!
please help

**Comment by meysam-70** [comment]
I added this line to proguard and my problem solved
-keep class io.realm.react.**

**Comment by rassemdev** [comment]
> -keep class io.realm.react.**

where did you add this?

**Comment by meysam-70** [comment]
> > -keep class io.realm.react.**
> 
> where did you add this?

in   proguard-rules.pro

**Comment by AshleyEke** [comment]
I'm having this issue but not using expo, I'm using metro instead. I got this straight from generating the template:
`npx react-native init RealmTemplate --template @realm/react-native-template-ts`
