### ISSUE TITLE
realm@2.21.1 install: `node-pre-gyp install --fallback-to-build`

### ISSUE THREAD

**Issue by fadeli1** [realm/realm-js#2183]
## Goals

npm install --save realm

## Expected Results

npm install --save realm  success

## Actual Results
```
> realm@2.21.1 install D:\lzzwork\react_native\swpaam\node_modules\realm
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://static.realm.io/node-pre-gyp/2.21.1/realm-v2.21.1-node-v59-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for realm@2.21.1 and node@9.5.0 (node-v59 ABI, unknown) (falling back to source compile with node-gyp)
Warning: Missing input files:
D:\lzzwork\react_native\swpaam\node_modules\realm\build\..\lib\browser\util.jsscripts\build-node-pre-gyp.ps1
D:\lzzwork\react_native\swpaam\node_modules\realm\build\..\src\object-store\src\descriptor_ordering.hpp
D:\lzzwork\react_native\swpaam\node_modules\realm\build\..\src\object-store\src\util\compiler.hpp
D:\lzzwork\react_native\swpaam\node_modules\realm\build\..\scripts\test.sh
D:\lzzwork\react_native\swpaam\node_modules\realm\build\..\scripts\set-version.sh
D:\lzzwork\react_native\swpaam\node_modules\realm\build\..\scripts\changelog-header.sh
D:\lzzwork\react_native\swpaam\node_modules\realm\build\..\scripts\publish.sh
D:\lzzwork\react_native\swpaam\node_modules\realm\build\..\src\object-store\src\util\time.hpp
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build t
ools for v141 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install v141 bui
ld tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-cli
ck the solution, and then selecting "Retarget solution". [D:\lzzwork\react_native\swpaam\node_modules\realm\build\OpenS
SL.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build t
ools for v141 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install v141 bui
ld tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-cli
ck the solution, and then selecting "Retarget solution". [D:\lzzwork\react_native\swpaam\node_modules\realm\build\scrip
ts.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build t
ools for v141 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install v141 bui
ld tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-cli
ck the solution, and then selecting "Retarget solution". [D:\lzzwork\react_native\swpaam\node_modules\realm\build\vendo
red-realm.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\fade\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\fade\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=D:\\lzzwork\\react_native\\swpaam\\node_modules\\realm\\compiled\\node-v59_win32_x64\\realm.node" "--module_name=realm" "--module_path=D:\\lzzwork\\react_native\\swpaam\\node_modules\\realm\\compiled\\node-v59_win32_x64" "--napi_version=2" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v59"
gyp ERR! cwd D:\lzzwork\react_native\swpaam\node_modules\realm
gyp ERR! node -v v9.5.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'D:\Program Files\nodejs\node.exe C:\Users\fade\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=D:\lzzwork\react_native\swpaam\node_modules\realm\compiled\node-v59_win32_x64\realm.node --module_name=realm --module_path=D:\lzzwork\react_native\swpaam\node_modules\realm\compiled\node-v59_win32_x64 --napi_version=2 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v59' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\lzzwork\react_native\swpaam\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:943:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\lzzwork\\react_native\\swpaam\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\lzzwork\react_native\swpaam\node_modules\realm
node-pre-gyp ERR! node -v v9.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute 'D:\Program Files\nodejs\node.exe C:\Users\fade\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=D:\lzzwork\react_native\swpaam\node_modules\realm\compiled\node-v59_win32_x64\realm.node --module_name=realm --module_path=D:\lzzwork\react_native\swpaam\node_modules\realm\compiled\node-v59_win32_x64 --napi_version=2 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v59' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! realm@2.21.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the realm@2.21.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fade\AppData\Roaming\npm-cache\_logs\2018-12-18T14_47_56_189Z-debug.log
```

## Version of Realm and Tooling

- Realm JS SDK Version: realm v2.21.1 
- Node or React Native: node v9.5.0 & React Native v0.57.8 & npm v6.4.1
- Client OS & Version: windows 10

**Comment by fadeli1** [comment]
Very strange, I can't follow the most wanted new version.
But I can install realm@2.0.7
How can I install the latest ones and help me?

**Comment by fadeli1** [comment]
The test found:
The largest version I can install: realm@2.18.0

**Comment by gogoku** [comment]
Try installing Python and adding python to path,
I was facing a similar issue , doing it fixed it for me

**Comment by rajivshah3** [comment]
@fadeli1 have you tried `npm install -g windows-build-tools`? That sometimes resolves build issues on Windows

**Comment by fadeli1** [comment]
@rajivshah3 Hi
I try:
Npm install -g windows-build-tools
run:
Npm install --save realm
I get the following error:
`
download-realm
  Resolved requirements: { CORE_SERVER_FOLDER: 'core/v5.12.5/windows/x64/nouwp/Release',
    CORE_ARCHIVE: 'realm-core-Release-v5.12.5-Windows-x64-devel.tar.gz' }
  No lockfile found at the target, proceeding.
  Download url: https://static.realm.io/downloads/core/v5.12.5/windows/x64/nouwp/Release/realm-core-Release-v5.12.5-Win
  dows-x64-devel.tar.gz
  Downloading realm-core-Release-v5.12.5-Windows-x64-devel.tar.gz
  Extracting realm-core-Release-v5.12.5-Windows-x64-devel.tar.gz => D:\lzzwork\react_native\swpaam\node_modules\realm\v
  endor\realm-win-x64
  Success
  binding_callback_thread_observer.cpp
  collection_notifications.cpp
  index_set.cpp
  list.cpp
  object.cpp
  placeholder.cpp
  object_schema.cpp
  object_store.cpp
  results.cpp
  schema.cpp
  shared_realm.cpp
  thread_safe_reference.cpp
  collection_change_builder.cpp
  collection_notifier.cpp
  list_notifier.cpp
  object_notifier.cpp
  primitive_list_notifier.cpp
  realm_coordinator.cpp
  results_notifier.cpp
  transact_log_handler.cpp
  weak_realm_notifier.cpp
  uuid.cpp
  external_commit_helper.cpp
  win_delay_load_hook.cc
  object-store.vcxproj -> D:\lzzwork\react_native\swpaam\node_modules\realm\build\Release\\object-store.lib
  js_realm.cpp
  node_init.cpp
  platform.cpp
  win_delay_load_hook.cc
LINK : fatal error LNK1181: 无法打开输入文件“C:\src\vcpkg\installed\x64-windows-static\lib\libeay32.lib” [D:\lzzwork\react_nati
ve\swpaam\node_modules\realm\build\realm.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
`

**Comment by fadeli1** [comment]
Update node version v10.15.0
Successfully installed realm@2.21.1

**Comment by kneth** [comment]
@sambwest ABI v59 is Node 9, which is not LTS or even active. Try with either node 8 or node 10.

**Comment by sambwest** [comment]
@kneth I was actually using 11 but copied the link above to demonstrate the point. I downgraded to 10 and it went away. Thanks! Your comment pointed me in the right direction.

**Comment by KGDeveloper** [comment]
> @fadeli1你试过`npm install -g windows-build-tools`吗？这有时可以解决Windows上的构建问题

你好，我这变是mac，也是报错相同问题，请问怎么解决

**Comment by KGDeveloper** [comment]
> 将节点版本更新到v10.15.0已
> 成功安装realm@2.21.1

你好，我得是mac，请问你的怎么解决的

**Comment by fadeli1** [comment]
@KGDeveloper 
Update node version to v10.0+

**Comment by kneth** [comment]
I am closing the issue as I believe it is working for everybody now :smile:

**Comment by navneet-kumar** [comment]
Hi, I am unable to install realm, getting below error.
Is my version combination is not yet supported ?
$ node -v 
`v11.5.0`
$ react-native -v
`react-native-cli: 2.0.1`
`react-native: 0.57.8`
$ npm -v
`6.5.0`
$ npm install --save realm

```
> realm@2.22.0 install /Users/navneet.kumar/workspace/MyClinic/node_modules/realm
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://static.realm.io/node-pre-gyp/2.22.0/realm-v2.22.0-node-v67-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for realm@2.22.0 and node@11.5.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp) 
  TOUCH Release/obj.target/OpenSSL.stamp
  ACTION binding_gyp_vendored_realm_target_download_realm /Users/ts-navneet.kumar/workspace/MyClinic/node_modules/realm/vendor/realm-mac-x64
Resolved requirements: { SYNC_SERVER_FOLDER: 'sync',
  SYNC_ARCHIVE: 'realm-sync-node-cocoa-3.14.12.tar.gz',
  SYNC_ARCHIVE_ROOT: 'realm-sync-node-cocoa-3.14.12' }
No lockfile found at the target, proceeding.
Download url: https://static.realm.io/downloads/sync/realm-sync-node-cocoa-3.14.12.tar.gz
Downloading realm-sync-node-cocoa-3.14.12.tar.gz [==============================================================================================================================================================================================================] (9161k)
Extracting realm-sync-node-cocoa-3.14.12.tar.gz => /Users/ts-navneet.kumar/workspace/MyClinic/node_modules/realm/vendor/realm-mac-x64
Success
  TOUCH Release/obj.target/vendored-realm.stamp
  TOUCH Release/obj.target/realm-core.stamp
  TOUCH Release/obj.target/realm-sync.stamp
  CXX(target) Release/obj.target/object-store/src/object-store/src/binding_callback_thread_observer.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/collection_notifications.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/index_set.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/list.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/object.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/placeholder.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/object_schema.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/object_store.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/results.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/schema.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/shared_realm.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/thread_safe_reference.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/impl/collection_change_builder.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/impl/collection_notifier.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/impl/list_notifier.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/impl/object_notifier.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/impl/primitive_list_notifier.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/impl/realm_coordinator.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/impl/results_notifier.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/impl/transact_log_handler.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/impl/weak_realm_notifier.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/util/uuid.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/impl/apple/external_commit_helper.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/impl/apple/keychain_helper.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/sync/impl/apple/network_reachability_observer.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/sync/impl/apple/system_configuration.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/sync/partial_sync.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/sync/sync_config.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/sync/sync_manager.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/sync/sync_user.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/sync/sync_session.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/sync/impl/sync_file.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/sync/impl/sync_metadata.o
  CXX(target) Release/obj.target/object-store/src/object-store/src/sync/impl/work_queue.o
  LIBTOOL-STATIC Release/object-store.a
  CXX(target) Release/obj.target/realm/src/js_realm.o
  CXX(target) Release/obj.target/realm/src/node/node_init.o
In file included from ../src/node/node_init.cpp:19:
In file included from ../src/node/node_init.hpp:21:
In file included from ../src/node/node_string.hpp:21:
../src/node/node_types.hpp:52:42: error: no type named 'NamedPropertyGetterCallback' in namespace 'v8'; did you mean 'IndexPropertyGetterCallback'?
    using StringPropertyGetterCallback = v8::NamedPropertyGetterCallback;
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                         IndexPropertyGetterCallback
../src/node/node_types.hpp:50:11: note: 'IndexPropertyGetterCallback' declared here
    using IndexPropertyGetterCallback = Nan::IndexGetterCallback;
          ^
../src/node/node_types.hpp:53:42: error: no type named 'NamedPropertySetterCallback' in namespace 'v8'; did you mean 'IndexPropertySetterCallback'?
    using StringPropertySetterCallback = v8::NamedPropertySetterCallback;
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                         IndexPropertySetterCallback
../src/node/node_types.hpp:51:11: note: 'IndexPropertySetterCallback' declared here
    using IndexPropertySetterCallback = Nan::IndexSetterCallback;
          ^
../src/node/node_types.hpp:54:50: error: no type named 'NamedPropertyEnumeratorCallback' in namespace 'v8'; did you mean 'IndexedPropertyEnumeratorCallback'?
    using StringPropertyEnumeratorCallback = v8::NamedPropertyEnumeratorCallback;
                                             ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                 IndexedPropertyEnumeratorCallback
/Users/ts-navneet.kumar/.node-gyp/11.5.0/include/node/v8.h:5646:16: note: 'IndexedPropertyEnumeratorCallback' declared here
typedef void (*IndexedPropertyEnumeratorCallback)(
               ^
In file included from ../src/node/node_init.cpp:19:
In file included from ../src/node/node_init.hpp:25:
../src/node/node_function.hpp:41:19: error: no member named 'GetCallingContext' in 'v8::Isolate'; did you mean 'GetCurrentContext'?
    if (!isolate->GetCallingContext().IsEmpty()) {
                  ^~~~~~~~~~~~~~~~~
                  GetCurrentContext
/Users/ts-navneet.kumar/.node-gyp/11.5.0/include/node/v8.h:7727:18: note: 'GetCurrentContext' declared here
  Local<Context> GetCurrentContext();
                 ^
In file included from ../src/node/node_init.cpp:19:
In file included from ../src/node/node_init.hpp:29:
../src/node/node_class.hpp:191:23: error: no member named 'SetNamedPropertyHandler' in 'v8::ObjectTemplate'; did you mean 'SetIndexedPropertyHandler'?
        instance_tpl->SetNamedPropertyHandler(string_accessor.getter ? string_accessor.getter : get_nonexistent_property, set_property, 0, 0, string_accessor.enumerator);
                      ^~~~~~~~~~~~~~~~~~~~~~~
                      SetIndexedPropertyHandler
/Users/ts-navneet.kumar/.node-gyp/11.5.0/include/node/v8.h:6178:8: note: 'SetIndexedPropertyHandler' declared here
  void SetIndexedPropertyHandler(
       ^
In file included from ../src/node/node_init.cpp:19:
In file included from ../src/node/node_init.hpp:29:
In file included from ../src/node/node_class.hpp:23:
../src/js_class.hpp:92:17: error: no type named 'StringPropertyGetterCallback' in 'realm::node::Types'
    typename T::StringPropertyGetterCallback getter;
    ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/node/node_class.hpp:368:16: note: in instantiation of template class 'realm::js::StringPropertyType<realm::node::Types>' requested here
template<node::StringPropertyType::GetterType F>
               ^
In file included from ../src/node/node_init.cpp:19:
In file included from ../src/node/node_init.hpp:29:
In file included from ../src/node/node_class.hpp:23:
../src/js_class.hpp:93:17: error: no type named 'StringPropertySetterCallback' in 'realm::node::Types'
    typename T::StringPropertySetterCallback setter;
    ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/node/node_init.cpp:19:
In file included from ../src/node/node_init.hpp:29:
../src/node/node_class.hpp:373:10: error: called object type 'int' is not a function or function pointer
        F(isolate, info.This(), property, return_value);
        ~^
8 errors generated.
make: *** [Release/obj.target/realm/src/node/node_init.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/Cellar/node/11.5.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/ts-navneet.kumar/workspace/MyClinic/node_modules/realm/compiled/node-v67_darwin_x64/realm.node" "--module_name=realm" "--module_path=/Users/ts-navneet.kumar/workspace/MyClinic/node_modules/realm/compiled/node-v67_darwin_x64" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v67"
gyp ERR! cwd /Users/ts-navneet.kumar/workspace/MyClinic/node_modules/realm
gyp ERR! node -v v11.5.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/11.5.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/ts-navneet.kumar/workspace/MyClinic/node_modules/realm/compiled/node-v67_darwin_x64/realm.node --module_name=realm --module_path=/Users/ts-navneet.kumar/workspace/MyClinic/node_modules/realm/compiled/node-v67_darwin_x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v67' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/ts-navneet.kumar/workspace/MyClinic/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/11.5.0/bin/node" "/Users/ts-navneet.kumar/workspace/MyClinic/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/ts-navneet.kumar/workspace/MyClinic/node_modules/realm
node-pre-gyp ERR! node -v v11.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/Cellar/node/11.5.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/ts-navneet.kumar/workspace/MyClinic/node_modules/realm/compiled/node-v67_darwin_x64/realm.node --module_name=realm --module_path=/Users/ts-navneet.kumar/workspace/MyClinic/node_modules/realm/compiled/node-v67_darwin_x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v67' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! realm@2.22.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the realm@2.22.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ts-navneet.kumar/.npm/_logs/2019-01-17T06_04_11_573Z-debug.log"

```
>

**Comment by kneth** [comment]
@navneet-kumar We don't support node 11 yet, see #2149.

**Comment by navneet-kumar** [comment]
@kneth Thank you very much for the response.

**Comment by mikerosillo** [comment]
I had the same problem just downgrade node to 8 and than type the following 
 sudo npm install realm --allow-root=true  --unsafe-perm=true
problem solved!

**Comment by cihanbas** [comment]
I had some issue , when ı downloaded node 10 version it was solved 
https://nodejs.org/en/download/

**Comment by d-pardo** [comment]
> I had the same issue , when ı downloaded node 10 version it was solved
> https://nodejs.org/en/download/

Thanks @cihanbas ! I dont know why... I was working with node 12, after the downgrade to v10 (LTS), it worked.

**Comment by phoenixit99** [comment]
download: newest version node : https://nodejs.org/en/download/ 
After that install: 
sudo npm install realm --allow-root=true --unsafe-perm=true

**Comment by manu006** [comment]
Yeah If you install the latest version of node then it will clearly work.
As  **Realm uses latest version of node.**
Go for this link to download node : https://nodejs.org/en/download/
