### ISSUE TITLE
What's the api to set path for 'realm-object-server'? Or how to disable sync?

### ISSUE THREAD

**Issue by anysome** [realm/realm-js#2236]
/Users/asfun/js/Diary/build/mac/diary.app/Contents/Resources/app.asar/node_modules/realm/lib/index.js:152 Uncaught Error: make_dir() failed: Permission denied Path: /realm-object-server/
    at Object.<anonymous> (/Users/asfun/js/Diary/build/mac/diary.app/Contents/Resources/app.asar/node_modules/realm/lib/index.js:152:27)
    at Object.<anonymous> (/Users/asfun/js/Diary/build/mac/diary.app/Contents/Resources/app.asar/node_modules/realm/lib/index.js:157:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (file:///Users/asfun/js/Diary/build/mac/diary.app/Contents/Resources/app.asar/dist/electron/renderer.js:1:12321)

**Comment by anysome** [comment]
> try it: process.chdir(app.getPath('userData'))

It works. Thanks @BigSteel

**Comment by davidolu** [comment]
> try it: process.chdir(app.getPath('userData'))

works like charm
