### ISSUE TITLE
lib/user-methods.js's performFetch API is unstable across platforms

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#2274]
## Goals

We have to make a choice: Either the `performFetch` method of [lib/user-methods.js](https://github.com/realm/realm-js/blob/master/lib/user-methods.js#L107-L143) should adhere to the fetch API, which means that we should be able to [read header values from a response](https://github.com/realm/realm-js/blob/master/lib/user-methods.js#L376-L386) such as `response.headers.get('Content-Type')` or we should simplify the way we call the method making less assumptions on the shape of the response object (I don't recommend the latter).

In its current implementation `performFetch` performs very differently whether Realm JS is running on Node.js or in an environment with `fetch` available.

We currently have [tests failing](https://github.com/realm/realm-js/blob/master/tests/js/user-tests.js#L177-L187) on master due to this discrepancy in behaviour across platforms. 

## Version of Realm and Tooling

- Realm JS SDK Version: 2.24.0
- Node or React Native: Both - but mostly React Native and Electron exhibits regressions.
- Client OS & Version: N/A
- Which debugger for React Native: N/A

**Comment by tgoyne** [comment]
That test failed because the network request to github failed, not because it couldn't read the content type header.

**Comment by kraenhansen** [comment]
Okay - I might have been a little too quick in my conclusion.

**Comment by bradjonesca** [comment]
FYI: https://github.com/whatwg/fetch/issues/878

**Comment by kraenhansen** [comment]
I am sorry to report that we still have an issue with this implementation on Electron when called from the main process:

```
ReferenceError: XMLHttpRequest is not defined
     at fetchWithTimeout (/Users/kraenhansen/Repositories/realm-studio/node_modules/realm/lib/user-methods.js:82:17)
     at next (/Users/kraenhansen/Repositories/realm-studio/node_modules/realm/lib/user-methods.js:125:9)
     at Promise (/Users/kraenhansen/Repositories/realm-studio/node_modules/realm/lib/user-methods.js:140:13)
     at new Promise (<anonymous>)
     at performFetch (/Users/kraenhansen/Repositories/realm-studio/node_modules/realm/lib/user-methods.js:138:16)
     at _authenticate (/Users/kraenhansen/Repositories/realm-studio/node_modules/realm/lib/user-methods.js:337:19)
     at request.catch (/Users/kraenhansen/Repositories/realm-studio/node_modules/realm/lib/user-methods.js:341:20)
     at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by kneth** [comment]
Moreover, we should add support for exponential backoff and retrying for all platforms.

**Comment by kraenhansen** [comment]
This issue went away as we merged with the Stich SDK and introduced the realm-network-transport package (https://github.com/realm/realm-js/tree/master/packages/realm-network-transport).
