### ISSUE TITLE
Can't run on Windows 2012

### ISSUE THREAD

**Issue by jlubeck** [realm/realm-js#2288]
I'm trying to run a node app that works fine on other environments on a Windows Server 2012 computer. 

I'm getting this error: 
```
PS C:\workspace\realm-exporter> node index
internal/modules/cjs/loader.js:718
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\workspace\realm-exporter\node_modules\realm\compiled\node-v64_win32_x64\realm.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\workspace\realm-exporter\node_modules\realm\lib\index.js:103:28)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
```

But the `realm.node` file is indeed there.

Investigating on other sources, I found "Dependency Walker", an app that checks that all the required dependencies are installed on a windows computer. And it looks like realm.node is missing some on my computer. But I don't really know what they are or how to get them. I hope someone here knows 

![Screen Shot 2019-03-15 at 12 29 30 PM](https://user-images.githubusercontent.com/3067603/54446733-02053f00-471e-11e9-98dc-52758916f2fd.png)

Thank you!

**Comment by fealebenpae** [comment]
Hi @jlubeck,

Realm supports only Windows 8.1 and up. This means you need Windows Server 2012 R2.

**Comment by jlubeck** [comment]
Ouch... I don't know if I can make that upgrade, since it's a customer's computer... I'll find out.
So there is no way to install those files somehow?

**Comment by fealebenpae** [comment]
Those are internal Windows libraries, AFAIK. I don't think it's possible to install them on an older Windows.

**Comment by jlubeck** [comment]
Alright, thank you for your quick replies!
