### ISSUE TITLE
npm install failing on windows

### ISSUE THREAD

**Issue by msaracevic** [realm/realm-js#2329]
## Goals

`npm install` on windows

After trying to deal with gyp and python dependency, I ended up installing python with `windows-build-tools` and in my `npm` I have `python="C:\\Users\\sarac\\.windows-build-tools\\python27\\python.exe"`

## Expected Results

That it actually installs

## Actual Results

```sh
sarac@Aero15-X9: ~/Documents/Dev/formation/server (master*) $ npm install --build-from-source=realm

> realm@2.15.3 install C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
Warning: Missing input files:
C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm\build\..\scripts\publish.sh
C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm\build\..\scripts\set-version.sh
C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm\build\..\scripts\test.sh
C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm\build\..\scripts\changelog-header.sh
C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm\build\..\src\object-store\src\descriptor_ordering.hpp
C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm\build\..\lib\browser\util.jsscripts\build-node-pre-gyp.ps1
C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm\build\..\src\object-store\src\util\compiler.hpp
C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm\build\..\src\object-store\src\util\time.hpp
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm\build\OpenSSL.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on
 disk.
C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm\build\scripts.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on
 disk.
C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm\build\vendored-realm.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file ex
ists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\sarac\\Documents\\Dev\\formation\\server\\node_modules\\realm\\compiled\\
node-v64_win32_x64\\realm.node" "--module_name=realm" "--module_path=C:\\Users\\sarac\\Documents\\Dev\\formation\\server\\node_modules\\realm\\compiled\\node-v64_win32_x64" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm\compil
ed\node-v64_win32_x64\realm.node --module_name=realm --module_path=C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm\compiled\node-v64_win32_x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\sarac\Documents\Dev\formation\server\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\sarac\\Documents\\Dev\\formation\\server\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm
node-pre-gyp ERR! node -v v10.15.3
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm\compiled\node-v64_win32_x64\realm.nod
e --module_name=realm --module_path=C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm\compiled\node-v64_win32_x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm WARN formation-server@0.0.2 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! realm@2.15.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the realm@2.15.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sarac\AppData\Roaming\npm-cache\_logs\2019-04-09T21_35_42_855Z-debug.log
```

## Steps to Reproduce

Take clean windows and run `npm install -g --production windows-build-tools`, then either with `npm set` or add with editor in your `.npmrc` reference to python `python="C:\\Users\\%YOURUSER%\\.windows-build-tools\\python27\\python.exe"`

## Version of Realm and Tooling

- Realm JS SDK Version:  n/a
- Node or React Native: node
- Client OS & Version: Windows 10
- Which debugger for React Native: None

## Additional Question

On [npm page](https://www.npmjs.com/package/realm) it says 
> Building Realm
> In case you don't want to use the precompiled version on npm, you can build Realm yourself from source. You’ll need an Internet connection the first time you build in order to download the core library.

Which precompiled version? Is there option to just include some other dependency which works out of the box regardless of OS? It's a pain to do different things on different operating systems to have things running and this is now the only thing blocking our dev efforts to be cross OS compatible.

**Comment by msaracevic** [comment]
Forgot to mention, normal `npm install` where we have realm as dependency also fails with same error, I just tried the `npm install --build-from-source=realm` for last ditch

**Comment by fealebenpae** [comment]
2.15.3 is from before we started distributing pre-built binaries for Node.js 10. I suggest using the latest version.

From the build errors it seems like you don't have the Desktop C++ workload installed in Visual Studio (or Build Tools), hence `msbuild` complaining it cannot find the `Microsoft.Cpp` project import. It's also possible that `node-gyp` isn't detecting the C++ compiler installation correctly.

In any case, it's best to use the pre-built binaries instead of building from source. Just make sure to use a more recent version that comes with binaries for your Node.js version.

**Comment by msaracevic** [comment]
cheers for answer

I did thinker with it, after adding `msvs_version=2017` to `.npmrc` I was getting

```
sarac@Aero15-X9: ~/Documents/Dev/formation/server (master*) $ npm install
> realm@2.15.3 install C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm
> node-pre-gyp install --fallback-to-build
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://static.realm.io/node-pre-gyp/2.15.3/realm-v2.15.3-node-v64-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for realm@2.15.3 and node@10.15.3 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
Warning: Missing input files:
C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm\build\..\scripts\publish.sh
C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm\build\..\scripts\set-version.sh
C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm\build\..\scripts\test.sh
C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm\build\..\scripts\changelog-header.sh
C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm\build\..\src\object-store\src\descriptor_ordering.hpp
C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm\build\..\lib\browser\util.jsscripts\build-node-pre-gyp.ps1
C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm\build\..\src\object-store\src\util\compiler.hpp
C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm\build\..\src\object-store\src\util\time.hpp
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  download-realm
  Resolved requirements: { CORE_SERVER_FOLDER: 'core/v5.7.2/windows/x64/nouwp/Release',
    CORE_ARCHIVE: 'realm-core-Release-v5.7.2-Windows-x64-devel.tar.gz' }
  No lockfile found at the target, proceeding.
  Download url: https://static.realm.io/downloads/core/v5.7.2/windows/x64/nouwp/Release/realm-core-Release-v5.7.2-Windows-x64-devel.tar.gz
  Downloading realm-core-Release-v5.7.2-Windows-x64-devel.tar.gz
  Extracting realm-core-Release-v5.7.2-Windows-x64-devel.tar.gz => C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm\vendor\realm-win-x64
  Success
  binding_callback_thread_observer.cpp
  collection_notifications.cpp
  index_set.cpp
  list.cpp
  object.cpp
  placeholder.cpp
  object_schema.cpp
  object_store.cpp
  results.cpp
  schema.cpp
  shared_realm.cpp
  thread_safe_reference.cpp
  collection_change_builder.cpp
  collection_notifier.cpp
  list_notifier.cpp
  object_notifier.cpp
  primitive_list_notifier.cpp
  realm_coordinator.cpp
  results_notifier.cpp
  transact_log_handler.cpp
  weak_realm_notifier.cpp
  uuid.cpp
  external_commit_helper.cpp
  win_delay_load_hook.cc
  object-store.vcxproj -> C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm\build\Release\\object-store.lib
  js_realm.cpp
  node_init.cpp
  platform.cpp
  win_delay_load_hook.cc
c:\users\sarac\documents\dev\formation\server\node_modules\realm\src\node\node_class.hpp(224): error C2664: 'v8::Maybe<bool> v8::Object::SetAccessor(v8::Local<v8::Context>,v8::Local<v8::Name>,v8::AccessorNameGetterCallback,v8::AccessorNameSetterCallback,v8::MaybeLoca
l<v8::Value>,v8::AccessControl,v8::PropertyAttribute,v8::SideEffectType)': cannot convert argument 2 from 'const realm::node::Types::PropertyGetterCallback' to 'v8::Local<v8::Name>' (compiling source file ..\src\node\node_init.cpp) [C:\Users\sarac\Documents\Dev\forma
tion\server\node_modules\realm\build\realm.vcxproj]
  c:\users\sarac\documents\dev\formation\server\node_modules\realm\src\node\node_class.hpp(224): note: No constructor could take the source type, or constructor overload resolution was ambiguous (compiling source file ..\src\node\node_init.cpp)
  c:\users\sarac\documents\dev\formation\server\node_modules\realm\src\node\node_class.hpp(139): note: see reference to function template instantiation 'void realm::node::ObjectWrap<ClassType>::setup_property<v8::Object>(v8::Local<v8::Object>,const std::string &,cons
  t realm::node::PropertyType &)' being compiled
          with
          [
              ClassType=realm::js::RealmClass<realm::node::Types>
          ] (compiling source file ..\src\node\node_init.cpp)
  c:\users\sarac\documents\dev\formation\server\node_modules\realm\src\node\node_class.hpp(139): note: see reference to function template instantiation 'void realm::node::ObjectWrap<ClassType>::setup_property<v8::Object>(v8::Local<v8::Object>,const std::string &,cons
  t realm::node::PropertyType &)' being compiled
          with
          [
              ClassType=realm::js::RealmClass<realm::node::Types>
          ] (compiling source file ..\src\node\node_init.cpp)
  c:\users\sarac\documents\dev\formation\server\node_modules\realm\src\node\node_class.hpp(132): note: while compiling class template member function 'v8::Local<v8::Function> realm::node::ObjectWrap<ClassType>::create_constructor(v8::Isolate *)'
          with
          [
              ClassType=realm::js::RealmClass<realm::node::Types>
          ] (compiling source file ..\src\node\node_init.cpp)
  c:\users\sarac\documents\dev\formation\server\node_modules\realm\src\js_realm.hpp(383): note: see reference to function template instantiation 'v8::Local<v8::Function> realm::node::ObjectWrap<ClassType>::create_constructor(v8::Isolate *)' being compiled
          with
          [
              ClassType=realm::js::RealmClass<realm::node::Types>
          ] (compiling source file ..\src\node\node_init.cpp)
  c:\users\sarac\documents\dev\formation\server\node_modules\realm\src\node\node_class.hpp(297): note: see reference to class template instantiation 'realm::node::ObjectWrap<ClassType>' being compiled
          with
          [
              ClassType=realm::js::RealmClass<realm::node::Types>
          ] (compiling source file ..\src\node\node_init.cpp)
  c:\users\sarac\documents\dev\formation\server\node_modules\realm\src\js_realm.hpp(383): note: see reference to class template instantiation 'realm::js::ObjectWrap<T,realm::js::RealmClass<T>>' being compiled
          with
          [
              T=realm::node::Types
          ] (compiling source file ..\src\node\node_init.cpp)
  c:\users\sarac\documents\dev\formation\server\node_modules\realm\src\js_realm.hpp(382): note: while compiling class template member function 'v8::Local<v8::Function> realm::js::RealmClass<realm::node::Types>::create_constructor(v8::Isolate *)' (compiling source fil
  e ..\src\node\node_init.cpp)
  c:\users\sarac\documents\dev\formation\server\node_modules\realm\src\node\node_init.cpp(27): note: see reference to function template instantiation 'v8::Local<v8::Function> realm::js::RealmClass<realm::node::Types>::create_constructor(v8::Isolate *)' being compiled
  c:\users\sarac\documents\dev\formation\server\node_modules\realm\src\node\node_init.cpp(27): note: see reference to class template instantiation 'realm::js::RealmClass<realm::node::Types>' being compiled
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\sarac\\Documents\\Dev\\formation\\server\\node_modules\\realm\\compiled\\
node-v64_win32_x64\\realm.node" "--module_name=realm" "--module_path=C:\\Users\\sarac\\Documents\\Dev\\formation\\server\\node_modules\\realm\\compiled\\node-v64_win32_x64" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm\compil
ed\node-v64_win32_x64\realm.node --module_name=realm --module_path=C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm\compiled\node-v64_win32_x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\sarac\Documents\Dev\formation\server\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\sarac\\Documents\\Dev\\formation\\server\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm
node-pre-gyp ERR! node -v v10.15.3
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm\compiled\node-v64_win32_x64\realm.nod
e --module_name=realm --module_path=C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm\compiled\node-v64_win32_x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm WARN formation-server@0.0.2 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! realm@2.15.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the realm@2.15.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sarac\AppData\Roaming\npm-cache\_logs\2019-04-09T22_05_05_991Z-debug.log
```

So it got further, but still not building

I will bump up the version in few hours when I get a hold of Windows machine and see if it works then out of the box

**Comment by wojryba** [comment]
I just had the same issue. I used nvm to switch to node 8.11.1 and it installed correctly.

**Comment by msaracevic** [comment]
I updated the npm dependency version to `"realm": "^2.26.0"` and it indeed does install without failing since it is not being built.

```
sarac@Aero15-X9: ~/Documents/Dev/formation/server (master*) $ npm install realm --save

> realm@2.26.0 install C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
[realm] Success: "C:\Users\sarac\Documents\Dev\formation\server\node_modules\realm\compiled\node-v64_win32_x64\realm.node" is installed via remote
npm WARN formation-server@0.0.2 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ realm@2.26.0
added 97 packages from 61 contributors, removed 1 package, updated 12 packages and audited 1819 packages in 9.628s
found 68 vulnerabilities (1 low, 67 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
``` 

Closing the issue, thank you for support
