### ISSUE TITLE
crashing on Android (startup app)

### ISSUE THREAD

**Issue by webforuse** [realm/realm-js#2599]
Hello. When startup application on android, application is crashing.

Error:
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: librealmreact.so caused by: Error: Cannot load /data/app/com.application-P_sNEwRiXgleu1ZRKQS9EA==/lib/arm/librealmreact.so
	at com.facebook.soloader.SoLoader.b(Unknown Source:383)
	at com.facebook.soloader.SoLoader.a(Unknown Source:106)
	at com.facebook.soloader.SoLoader.a(Unknown Source:96)
	at com.facebook.soloader.SoLoader.a(Unknown Source:1)
	at io.realm.react.RealmReactModule.<clinit>(Unknown Source:2)
	at io.realm.react.a.a(Unknown Source:0)
	at com.facebook.react.q.a(Unknown Source:41)
	at com.facebook.react.e.a(Unknown Source:30)
	at com.facebook.react.l.a(Unknown Source:35)
	at com.facebook.react.l.a(Unknown Source:54)
	at com.facebook.react.l.a(Unknown Source:36)
	at com.facebook.react.l.a(Unknown Source:0)
	at com.facebook.react.l$5.run(Unknown Source:68)
	at java.lang.Thread.run(Thread.java:764)

Realm 3.3.0
RN: 60.4
Android 8 or 9

**Comment by kneth** [comment]
Did you disable Hermes in your app? Realm does not yet support Hermes (see #2455), so you need to disable it.
