### ISSUE TITLE
[N-API] Stack trace is different

### ISSUE THREAD

**Issue by kneth** [realm/realm-js#2710]
If an exception happens in a write transaction, there is a different between our Nan and N-API implementations.

Consider the following code:

```
const Realm = require('realm');

const bobject = {
    name: 'BObject',
    properties: {
        id: 'int',
        data: 'int',
    }
};

let realm = new Realm({schema: [bobject]});

function broken() { throw new Error('Test realm.'); }

realm.write(() => {
    realm.create('BObject', { id: 1, data: 100 });
    broken();
});
realm.close();
```

With Realm JavaScript v3.6.3 the stack trace is:

```
Error: Test realm.
    at broken (/Users/kneth/tmp/bmark/broken.js:13:27)
    at Realm.realm.write (/Users/kneth/tmp/bmark/broken.js:17:5)
    at Object.<anonymous> (/Users/kneth/tmp/bmark/broken.js:15:7)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
```

And for v3.7.0-alpha.2 the stack trace is:

```
Error: Test realm.
    at Object.<anonymous> (/Users/kneth/tmp/bmark/broken.js:15:7)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

The first line in the stack trace is different. For Nan implementation it is possible to see where the exception is thrown while the N-API implementation doesn't provide this information.

**Comment by blagoev** [comment]
This is already fixed with this commit.
https://github.com/realm/realm-js/commit/c6830e7b3b1e49fba628aa580d3b8ceb9a3339b1

closing this issue.
