### ISSUE TITLE
node-gyp error with Node v13

### ISSUE THREAD

**Issue by Jarred-Sumner** [realm/realm-js#2716]
## Goals

I'm trying to install `realm` in my react native app.

## Expected Results

`yarn add realm` should succeed

## Actual Results

```
error /Users/jarred/Code/yeet/yeet/node_modules/realm: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: /Users/jarred/Code/yeet/yeet/node_modules/realm
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.13.0
node-pre-gyp info using node@13.8.0 | darwin | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "/Users/jarred/Code/yeet/yeet/node_modules/realm/compiled/node-v79_darwin_x64/realm.node" (not found)
node-pre-gyp http GET https://static.realm.io/node-pre-gyp/3.6.3/realm-v3.6.3-node-v79-darwin-x64.tar.gz
node-pre-gyp http 404 https://static.realm.io/node-pre-gyp/3.6.3/realm-v3.6.3-node-v79-darwin-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://static.realm.io/node-pre-gyp/3.6.3/realm-v3.6.3-node-v79-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for realm@3.6.3 and node@13.8.0 (node-v79 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://static.realm.io/node-pre-gyp/3.6.3/realm-v3.6.3-node-v79-darwin-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@13.8.0 | darwin | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@13.8.0 | darwin | x64
gyp info find Python using Python version 3.7.5 found at "/Users/jarred/.pyenv/versions/3.7.5/bin/python"
gyp info spawn /Users/jarred/.pyenv/versions/3.7.5/bin/python
gyp info spawn args [
gyp info spawn args   '/Users/jarred/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jarred/Code/yeet/yeet/node_modules/realm/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jarred/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jarred/Library/Caches/node-gyp/13.8.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/jarred/Library/Caches/node-gyp/13.8.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/jarred/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/jarred/Library/Caches/node-gyp/13.8.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/jarred/Code/yeet/yeet/node_modules/realm',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Traceback (most recent call last):
  File "/Users/jarred/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
  File "/Users/jarred/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
  File "/Users/jarred/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
  File "/Users/jarred/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 532, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/Users/jarred/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2215, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File "/Users/jarred/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 794, in Write
    extra_mac_bundle_resources, part_of_all)
  File "/Users/jarred/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 900, in WriteActions
    env = self.GetSortedXcodeEnv()
  File "/Users/jarred/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1885, in GetSortedXcodeEnv
    additional_settings)
  File "/Users/jarred/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1616, in GetSortedXcodeEnv
    additional_settings)
  File "/Users/jarred/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1527, in _GetXcodeEnv
    if XcodeVersion() >= '0500' and not env.get('SDKROOT'):
TypeError: '>=' not supported between instances of 'tuple' and 'str'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/jarred/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.3.0
gyp ERR! command "/Users/jarred/.nvm/versions/node/v13.8.0/bin/node" "/Users/jarred/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/jarred/Code/yeet/yeet/node_modules/realm/compiled/node-v79_darwin_x64/realm.node" "--module_name=realm" "--module_path=/Users/jarred/Code/yeet/yeet/node_modules/realm/compiled/node-v79_darwin_x64" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v79"
gyp ERR! cwd /Users/jarred/Code/yeet/yeet/node_modules/realm
gyp ERR! node -v v13.8.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/jarred/.nvm/versions/node/v13.8.0/bin/node /Users/jarred/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/jarred/Code/yeet/yeet/node_modules/realm/compiled/node-v79_darwin_x64/realm.node --module_name=realm --module_path=/Users/jarred/Code/yeet/yeet/node_modules/realm/compiled/node-v79_darwin_x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/jarred/Code/yeet/yeet/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1026:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Darwin 19.3.0
node-pre-gyp ERR! command "/Users/jarred/.nvm/versions/node/v13.8.0/bin/node" "/Users/jarred/Code/yeet/yeet/node_modules/realm/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/jarred/Code/yeet/yeet/node_modules/realm
node-pre-gyp ERR! node -v v13.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
Failed to execute '/Users/jarred/.nvm/versions/node/v13.8.0/bin/node /Users/jarred/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/jarred/Code/yeet/yeet/node_modules/realm/compiled/node-v79_darwin_x64/realm.node --module_name=realm --module_path=/Users/jarred/Code/yeet/yeet/node_modules/realm/compiled/node-v79_darwin_x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

## Steps to Reproduce

1. Use node v13
2. Run `yarn add realm`

## Code Sample

`yarn add realm`

**Comment by glucianog** [comment]
Realm doesn't support node v13 yet. 

You need to use Node version 8.3.0 (and later versions in 8.x) or 10.x in order to use Realm.
Check: [Realm documentation](https://realm.io/docs/javascript/latest/)

**Comment by blagoev** [comment]
If you can you can try the alpha version that has support for node > 10
