### ISSUE TITLE
Failing to install (node-pre-gyp) with node version 8.14

### ISSUE THREAD

**Issue by buchereli** [realm/realm-js#2719]
##  Goals

Install realm

## Expected Results

realm installs successfully, as it has been in the past. 

## Actual Results

No changes to package-json just randomly started failing.

```
> realm@3.6.3 install /Users/elijahbucher/easy-expense/EasyExpense/node_modules/realm
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for realm@3.6.3 and node@8.14.0 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error connect ETIMEDOUT 52.216.128.130:443
  TOUCH Release/obj.target/OpenSSL.stamp
  ACTION binding_gyp_vendored_realm_target_download_realm /Users/elijahbucher/easy-expense/EasyExpense/node_modules/realm/vendor/realm-mac-x64
Resolved requirements: { SYNC_SERVER_FOLDER: 'sync',
  SYNC_ARCHIVE: 'realm-sync-node-cocoa-4.9.4.tar.gz',
  SYNC_ARCHIVE_ROOT: 'realm-sync-node-cocoa-4.9.4' }
Resolved options: { platform: 'mac', sync: true, arch: 'x64' }
No lockfile found at the target, proceeding.
Download url: https://static.realm.io/downloads/sync/realm-sync-node-cocoa-4.9.4.tar.gz
{ FetchError: request to https://static.realm.io/downloads/sync/realm-sync-node-cocoa-4.9.4.tar.gz failed, reason: connect ETIMEDOUT 52.216.205.138:443
    at ClientRequest.<anonymous> (/Users/elijahbucher/easy-expense/EasyExpense/node_modules/realm/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  name: 'FetchError',
  message: 'request to https://static.realm.io/downloads/sync/realm-sync-node-cocoa-4.9.4.tar.gz failed, reason: connect ETIMEDOUT 52.216.205.138:443',
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT' }
make: *** [/Users/elijahbucher/easy-expense/EasyExpense/node_modules/realm/vendor/realm-mac-x64] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node@8/8.14.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node@8/8.14.0/bin/node" "/usr/local/Cellar/node@8/8.14.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/elijahbucher/easy-expense/EasyExpense/node_modules/realm/compiled/node-v57_darwin_x64/realm.node" "--module_name=realm" "--module_path=/Users/elijahbucher/easy-expense/EasyExpense/node_modules/realm/compiled/node-v57_darwin_x64" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v57"
gyp ERR! cwd /Users/elijahbucher/easy-expense/EasyExpense/node_modules/realm
gyp ERR! node -v v8.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node@8/8.14.0/bin/node /usr/local/Cellar/node@8/8.14.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/elijahbucher/easy-expense/EasyExpense/node_modules/realm/compiled/node-v57_darwin_x64/realm.node --module_name=realm --module_path=/Users/elijahbucher/easy-expense/EasyExpense/node_modules/realm/compiled/node-v57_darwin_x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/elijahbucher/easy-expense/EasyExpense/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Darwin 18.7.0
node-pre-gyp ERR! command "/usr/local/Cellar/node@8/8.14.0/bin/node" "/Users/elijahbucher/easy-expense/EasyExpense/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/elijahbucher/easy-expense/EasyExpense/node_modules/realm
node-pre-gyp ERR! node -v v8.14.0
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node@8/8.14.0/bin/node /usr/local/Cellar/node@8/8.14.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/elijahbucher/easy-expense/EasyExpense/node_modules/realm/compiled/node-v57_darwin_x64/realm.node --module_name=realm --module_path=/Users/elijahbucher/easy-expense/EasyExpense/node_modules/realm/compiled/node-v57_darwin_x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
npm WARN eslint-plugin-react@7.12.4 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react-native@3.6.0 requires a peer of eslint@^3.17.0 || ^4 || ^5 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/eslint-plugin@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/parser@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@17.1.1 requires a peer of eslint@^4.19.1 || ^5.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb-base@13.2.0 requires a peer of eslint@^4.19.1 || ^5.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-fs@2.16.2 requires a peer of react-native@^0.59.5 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-fs@2.16.2 requires a peer of react-native-windows@^0.57.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-spring-scrollview@2.0.22 requires a peer of react-native@^0.50.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-spring-scrollview@2.0.22 requires a peer of lottie-react-native@latest but none is installed. You must install peer dependencies yourself.
npm WARN react-navigation-stack@1.10.3 requires a peer of react-native-screens@^1.0.0 || ^1.0.0-alpha but none is installed. You must install peer dependencies yourself.
npm WARN react-navigation-tabs@2.7.0 requires a peer of react-native-screens@^1.0.0 || ^1.0.0-alpha but none is installed. You must install peer dependencies yourself.
npm WARN styled-components@4.4.1 requires a peer of react-dom@>= 16.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! realm@3.6.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the realm@3.6.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/elijahbucher/.npm/_logs/2020-02-10T22_08_03_172Z-debug.log
```

## Steps to Reproduce

npm install realm --save

## Version of Realm and Tooling
"realm": "^3.6.3"

node --version
v8.14.0

**Comment by ericschaal** [comment]
Same 😢

**Comment by roconnorr** [comment]
Seems like something is wrong with their SSL cert on https://realm.io/ http is working for me

**Comment by ioveracker** [comment]
This appears to be resolved now.

**Comment by jherencia** [comment]
Failing again

**Comment by ioveracker** [comment]
Now it appears to be explicitly SSL related:
```
{ FetchError: request to https://static.realm.io/downloads/sync/realm-sync-node-cocoa-4.9.4.tar.gz failed, reason: write EPROTO 4546723264:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1407:SSL alert number 40
```

**Comment by ioveracker** [comment]
And it's back! 😂

**Comment by kneth** [comment]
Yeah, we had a little DNS issue - sorry about that.

**Comment by brunocrpontes** [comment]
I'm currently facing this issue 🧐

**Comment by kneth** [comment]
@brunocrpontes We don't support node 12 yet.

**Comment by blagoev** [comment]
@brunocrpontes If you need to use node 12 I suggest trying out our alpha version for it. https://github.com/realm/realm-js/releases/tag/v3.7.0-alpha.2

As @kneth said we don't have a stable release for node 12 yet. so treat this as exactly what it is an alpha version.

**Comment by brunocrpontes** [comment]
Understood @blagoev @kneth. Thanks for reply. I will try workaround it with nvm if it's doesn't fit I change to alpha version
