### ISSUE TITLE
`node-pre-gyp install --fallback-to-build` failing with timeout

### ISSUE THREAD

**Issue by ioveracker** [realm/realm-js#2720]
## Goals

Install `realm`.

## Expected Results

Expected `realm` to be installed.

## Actual Results

It fails to download `https://static.realm.io/downloads/sync/realm-sync-node-cocoa-4.9.4.tar.gz` with a timeout error. This could be related to S3 but the [AWS dashboard](https://status.aws.amazon.com) shows everything green at the moment. 

This started around 21:30 UTC today (Feb 10, 2020) from three disparate geographic locations so seems unrelated to network / firewall configuration.

Note that we've been using Realm for years--this isn't a new install.

```
error /Users/ioveracker/Source/tmp/client-apps-learner/node_modules/realm: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /Users/ioveracker/Source/tmp/client-apps-learner/node_modules/realm
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.13.0
node-pre-gyp info using node@10.15.3 | darwin | x64
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info check checked for "/Users/ioveracker/Source/tmp/client-apps-learner/node_modules/realm/compiled/node-v64_darwin_x64/realm.node" (not found)
node-pre-gyp http GET https://static.realm.io/node-pre-gyp/3.6.3/realm-v3.6.3-node-v64-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for realm@3.6.3 and node@10.15.3 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error connect ETIMEDOUT 52.217.41.67:443 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.3 | darwin | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.3 | darwin | x64
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/Users/ioveracker/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ioveracker/Source/tmp/client-apps-learner/node_modules/realm/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ioveracker/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ioveracker/.node-gyp/10.15.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/ioveracker/.node-gyp/10.15.3',
gyp info spawn args   '-Dnode_gyp_dir=/Users/ioveracker/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/ioveracker/.node-gyp/10.15.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/ioveracker/Source/tmp/client-apps-learner/node_modules/realm',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.3 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  TOUCH Release/obj.target/OpenSSL.stamp
  ACTION binding_gyp_vendored_realm_target_download_realm /Users/ioveracker/Source/tmp/client-apps-learner/node_modules/realm/vendor/realm-mac-x64
Resolved requirements: { SYNC_SERVER_FOLDER: 'sync',
  SYNC_ARCHIVE: 'realm-sync-node-cocoa-4.9.4.tar.gz',
  SYNC_ARCHIVE_ROOT: 'realm-sync-node-cocoa-4.9.4' }
Resolved options: { platform: 'mac', sync: true, arch: 'x64' }
No lockfile found at the target, proceeding.
Download url: https://static.realm.io/downloads/sync/realm-sync-node-cocoa-4.9.4.tar.gz
{ FetchError: request to https://static.realm.io/downloads/sync/realm-sync-node-cocoa-4.9.4.tar.gz failed, reason: connect ETIMEDOUT 52.217.39.155:443
    at ClientRequest.<anonymous> (/Users/ioveracker/Source/tmp/client-apps-learner/node_modules/realm/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:189:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'FetchError',
  message:
   'request to https://static.realm.io/downloads/sync/realm-sync-node-cocoa-4.9.4.tar.gz failed, reason: connect ETIMEDOUT 52.217.39.155:443',
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT' }
make: *** [/Users/ioveracker/Source/tmp/client-apps-learner/node_modules/realm/vendor/realm-mac-x64] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/ioveracker/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.3.0
gyp ERR! command "/Users/ioveracker/.nvm/versions/node/v10.15.3/bin/node" "/Users/ioveracker/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/ioveracker/Source/tmp/client-apps-learner/node_modules/realm/compiled/node-v64_darwin_x64/realm.node" "--module_name=realm" "--module_path=/Users/ioveracker/Source/tmp/client-apps-learner/node_modules/realm/compiled/node-v64_darwin_x64" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /Users/ioveracker/Source/tmp/client-apps-learner/node_modules/realm
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/ioveracker/.nvm/versions/node/v10.15.3/bin/node /Users/ioveracker/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/ioveracker/Source/tmp/client-apps-learner/node_modules/realm/compiled/node-v64_darwin_x64/realm.node --module_name=realm --module_path=/Users/ioveracker/Source/tmp/client-apps-learner/node_modules/realm/compiled/node-v64_darwin_x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/ioveracker/Source/tmp/client-apps-learner/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Darwin 19.3.0
node-pre-gyp ERR! command "/Users/ioveracker/.nvm/versions/node/v10.15.3/bin/node" "/Users/ioveracker/Source/tmp/client-apps-learner/node_modules/realm/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/ioveracker/Source/tmp/client-apps-learner/node_modules/realm
node-pre-gyp ERR! node -v v10.15.3
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok 
Failed to execute '/Users/ioveracker/.nvm/versions/node/v10.15.3/bin/node /Users/ioveracker/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/ioveracker/Source/tmp/client-apps-learner/node_modules/realm/compiled/node-v64_darwin_x64/realm.node --module_name=realm --module_path=/Users/ioveracker/Source/tmp/client-apps-lea
```

## Steps to Reproduce

Run `yarn install` | `npm install` in a project utilizing the `realm` package.

## Version of Realm and Tooling

- Realm JS SDK Version: 3.6.3
- Node or React Native: Node 10.15.3 / React Native 0.61.5
- Client OS & Version: macOS 10.15.3
- Which debugger for React Native: N/A

**Comment by feiyingx** [comment]
Having the same issue, it like their cdn may be down

**Comment by ioveracker** [comment]
Closing as a duplicate of #2719
