### ISSUE TITLE
Realm PhaseScriptExecution failed

### ISSUE THREAD

**Issue by sushilmishraios** [realm/realm-js#2726]
Using Node.js v10.15.0
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/../..
'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
Command PhaseScriptExecution failed with a nonzero exit code

<img width="477" alt="Screenshot 2020-02-14 at 4 43 46 PM" src="https://user-images.githubusercontent.com/5715607/74526515-8b824a00-4f49-11ea-89d0-40b4e1e52eb4.png">

**Comment by kneth** [comment]
Please take a look at https://github.com/realm/realm-js/issues/1738#issuecomment-405642827

**Comment by faizantariq1** [comment]
@sushilmishraios did you resolve this issue???...
i'm have the same issue on ios side in react native...

**Note**: It's running on android side but giving error on ios side. when adding realm library.

Using Node.js v12.16.2
internal/modules/cjs/loader.js:983
throw err;
^

Error: Cannot find module '/Users/faraztariq/Desktop/Naseeb'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
at Function.Module._load (internal/modules/cjs/loader.js:862:27)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
at internal/main/run_main_module.js:18:47 {
code: 'MODULE_NOT_FOUND',
requireStack: []
}
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by sushilmishraios** [comment]
Yes @faizantariq1,
I have a space source repo folder in my system. I just remove that space and cache clean for node_modules. It's work for me.

**Comment by faizantariq1** [comment]
@sushilmishraios thank you. done the same on that day...:D

**Comment by saps1063** [comment]
Can't integrate realm in an iOS project.

        PhaseScriptExecution [CP-User]\ Download\ Realm\ Core\ &\ Sync /Users/parth.shah/Library/Developer/Xcode/DerivedData/RealmDemoInReactNative-fpkzpswfqkufyuggomxydufwvsav/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RealmJS.build/Script-9CA25826422EB66EE5E41D2C97331D2E.sh

/bin/sh -c /Users/parth.shah/Library/Developer/Xcode/DerivedData/RealmDemoInReactNative-fpkzpswfqkufyuggomxydufwvsav/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RealmJS.build/Script-9CA25826422EB66EE5E41D2C97331D2E.sh
Using Node.js v10.16.0
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/Users/parth.shah/Parth'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Command PhaseScriptExecution failed with a nonzero exit code


XCode Version : 11.2.1
iOS Simulator : iPhone 11 - iOS 13.2.2
node -version : v10.16.0
/usr/local/bin/node --version : v10.16.0

Package.json ->
"dependencies": {
    "react": "16.11.0",
    "react-native": "0.62.2",
    "realm": "^6.0.1"
  }

**Comment by sushilmishraios** [comment]
@saps1063 just remove space from project folder name.
