### ISSUE TITLE
iOS PhaseScriptExecution Fails on Archive

### ISSUE THREAD

**Issue by napsta32** [realm/realm-js#2992]
## Goals

I was trying to create an ipa with Jenkins XCode integration plugin.

## Expected Results

In PhaseScriptExecution, `download-realm.js` script is executed.

## Actual Results

In PhaseScriptExecution, My React Native `index.js` file tries to be executed.

```
...IntermediateBuildFilesPath/Pods.build/Release-iphoneos/RealmJS.build/Script-9CA25826422EB66EE5E41D2C97331D2E.sh
Using Node.js v14.4.0
(node:44310) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/my.user/.jenkins/workspace/ProjectName/index.js:5
import {AppRegistry, Platform} from 'react-native';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1116:16)
    at Module._compile (internal/modules/cjs/loader.js:1164:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
Command PhaseScriptExecution failed with a nonzero exit code
```

## Steps to Reproduce

Build iOS project using Jenkins XCode integration. Tried cleaning entire workspace.

## Code Sample

React Native base code.

## Version of Realm and Tooling

- Realm JS SDK Version: 6.0.2
- Node or React Native: 12.8.1 AND 14.4.0 (tried both)
- Client OS & Version: macOS 10.15.4 
- Which debugger for React Native: None
- Jenkins version: 2.235.1

**Comment by napsta32** [comment]
Looks something related to running the project and building in jenkins at the same time.

**Comment by napsta32** [comment]
Real issue is related to unsupported spaces in directory path.
