### ISSUE TITLE
Unable to build module with electron

### ISSUE THREAD

**Issue by prefixaut** [realm/realm-js#3092]
## Expected Results

To be able to install it alongside electron.

As a short preface, I had also issues installing the project which uses realm on windows.
The windows issue is probably #3009, but I wanted to get to work.
To be finally able to work on it, I installed Manjaro **FRESHLY** and installed node via *nvm*, as well as *yarn* to get to it.

A buddy who started the project, has the same setup (Manjaro, also recently setup), and it works there without any errors.
We were already troubleshooting everything we knew, but we're out of ideas at this point.

## Actual Results

During installation, the building of the module fails.

```sh
$ yarn add realm
yarn add v1.22.4
[1/4] Resolving packages...
warning realm > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning realm > deprecated-react-native-listview > fbjs > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning realm > deprecated-react-native-listview > create-react-class > fbjs > core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "realm > deprecated-react-native-listview@0.0.6" has unmet peer dependency "react@*".
warning "realm > deprecated-react-native-listview@0.0.6" has unmet peer dependency "react-native@*".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 27 new dependencies.
info Direct dependencies
└─ realm@6.0.3
info All dependencies
├─ agent-base@4.3.0
├─ array-back@1.0.4
├─ asap@2.0.6
├─ command-line-args@4.0.7
├─ create-react-class@15.6.3
├─ deepmerge@2.1.0
├─ deprecated-react-native-listview@0.0.6
├─ encoding@0.1.13
├─ es6-promise@4.2.8
├─ es6-promisify@5.0.0
├─ fbjs-css-vars@1.0.2
├─ fbjs@1.0.0
├─ find-replace@1.0.3
├─ http-basic@2.5.1
├─ http-response-object@1.1.0
├─ https-proxy-agent@2.2.4
├─ node-fetch@1.7.3
├─ node-machine-id@1.1.12
├─ prop-types@15.7.2
├─ react-clone-referenced-element@1.1.0
├─ react-is@16.13.1
├─ realm@6.0.3
├─ stream-counter@1.0.0
├─ sync-request@3.0.1
├─ test-value@2.1.0
├─ then-request@2.2.0
└─ whatwg-fetch@3.2.0
$ electron-builder install-app-deps
  • electron-builder  version=22.8.0
  • rebuilding native dependencies  dependencies=realm@6.0.3, sqlite3@5.0.0 platform=linux arch=x64
  • rebuilding native dependency  name=sqlite3 version=5.0.0
  • rebuilding native dependency  name=realm version=6.0.3
  ⨯ cannot execute  cause=exit status 1
                    out=yarn run v1.22.4
    $ node-pre-gyp install --fallback-to-build -j 8
    Failed to execute '/home/dominik/.nvm/versions/node/v12.18.3/bin/node /run/media/dominik/Data/workspace/test/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --jobs=8 --module=/run/media/dominik/Data/workspace/test/node_modules/realm/compiled/electron-v9.1_linux_x64/realm.node --module_name=realm --module_path=/run/media/dominik/Data/workspace/test/node_modules/realm/compiled/electron-v9.1_linux_x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v9.1' (1)
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    
                    errorOut=warning package.json: License should be a valid SPDX license expression
    /bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_AT.UTF-8)
    /bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_AT.UTF-8)
    node-pre-gyp info it worked if it ends with ok
    node-pre-gyp info using node-pre-gyp@0.15.0
    node-pre-gyp info using node@12.18.3 | linux | x64
    node-pre-gyp WARN Using request for node-pre-gyp https download 
    node-pre-gyp http GET https://static.realm.io/node-pre-gyp/6.0.3/realm-v6.0.3-electron-v9.1-linux-x64.tar.gz
    node-pre-gyp http 404 https://static.realm.io/node-pre-gyp/6.0.3/realm-v6.0.3-electron-v9.1-linux-x64.tar.gz
    node-pre-gyp WARN Tried to download(404): https://static.realm.io/node-pre-gyp/6.0.3/realm-v6.0.3-electron-v9.1-linux-x64.tar.gz 
    node-pre-gyp WARN Pre-built binaries not found for realm@6.0.3 and electron@9.1.1 (electron-v9.1 ABI, glibc) (falling back to source compile with node-gyp) 
    node-pre-gyp http 404 status code downloading tarball https://static.realm.io/node-pre-gyp/6.0.3/realm-v6.0.3-electron-v9.1-linux-x64.tar.gz 
    gyp info it worked if it ends with ok
    gyp info using node-gyp@3.8.0
    gyp info using node@12.18.3 | linux | x64
    gyp info ok 
    gyp info it worked if it ends with ok
    gyp info using node-gyp@3.8.0
    gyp info using node@12.18.3 | linux | x64
    gyp ERR! configure error 
    gyp ERR! stack Error: Command failed: /usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
    gyp ERR! stack   File "<string>", line 1
    gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
    gyp ERR! stack                       ^
    gyp ERR! stack SyntaxError: invalid syntax
    gyp ERR! stack 
    gyp ERR! stack     at ChildProcess.exithandler (child_process.js:303:12)
    gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
    gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
    gyp ERR! System Linux 5.6.19-2-MANJARO
    gyp ERR! command "/home/dominik/.nvm/versions/node/v12.18.3/bin/node" "/run/media/dominik/Data/workspace/test/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--jobs=8" "--module=/run/media/dominik/Data/workspace/test/node_modules/realm/compiled/electron-v9.1_linux_x64/realm.node" "--module_name=realm" "--module_path=/run/media/dominik/Data/workspace/test/node_modules/realm/compiled/electron-v9.1_linux_x64" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v9.1"
    gyp ERR! cwd /run/media/dominik/Data/workspace/test/node_modules/realm
    gyp ERR! node -v v12.18.3
    gyp ERR! node-gyp -v v3.8.0
    gyp ERR! not ok 
    node-pre-gyp ERR! build error 
    node-pre-gyp ERR! stack Error: Failed to execute '/home/dominik/.nvm/versions/node/v12.18.3/bin/node /run/media/dominik/Data/workspace/test/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --jobs=8 --module=/run/media/dominik/Data/workspace/test/node_modules/realm/compiled/electron-v9.1_linux_x64/realm.node --module_name=realm --module_path=/run/media/dominik/Data/workspace/test/node_modules/realm/compiled/electron-v9.1_linux_x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v9.1' (1)
    node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/run/media/dominik/Data/workspace/test/node_modules/realm/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
    node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
    node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
    node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
    node-pre-gyp ERR! System Linux 5.6.19-2-MANJARO
    node-pre-gyp ERR! command "/home/dominik/.nvm/versions/node/v12.18.3/bin/node" "/run/media/dominik/Data/workspace/test/node_modules/realm/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "-j" "8"
    node-pre-gyp ERR! cwd /run/media/dominik/Data/workspace/test/node_modules/realm
    node-pre-gyp ERR! node -v v12.18.3
    node-pre-gyp ERR! node-pre-gyp -v v0.15.0
    node-pre-gyp ERR! not ok 
    error Command failed with exit code 1.
    
                    command=/home/dominik/.nvm/versions/node/v12.18.3/bin/node /usr/lib/node_modules/yarn/bin/yarn.js run install
                    workingDir=/run/media/dominik/Data/workspace/test/node_modules/realm
error Command failed with exit code 1.
```

## Steps to Reproduce

- `npm i -g @vue/cli`
- `vue create test`
- `cd test`
- `vue add electron-builder`
- `yarn add realm`

## Version of Realm and Tooling

- Realm JS SDK Version: 6.0.3
- Node or React Native: Node v12.18.3
- Node-Gyp Version: 3.8.0
- Yarn Version: 1.22.4
- NPM Version: 6.14.6
- Electron-Version: 9.1.1
- Client OS & Version: 5.6.19-2-MANJARO #1 SMP PREEMPT Wed Jun 17 22:24:52 UTC 2020 x86_64 GNU/Linux
- Which debugger for React Native: None

**Comment by steffenagger** [comment]
```zsh
gyp ERR! stack Error: Command failed: /usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
```

Looks like you have Python 3 installed? Please install Python 2.7, and try again.

**Comment by prefixaut** [comment]
Tried it with python 2.7 (Installed it, linked the versions /usr/bin/python -> /usr/bin/python2 and /usr/bin/python-config -> /usr/bin/python2-config), but with the same results.
Did that after creating a new bash session, and `python --version` also properly reported the version `2.7`.

My buddy where it works, doesn't have python 2 installed at all either, so I highly doubt that it has something to do with the python version.

I get a different error now from the actual project:

```
yarn install v1.22.4
[1/4] Resolving packages...
success Already up-to-date.
$ electron-builder install-app-deps
  • electron-builder  version=22.7.0
  • loaded configuration  file=/run/media/dominik/Data/workspace/<projectName>/electron-builder.json
  • rebuilding native dependencies  dependencies=realm@6.0.3 platform=linux arch=x64
  • rebuilding native dependency  name=realm version=6.0.3
  ⨯ cannot execute  cause=exit status 1
                    out=yarn run v1.22.4
    $ node-pre-gyp install --fallback-to-build -j 8
    Failed to execute '/home/dominik/.nvm/versions/node/v12.18.3/bin/node /home/dominik/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --jobs=8 --module=/run/media/dominik/Data/workspace/<projectName>/node_modules/realm/compiled/electron-v9.1_linux_x64/realm.node --module_name=realm --module_path=/run/media/dominik/Data/workspace/<projectName>/node_modules/realm/compiled/electron-v9.1_linux_x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v9.1' (1)
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    
                    errorOut=warning package.json: License should be a valid SPDX license expression
    /bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_AT.UTF-8)
    /bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_AT.UTF-8)
    node-pre-gyp info it worked if it ends with ok
    node-pre-gyp info using node-pre-gyp@0.15.0
    node-pre-gyp info using node@12.18.3 | linux | x64
    node-pre-gyp WARN Using request for node-pre-gyp https download 
    node-pre-gyp http GET https://static.realm.io/node-pre-gyp/6.0.3/realm-v6.0.3-electron-v9.1-linux-x64.tar.gz
    node-pre-gyp http 404 https://static.realm.io/node-pre-gyp/6.0.3/realm-v6.0.3-electron-v9.1-linux-x64.tar.gz
    node-pre-gyp WARN Tried to download(404): https://static.realm.io/node-pre-gyp/6.0.3/realm-v6.0.3-electron-v9.1-linux-x64.tar.gz 
    node-pre-gyp WARN Pre-built binaries not found for realm@6.0.3 and electron@9.1.0 (electron-v9.1 ABI, glibc) (falling back to source compile with node-gyp) 
    node-pre-gyp http 404 status code downloading tarball https://static.realm.io/node-pre-gyp/6.0.3/realm-v6.0.3-electron-v9.1-linux-x64.tar.gz 
    gyp info it worked if it ends with ok
    gyp info using node-gyp@5.1.0
    gyp info using node@12.18.3 | linux | x64
    gyp info ok 
    gyp info it worked if it ends with ok
    gyp info using node-gyp@5.1.0
    gyp info using node@12.18.3 | linux | x64
    gyp info find Python using Python version 3.8.3 found at "/usr/bin/python"
    gyp info spawn /usr/bin/python
    gyp info spawn args [
    gyp info spawn args   '/home/dominik/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
    gyp info spawn args   'binding.gyp',
    gyp info spawn args   '-f',
    gyp info spawn args   'make',
    gyp info spawn args   '-I',
    gyp info spawn args   '/run/media/dominik/Data/workspace/<projectName>/node_modules/realm/build/config.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/home/dominik/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/home/dominik/.electron-gyp/9.1.0/include/node/common.gypi',
    gyp info spawn args   '-Dlibrary=shared_library',
    gyp info spawn args   '-Dvisibility=default',
    gyp info spawn args   '-Dnode_root_dir=/home/dominik/.electron-gyp/9.1.0',
    gyp info spawn args   '-Dnode_gyp_dir=/home/dominik/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/node-gyp',
    gyp info spawn args   '-Dnode_lib_file=/home/dominik/.electron-gyp/9.1.0/<(target_arch)/node.lib',
    gyp info spawn args   '-Dmodule_root_dir=/run/media/dominik/Data/workspace/<projectName>/node_modules/realm',
    gyp info spawn args   '-Dnode_engine=v8',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.'
    gyp info spawn args ]
    /bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_AT.UTF-8)
    /bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_AT.UTF-8)
    gyp: Call to 'node -p "'REALMJS_USE_DEBUG_CORE' in process.env ? 1 : 0"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
    gyp ERR! configure error 
    gyp ERR! stack Error: `gyp` failed with exit code: 1
    gyp ERR! stack     at onCpExit (/home/dominik/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:354:16)
    gyp ERR! stack     at ChildProcess.<anonymous> (/home/dominik/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:347:9)
    gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    gyp ERR! System Linux 5.6.19-2-MANJARO
    gyp ERR! command "/home/dominik/.nvm/versions/node/v12.18.3/bin/node" "/home/dominik/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--jobs=8" "--module=/run/media/dominik/Data/workspace/<projectName>/node_modules/realm/compiled/electron-v9.1_linux_x64/realm.node" "--module_name=realm" "--module_path=/run/media/dominik/Data/workspace/<projectName>/node_modules/realm/compiled/electron-v9.1_linux_x64" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v9.1"
    gyp ERR! cwd /run/media/dominik/Data/workspace/<projectName>/node_modules/realm
    gyp ERR! node -v v12.18.3
    gyp ERR! node-gyp -v v5.1.0
    gyp ERR! not ok 
    node-pre-gyp ERR! build error 
    node-pre-gyp ERR! stack Error: Failed to execute '/home/dominik/.nvm/versions/node/v12.18.3/bin/node /home/dominik/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --jobs=8 --module=/run/media/dominik/Data/workspace/<projectName>/node_modules/realm/compiled/electron-v9.1_linux_x64/realm.node --module_name=realm --module_path=/run/media/dominik/Data/workspace/<projectName>/node_modules/realm/compiled/electron-v9.1_linux_x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v9.1' (1)
    node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/run/media/dominik/Data/workspace/<projectName>/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
    node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
    node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
    node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
    node-pre-gyp ERR! System Linux 5.6.19-2-MANJARO
    node-pre-gyp ERR! command "/home/dominik/.nvm/versions/node/v12.18.3/bin/node" "/run/media/dominik/Data/workspace/<projectName>/node_modules/realm/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "-j" "8"
    node-pre-gyp ERR! cwd /run/media/dominik/Data/workspace/<projectName>/node_modules/realm
    node-pre-gyp ERR! node -v v12.18.3
    node-pre-gyp ERR! node-pre-gyp -v v0.15.0
    node-pre-gyp ERR! not ok 
    error Command failed with exit code 1.
    
                    command=/home/dominik/.nvm/versions/node/v12.18.3/bin/node /usr/lib/node_modules/yarn/bin/yarn.js run install
                    workingDir=/run/media/dominik/Data/workspace/<projectName>/node_modules/realm
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Building the dependency manually *without* electron via `npm --build-from-source install realm` works. But building them via electron, it fails.
I also tried to install it manually via electron from the electron docs: https://www.electronjs.org/docs/tutorial/using-native-node-modules#using-npm, but with the same results.

**Comment by kneth** [comment]
We don't rebuild for Electron v9.1: https://github.com/realm/realm-js/blob/master/Jenkinsfile#L13
