### ISSUE TITLE
couldn't find DSO to load: librealmreact.so

### ISSUE THREAD

**Issue by apperside** [realm/realm-js#3228]
Hello,
I have tryied to follow the steps in the [mongodb tutorial to create a react-native task tracker app](https://docs.mongodb.com/realm/tutorial/react-native/).
I can succesfully run the app on ios, but when I try to run on android I get the following error (and I get the same exact error if I try to run the react-native sample app located [here](https://github.com/mongodb-university/realm-tutorial/tree/main/rn) 

2020-09-16 16:23:41.593 15010-15084/com.rn D/SoLoader: About to load: librealmreact.so
2020-09-16 16:23:41.593 15010-15084/com.rn D/SoLoader: librealmreact.so not found on /data/data/com.rn/lib-main
2020-09-16 16:23:41.593 15010-15084/com.rn D/SoLoader: librealmreact.so found on /data/app/com.rn-jXS9bJol0Owk5xSwXAX-Lw==/lib/arm64
2020-09-16 16:23:41.593 15010-15084/com.rn D/SoLoader: Not resolving dependencies for librealmreact.so
2020-09-16 16:23:41.602 15010-15084/com.rn W/System.err: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN5realm3app10PushClient15register_deviceERKNSt6__ndk112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEENS2_10shared_ptrINS_8SyncUserEEENS2_8functionIFvNS_4util8OptionalINS0_8AppErrorEEEEEE" referenced by "/data/app/com.rn-jXS9bJol0Owk5xSwXAX-Lw==/lib/arm64/librealmreact.so"...
2020-09-16 16:23:41.602 15010-15084/com.rn W/System.err:     at java.lang.Runtime.load0(Runtime.java:938)
2020-09-16 16:23:41.602 15010-15084/com.rn W/System.err:     at java.lang.System.load(System.java:1631)
2020-09-16 16:23:41.602 15010-15084/com.rn W/System.err:     at com.facebook.soloader.SoLoader$1.load(SoLoader.java:395)
2020-09-16 16:23:41.602 15010-15084/com.rn W/System.err:     at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:77)
2020-09-16 16:23:41.602 15010-15084/com.rn W/System.err:     at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:50)
2020-09-16 16:23:41.602 15010-15084/com.rn W/System.err:     at com.facebook.soloader.ApplicationSoSource.loadLibrary(ApplicationSoSource.java:82)
2020-09-16 16:23:41.602 15010-15084/com.rn W/System.err:     at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:766)
2020-09-16 16:23:41.602 15010-15084/com.rn W/System.err:     at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:673)
2020-09-16 16:23:41.602 15010-15084/com.rn W/System.err:     at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:611)
2020-09-16 16:23:41.603 15010-15084/com.rn W/System.err:     at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:559)
2020-09-16 16:23:41.603 15010-15084/com.rn W/System.err:     at io.realm.react.RealmReactModule.<clinit>(RealmReactModule.java:56)
2020-09-16 16:23:41.603 15010-15084/com.rn W/System.err:     at io.realm.react.RealmReactPackage.createNativeModules(RealmReactPackage.java:31)
2020-09-16 16:23:41.603 15010-15084/com.rn W/System.err:     at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
2020-09-16 16:23:41.603 15010-15084/com.rn W/System.err:     at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
2020-09-16 16:23:41.603 15010-15084/com.rn W/System.err:     at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1298)
2020-09-16 16:23:41.603 15010-15084/com.rn W/System.err:     at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1269)
2020-09-16 16:23:41.603 15010-15084/com.rn W/System.err:     at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1194)
2020-09-16 16:23:41.603 15010-15084/com.rn W/System.err:     at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:132)
2020-09-16 16:23:41.603 15010-15084/com.rn W/System.err:     at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:996)
2020-09-16 16:23:41.603 15010-15084/com.rn W/System.err:     at java.lang.Thread.run(Thread.java:919)
2020-09-16 16:23:41.603 15010-15084/com.rn E/SoLoader: couldn't find DSO to load: librealmreact.so caused by: dlopen failed: cannot locate symbol "_ZN5realm3app10PushClient15register_deviceERKNSt6__ndk112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEENS2_10shared_ptrINS_8SyncUserEEENS2_8functionIFvNS_4util8OptionalINS0_8AppErrorEEEEEE" referenced by "/data/app/com.rn-jXS9bJol0Owk5xSwXAX-Lw==/lib/arm64/librealmreact.so"... result: 0
2020-09-16 16:23:41.604 15010-15084/com.rn E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.rn, PID: 15010
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: librealmreact.so caused by: dlopen failed: cannot locate symbol "_ZN5realm3app10PushClient15register_deviceERKNSt6__ndk112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEENS2_10shared_ptrINS_8SyncUserEEENS2_8functionIFvNS_4util8OptionalINS0_8AppErrorEEEEEE" referenced by "/data/app/com.rn-jXS9bJol0Owk5xSwXAX-Lw==/lib/arm64/librealmreact.so"... result: 0
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:825)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:673)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:611)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:559)
        at io.realm.react.RealmReactModule.<clinit>(RealmReactModule.java:56)
        at io.realm.react.RealmReactPackage.createNativeModules(RealmReactPackage.java:31)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1298)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1269)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1194)
        at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:132)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:996)
        at java.lang.Thread.run(Thread.java:919)

**This is the screenshot of apk analyzer**

<img width="1261" alt="Screenshot 2020-09-16 at 16 55 21" src="https://user-images.githubusercontent.com/5955338/93354790-b0230500-f83d-11ea-9298-9c791d665ebf.png">

I am not using hermes nor proguard

## Version of Realm and Tooling

- Realm JS SDK Version: 10.0.0-beta.9
- Node or React Native: react-nattive
- Which debugger for React Native: None

System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 285.73 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.22.0 - ~/.nvm/versions/node/v10.22.0/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v10.22.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 25, 26, 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.7/11E801a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242-release - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by ianpward** [comment]
@apperside  can you try beta.12 please?

**Comment by apperside** [comment]
@ianpward it works, thank you :-)

**Comment by apperside** [comment]
Hello @ianpward ,
actually the android problem does not occour anymore with beta.12, but it breaks iOS.
[Here](https://pastebin.com/jAA2PR4b) you can find the complete stack trace, I couldn't paste it here becase is too long

**Comment by apperside** [comment]
Hi @kraenhansen ,
sure, after changing to beta.12 I deleted node_modules and ran `npm i && cd ios && pod install.`

**Comment by kraenhansen** [comment]
@apperside are you building via the `react-native` CLI or Xcode? And did you clean the build folder?

**Comment by apperside** [comment]
I tried to run both from Xcode and from RN cli, both attempts done (twice) after cleaning the build folder from Xcode

**Comment by apperside** [comment]
Maybe it has been fixed by beta.13 (I see something related to it in the release notes), I'm gonna trying it

**Comment by apperside** [comment]
it seem that with beta.13 is now working with both android and ios

**Comment by kraenhansen** [comment]
Awesome! Thanks for taking the time to investigate this further.

**Comment by droidMakk** [comment]
anything came up with this investigation?
