### ISSUE TITLE
couldn't find DSO to load: librealmreact.so caused by: dlopen failed: cannot locate symbol

### ISSUE THREAD

**Issue by hengkx** [realm/realm-js#3347]
## Actual Results
E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.hengzwl.privacy, PID: 26709
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: librealmreact.so caused by: dlopen failed: cannot locate symbol "_ZN5realm3app8AppUtils16check_for_errorsERKNS0_8ResponseE" referenced by "/data/app/~~GgWshyS60acp1mnzsu16Gw==/com.hengzwl.privacy-2-JN-jai49kaJKEMlhaYRA==/lib/x86/librealmreact.so"... result: 0
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:896)
        at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:725)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:649)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:629)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:577)
        at io.realm.react.RealmReactModule.<clinit>(RealmReactModule.java:56)
        at io.realm.react.RealmReactPackage.createNativeModules(RealmReactPackage.java:31)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1347)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1318)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1225)
        at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1016)
        at java.lang.Thread.run(Thread.java:923)

## Version of Realm and Tooling

- Realm JS SDK Version: 10.0.0
- Node or React Native: 0.63.3
- Client OS & Version: android
- Which debugger for React Native: React Native

**Comment by blagoev** [comment]
thanks for reporting, we will investigate this with high priority

**Comment by hengkx** [comment]
Thank you very much for your quick response. When will it be released?

**Comment by blagoev** [comment]
In general we don't comment on future releases and dates but as I said it will be treated with high priority

**Comment by hengkx** [comment]
resolved

**Comment by ianpward** [comment]
@hengkx Thank you for the report - we really appreciate it

**Comment by vorousjames** [comment]
year and a half later, this is happening for me on the M1 architecture building a fresh install of react-native after trying to build a freshly cleaned android project
RN: 64.2
Realm: 10.6.0
MacOS: 11.3
Android Studio: 4.2.1

any update? @blagoev

**Comment by kneth** [comment]
@vorousjames Could you provide the build log?
