### ISSUE TITLE
Failed to execute 'send' on 'XMLHttpRequest' with REALM 10.1.2

### ISSUE THREAD

**Issue by xlucxs** [realm/realm-js#3486]
I am using the latest version currently available

> "react": "16.13.1",
> "react-native": "0.63.4",
>  "realm": "^10.1.2",

I have this error in Chrome after updating to the latest version

![image](https://user-images.githubusercontent.com/42546473/103172128-925c3780-4851-11eb-9d52-8d8283008e9e.png)

My app is crashing on startup with the Pixel 4 XL emulator, same problem with Samsung S8 (Android 9)

This error seems to appear after the login function, I've followed the relam mongodb totorial https://github.com/mongodb-university/realm-tutorial/tree/main/rn

    // The log in function takes an email and password and uses the emailPassword
    // authentication provider to log in.
    const logIn = async (email, password) => {
        console.log(`Logging in as ${email}...`);
        const creds = Realm.Credentials.emailPassword(email, password);
        const newUser = await app.logIn(creds);
        setUser(newUser);
        console.log(`Logged in as ${newUser.id}`);
      };

![image](https://user-images.githubusercontent.com/42546473/103172350-1e229380-4853-11eb-8297-5c86dc4f253d.png)

I've tried to 

- Reset chrome cache
- Reinstall the application
- https://github.com/realm/realm-js/issues/2551#issuecomment-542392638

Maybe the error is comming from https://reactnative.dev/docs/running-on-device with
`$ adb -s <device name> reverse tcp:8081 tcp:8081`
when setting up the environnement ...

Thank you for the help :)

**Comment by kneth** [comment]
Thank you for your detailed bug report.

We are aware of a bug which prevents reloading the app on Android (see comment in second bug fix in https://github.com/realm/realm-js/blob/master/CHANGELOG.md#1012-release-notes-2020-12-16). 

Do you observe the crash every time?

**Comment by xlucxs** [comment]
> Thank you for your detailed bug report.
> 
> We are aware of a bug which prevents reloading the app on Android (see comment in second bug fix in https://github.com/realm/realm-js/blob/master/CHANGELOG.md#1012-release-notes-2020-12-16). 
> 
> Do you observe the crash every time?

Thank you for the answer, yes it happens every time the application is reloaded with the debugger

**Comment by xlucxs** [comment]
@fronck There is no problem when the login function is not called, the application works normally. Once the login function is called and the application is reloaded, that's when it crashes.

**Comment by kraenhansen** [comment]
@xlucxs just a heads up that the repository that you're referencing [has been deprecated](https://github.com/mongodb-university/realm-tutorial/blob/main/README.md#%EF%B8%8F-deprecated) and is no longer maintained:
> This repository is no longer maintained. Please follow along with the tutorial at https://docs.mongodb.com/realm/tutorial

**Comment by xlucxs** [comment]
@kraenhansen Thanks, I've adapted the code with the new tutorial https://docs.mongodb.com/realm/tutorial/react-native, but the problem persists

I completely re-installed my environment by following this tutorial https://reactnative.dev/docs/environment-setup

Now after reloading the application once the login function has been called, I got this error. I'm using the react-native-keychain library, the problem is maybe comming from there ...

```
Keychain couldn't be accessed! DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://192.168.1.227:8083/call_method'.
    at makeRequest (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:104615:16)
    at sendRequest (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:104661:22)
    at Object.callMethod (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:104420:18)
    at App.<anonymous> (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:104130:20)
    at http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:112636:24
    at http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:103443:9
    at tryCallTwo (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27000:7)
    at doResolve (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27164:15)
    at new Promise (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27023:5)
    at promisify (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:103442:14)
```

    
I will continue to look for...

**Comment by kraenhansen** [comment]
Just to be clear, the error that you're seeing `Failed to execute 'send' on 'XMLHttpRequest'` is thrown when the Chrome debugging process cannot react the RPC web-server embedded in the Realm library. The client (chrome) side logs are of little use, since they're almost certainly a symptom of something else.

The cause of the error is almost always one of two:
1. The device is not on the same network or the port has not been forwarded correctly.
2. The app running on the device (or simulator) has crashed. The root cause of that crash can be anything ...

Since your initial description mentioned that the app was crashing on startup, I believe we're in the latter of the two scenarios.
Therefore I would love to see the logcat output or any backtrace that might be reviled from running the app using Android Studio.

**Comment by xlucxs** [comment]
@kraenhansen 

Here is the logcat from android studio, the crash seems to happen at this moment


```
2021-02-02 14:14:58.635 25768-25783/com.electroperrinapplication I/chatty: uid=10133(com.electroperrinapplication) FinalizerDaemon identical 15 lines
2021-02-02 14:14:58.635 25768-25783/com.electroperrinapplication W/System: A resource failed to call end. 
2021-02-02 14:14:58.715 25768-25768/com.electroperrinapplication W/rrinapplicatio: Accessing hidden field Landroid/widget/ScrollView;->mScroller:Landroid/widget/OverScroller; (greylist, reflection, allowed)
2021-02-02 14:14:58.732 25768-25768/com.electroperrinapplication I/ReactNative: [GESTURE HANDLER] Initialize gesture handler for root view com.facebook.react.ReactRootView{30f0fa3 V.E...... ......ID 0,0-1440,2700 #1}
2021-02-02 14:14:58.776 25768-25768/com.electroperrinapplication E/unknown:NativeViewHierarchyManager: Unable to update properties for view tag 213
    com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag 213 could not be found.
    
        at com.facebook.react.uimanager.NativeViewHierarchyManager.resolveViewManager(NativeViewHierarchyManager.java:109)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:133)
        at com.facebook.react.uimanager.UIImplementation.synchronouslyUpdateViewOnUIThread(UIImplementation.java:291)
        at com.facebook.react.uimanager.UIManagerModule.synchronouslyUpdateViewOnUIThread(UIManagerModule.java:400)
        at com.facebook.react.animated.PropsAnimatedNode.updateView(PropsAnimatedNode.java:99)
        at com.facebook.react.animated.NativeAnimatedNodesManager.updateNodes(NativeAnimatedNodesManager.java:548)
        at com.facebook.react.animated.NativeAnimatedNodesManager.runUpdates(NativeAnimatedNodesManager.java:457)
        at com.facebook.react.animated.NativeAnimatedModule$1.doFrameGuarded(NativeAnimatedModule.java:104)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:964)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:721)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2021-02-02 14:14:58.777 25768-25768/com.electroperrinapplication E/unknown:NativeViewHierarchyManager: Unable to update properties for view tag 235
    com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag 235 could not be found.
```

```
021-02-02 14:15:03.009 25768-25783/com.electroperrinapplication I/chatty: uid=10133(com.electroperrinapplication) FinalizerDaemon identical 9 lines
2021-02-02 14:15:03.009 25768-25783/com.electroperrinapplication W/System: A resource failed to call end. 
2021-02-02 14:15:12.380 25768-25768/com.electroperrinapplication W/unknown:ReactNative: Packager connection already open, nooping.
2021-02-02 14:15:12.380 25768-25836/com.electroperrinapplication I/ReactNative: [GESTURE HANDLER] Tearing down gesture handler registered for root view com.facebook.react.ReactRootView{30f0fa3 V.E...... ......ID 0,0-1440,2700}
2021-02-02 14:15:12.381 25768-25836/com.electroperrinapplication I/Realm: Stopping the webserver
2021-02-02 14:15:12.393 25768-25851/com.electroperrinapplication W/MessageQueue: Handler (android.os.Handler) {4c3a820} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {4c3a820} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:558)
        at android.os.Handler.enqueueMessage(Handler.java:754)
        at android.os.Handler.sendMessageAtTime(Handler.java:703)
        at android.os.Handler.sendMessageDelayed(Handler.java:673)
        at android.os.Handler.postDelayed(Handler.java:475)
        at io.realm.react.RealmReactModule$1.run(RealmReactModule.java:166)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2021-02-02 14:15:12.406 25768-26027/com.electroperrinapplication V/JSRealm: setDefaultRealmFileDirectory
2021-02-02 14:15:12.406 25768-26027/com.electroperrinapplication D/JSRealm: Absolute path: /data/data/com.electroperrinapplication/files
2021-02-02 14:15:12.412 25768-26027/com.electroperrinapplication E/unknown:ReactNative: ReactInstanceManager.createReactContext: mJSIModulePackage null
2021-02-02 14:15:12.414 25768-26032/com.electroperrinapplication E/unknown:ReactNative: ReactInstanceManager.attachRootViewToInstance()
```

```
2021-02-02 14:14:54.712 25768-25835/com.electroperrinapplication V/JSRealm: setupChromeDebugModeRealmJsContext
2021-02-02 14:14:54.730 25768-25835/com.electroperrinapplication I/Realm: Starting the debugging WebServer, Host: null Port: 8083
2021-02-02 14:14:54.740 25768-25768/com.electroperrinapplication E/unknown:ReactNative: ReactInstanceManager.attachRootViewToInstance()
2021-02-02 14:14:54.741 25768-25768/com.electroperrinapplication E/unknown:ReactRootView: runApplication: call AppRegistry.runApplication
2021-02-02 14:14:55.597 25768-25783/com.electroperrinapplication W/System: A resource failed to call end. 
2021-02-02 14:14:55.597 25768-25783/com.electroperrinapplication W/System: A resource failed to call end. 
```


I'm currently running the application with the android studio emulator

**Comment by kraenhansen** [comment]
@xlucxs I'm circling back here. I've had a hard time reproducing this issue and would love to know if you're still experiencing this?
