### ISSUE TITLE
Realm (sync) crashes Electron on Windows

### ISSUE THREAD

**Issue by marcoancona** [realm/realm-js#3535]
## Goals

We are building an Electron app using Realm Sync.

## Actual Results

It seems that enabling sync on a Realm crashes Electron (see below). 
- the crash occurs when the code runs on `electron` but not when runs on pure `node`;
- the crash appears on Windows but not on macOS;
- the crash does not appear if no `sync` option is provided;
- the problem seems not to appear when the Realm db is already available on disk (i.e., running the code with `node` first, then with `electron`).

## Steps to Reproduce

On Windows:

```
> cross-env ELECTRON_ENABLE_LOGGING=true ELECTRON_ENABLE_STACK_DUMPING=true electron .\server.js
```
will print
```
{
  node: '14.15.1',
  v8: '8.9.100-electron.0',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.16.1',
  modules: '87',
  nghttp2: '1.41.0',
  napi: '7',
  llhttp: '2.1.3',
  openssl: '1.1.1',
  icu: '68.1',
  unicode: '13.0',
  electron: '12.0.0-beta.18',
  chrome: '89.0.4348.1'
}
Logged in with the user id: 601191a37c8bd7628256e19b
Connection[1]: Session[1]: client_reset_config = false, Realm exists = true, async open = false, client reset = false
Connection[1]: Connected to endpoint '52.49.130.120:443' (from '127.0.0.1:51575')
Connection[1]: Verifying server SSL certificate using 155 root certificates
Received fatal exception 0xc06d007f
Backtrace:
        RaiseException [0x00007FFF9B5E3B29+69]
        (No symbol) [0x00007FFF0ABA8E67]
```

Instead,
```
> node ./server.js
```
produces the expected result:
```
{
  node: '14.15.1',
  v8: '8.4.371.19-node.17',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.16.1',
  modules: '83',
  nghttp2: '1.41.0',
  napi: '7',
  llhttp: '2.1.3',
  openssl: '1.1.1g',
  cldr: '37.0',
  icu: '67.1',
  tz: '2020a',
  unicode: '13.0'
}
Logged in with the user id: 601191a37c8bd7628256e19b
Connection[1]: Session[1]: client_reset_config = false, Realm exists = true, async open = false, client reset = false
Connection[1]: Connected to endpoint '52.49.130.120:443' (from '127.0.0.1:51666')
Connection[1]: Verifying server SSL certificate using 155 root certificates
[
  {
    _id: '3d785166-4da9-453a-9e35-cbaec902904b',
    _partition: null,
    name: 'Test event',
    status: 'Open'
  },
  ...
]
```

**Note**: the problem does *not* appear if first the script is run with `node`, and then with `electron`. In other words, it seems to crash only if the realm database needs to be created from scratch. 

## Code Sample

`server.js`
```js
const Realm = require('realm');
const uuidV4 = require('uuid').v4;

console.log(process.versions);

const TaskSchema = {
  name: 'Task',
  properties: {
    _id: 'string',
    _partition: 'string?',
    name: 'string',
    status: 'string',
  },
  primaryKey: '_id',
};

const app = new Realm.App({ id: 'some-realm-id' });
async function handleLogin() {
  const credentials = Realm.Credentials.anonymous();
  const user = await app.logIn(credentials);
  await user.refreshCustomData();
  console.log(`Logged in with the user id: ${user.id}`);

  const realm = await Realm.open({
    schema: [TaskSchema],
    // inMemory: true,
    sync: {
      user: app.currentUser,
      partitionValue: 'myPartition',
    },
  });

  realm.write(() => {
    realm.create('Task', {
      _id: uuidV4(),
      name: 'Test event',
      status: 'Open',
    });
  });

  const syncTasks = realm.objects('Task');
  console.log(syncTasks.toJSON());
  realm.addListener('change', () => {
    console.log('sync tasks - ', syncTasks.toJSON());
  });
}

handleLogin().catch((err) => console.error(err));
process.stdin.resume();

process.on('uncaughtException', (err, origin) => {
  console.log(err);
  console.log(origin);
});

process.on('unhandledRejection', (reason, p) => {
  console.log('Unhandled Rejection at: Promise ', p, ' reason: ', reason);
  // application specific logging, throwing an error, or other logic here
});

process.on('SIGTERM', (signal) => {
  console.log(`Process ${process.pid} received a SIGTERM signal`);
  process.exit(0);
});

process.on('SIGINT', (signal) => {
  console.log(`Process ${process.pid} has been interrupted`);
  process.exit(0);
});


```

## Version of Realm and Tooling

- Realm JS SDK Version: 10.1.4
- Node or React Native: Electron 12 / Node 14 (see logs above)
- Client OS & Version: Windows 10

**Comment by kraenhansen** [comment]
Thanks a lot for the detailed bug report, I'll try to reproduce this.

**Comment by kraenhansen** [comment]
I've been unsuccessful in reproducing this.

The following is my output of running `npx electron server.js` on a Windows 10 machine:

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\kraen.hansen\Projects\realm-js-issue-3535> node -v
node : The term 'node' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that 
the path is correct and try again.
At line:1 char:1
+ node -v
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (node:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS C:\Users\kraen.hansen\Projects\realm-js-issue-3535> nvm use 14
14.0.0
Now using node v14.0.0 (64-bit)
PS C:\Users\kraen.hansen\Projects\realm-js-issue-3535> node -v
v14.0.0
PS C:\Users\kraen.hansen\Projects\realm-js-issue-3535> nvm

Running version 1.1.7.

Usage:

  nvm arch                     : Show if node is running in 32 or 64 bit mode.
  nvm install <version> [arch] : The version can be a node.js version or "latest" for the latest stable version.
                                 Optionally specify whether to install the 32 or 64 bit version (defaults to system arch).
                                 Set [arch] to "all" to install 32 AND 64 bit versions.
                                 Add --insecure to the end of this command to bypass SSL validation of the remote download server.
  nvm list [available]         : List the node.js installations. Type "available" at the end to see what can be installed. Aliased as ls.
  nvm on                       : Enable node.js version management.
  nvm off                      : Disable node.js version management.
  nvm proxy [url]              : Set a proxy to use for downloads. Leave [url] blank to see the current proxy.
                                 Set [url] to "none" to remove the proxy.
  nvm node_mirror [url]        : Set the node mirror. Defaults to https://nodejs.org/dist/. Leave [url] blank to use default url.
  nvm npm_mirror [url]         : Set the npm mirror. Defaults to https://github.com/npm/cli/archive/. Leave [url] blank to default url.
  nvm uninstall <version>      : The version must be a specific version.
  nvm use [version] [arch]     : Switch to use the specified version. Optionally specify 32/64bit architecture.
                                 nvm use <arch> will continue using the selected version, but switch to 32/64 bit mode.
  nvm root [path]              : Set the directory where nvm should store different versions of node.js.
                                 If <path> is not set, the current root will be displayed.
  nvm version                  : Displays the current running version of nvm for Windows. Aliased as v.

PS C:\Users\kraen.hansen\Projects\realm-js-issue-3535> ls


    Directory: C:\Users\kraen.hansen\Projects\realm-js-issue-3535


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         1/29/2021  12:58 PM           1724 index.js


PS C:\Users\kraen.hansen\Projects\realm-js-issue-3535> node .\index.js
internal/modules/cjs/loader.js:1017
  throw err;
  ^

Error: Cannot find module 'realm'
Require stack:
- C:\Users\kraen.hansen\Projects\realm-js-issue-3535\index.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1014:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:884:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:1074:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:72:18)←[39m
    at Object.<anonymous> (C:\Users\kraen.hansen\Projects\realm-js-issue-3535\index.js:1:15)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1185:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:1034:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:923:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'C:\\Users\\kraen.hansen\\Projects\\realm-js-issue-3535\\index.js'←[39m
  ]
}
PS C:\Users\kraen.hansen\Projects\realm-js-issue-3535> npm init -y
Wrote to C:\Users\kraen.hansen\Projects\realm-js-issue-3535\package.json:

{
  "name": "realm-js-issue-3535",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


PS C:\Users\kraen.hansen\Projects\realm-js-issue-3535> npm install realm
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> realm@10.1.4 install C:\Users\kraen.hansen\Projects\realm-js-issue-3535\node_modules\realm
> node-pre-gyp install --fallback-to-build -j 8 ${npm_config_arch:+--target_arch=${npm_config_arch}}

node-pre-gyp WARN Using request for node-pre-gyp https download
[realm] Success: "C:\Users\kraen.hansen\Projects\realm-js-issue-3535\node_modules\realm\compiled\napi-v4_win32_x64\realm.node" is installed via remote
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN deprecated-react-native-listview@0.0.6 requires a peer of react@* but none is installed. You must install peer dependencies yourself.
npm WARN deprecated-react-native-listview@0.0.6 requires a peer of react-native@* but none is installed. You must install peer dependencies yourself.
npm WARN realm-js-issue-3535@1.0.0 No description
npm WARN realm-js-issue-3535@1.0.0 No repository field.

+ realm@10.1.4
added 173 packages from 262 contributors and audited 173 packages in 42.125s

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

PS C:\Users\kraen.hansen\Projects\realm-js-issue-3535> npm install electron

> core-js@3.8.3 postinstall C:\Users\kraen.hansen\Projects\realm-js-issue-3535\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> electron@11.2.1 postinstall C:\Users\kraen.hansen\Projects\realm-js-issue-3535\node_modules\electron
> node install.js

Downloading electron-v11.2.1-win32-x64.zip: [====================================================================================================] 100% ETA: 0.0 seconds
npm WARN deprecated-react-native-listview@0.0.6 requires a peer of react@* but none is installed. You must install peer dependencies yourself.
npm WARN deprecated-react-native-listview@0.0.6 requires a peer of react-native@* but none is installed. You must install peer dependencies yourself.
npm WARN realm-js-issue-3535@1.0.0 No description
npm WARN realm-js-issue-3535@1.0.0 No repository field.

+ electron@11.2.1
added 73 packages from 87 contributors and audited 246 packages in 65.86s

12 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

PS C:\Users\kraen.hansen\Projects\realm-js-issue-3535> node .\index.js
{
  node: '14.0.0',
  v8: '8.1.307.30-node.30',
  uv: '1.37.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.16.0',
  modules: '83',
  nghttp2: '1.40.0',
  napi: '6',
  llhttp: '2.0.4',
  openssl: '1.1.1f',
  cldr: '36.1',
  icu: '66.1',
  tz: '2019c',
  unicode: '13.0'
}
{
  message: "cannot find app using Client App ID 'some-realm-id'",
  code: -1
}
Process 3484 has been interrupted
PS C:\Users\kraen.hansen\Projects\realm-js-issue-3535> node .\index.js
{
  node: '14.0.0',
  v8: '8.1.307.30-node.30',
  uv: '1.37.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.16.0',
  modules: '83',
  nghttp2: '1.40.0',
  napi: '6',
  llhttp: '2.0.4',
  openssl: '1.1.1f',
  cldr: '36.1',
  icu: '66.1',
  tz: '2019c',
  unicode: '13.0'
}
{ message: "authentication via 'anon-user' is unsupported", code: 2 }
Process 2860 has been interrupted
PS C:\Users\kraen.hansen\Projects\realm-js-issue-3535> node .\index.js
{
  node: '14.0.0',
  v8: '8.1.307.30-node.30',
  uv: '1.37.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.16.0',
  modules: '83',
  nghttp2: '1.40.0',
  napi: '6',
  llhttp: '2.0.4',
  openssl: '1.1.1f',
  cldr: '36.1',
  icu: '66.1',
  tz: '2019c',
  unicode: '13.0'
}
Logged in with the user id: 6013fe2d3ff3614ebd228efe
Connection[1]: Session[1]: client_reset_config = false, Realm exists = false, async open = false, client reset = false
Connection[1]: Connected to endpoint '52.16.113.157:443' (from '127.0.0.1:54650')
Connection[1]: Verifying server SSL certificate using 155 root certificates
Connection[1]: Disconnected
{
  message: 'The following changes cannot be made in additive-only schema mode:\n' +
    "- Property 'Task._id' has been changed from 'object id' to 'string'.\n" +
    "- Property 'Task._partition' has been made optional.",
  errorCode: 1
}
Process 4808 has been interrupted
PS C:\Users\kraen.hansen\Projects\realm-js-issue-3535> node .\index.js
{
  node: '14.0.0',
  v8: '8.1.307.30-node.30',
  uv: '1.37.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.16.0',
  modules: '83',
  nghttp2: '1.40.0',
  napi: '6',
  llhttp: '2.0.4',
  openssl: '1.1.1f',
  cldr: '36.1',
  icu: '66.1',
  tz: '2019c',
  unicode: '13.0'
}
Logged in with the user id: 6013fe2d3ff3614ebd228efe
Connection[1]: Session[1]: client_reset_config = false, Realm exists = true, async open = false, client reset = false
Connection[1]: Connected to endpoint '52.16.113.157:443' (from '127.0.0.1:54653')
Connection[1]: Verifying server SSL certificate using 155 root certificates
Error: Task._id must be of type 'objectId', got 'string' ('1b55646f-5db8-4328-94c2-bab46eb2ed06')
    at Realm.<anonymous> (C:\Users\kraen.hansen\Projects\realm-js-issue-3535\index.js:34:11)
    at handleLogin (C:\Users\kraen.hansen\Projects\realm-js-issue-3535\index.js:33:9)
Connection[1]: Disconnected
Process 5528 has been interrupted
PS C:\Users\kraen.hansen\Projects\realm-js-issue-3535> node .\index.js
{
  node: '14.0.0',
  v8: '8.1.307.30-node.30',
  uv: '1.37.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.16.0',
  modules: '83',
  nghttp2: '1.40.0',
  napi: '6',
  llhttp: '2.0.4',
  openssl: '1.1.1f',
  cldr: '36.1',
  icu: '66.1',
  tz: '2019c',
  unicode: '13.0'
}
Logged in with the user id: 6013fe2d3ff3614ebd228efe
Connection[1]: Session[1]: client_reset_config = false, Realm exists = true, async open = false, client reset = false
Connection[1]: Connected to endpoint '52.16.113.157:443' (from '127.0.0.1:54656')
Connection[1]: Verifying server SSL certificate using 155 root certificates
Error: Missing value for property 'Task._partition'
    at Realm.<anonymous> (C:\Users\kraen.hansen\Projects\realm-js-issue-3535\index.js:34:11)
    at handleLogin (C:\Users\kraen.hansen\Projects\realm-js-issue-3535\index.js:33:9)
Connection[1]: Disconnected
Process 2548 has been interrupted
PS C:\Users\kraen.hansen\Projects\realm-js-issue-3535> node .\index.js
{
  node: '14.0.0',
  v8: '8.1.307.30-node.30',
  uv: '1.37.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.16.0',
  modules: '83',
  nghttp2: '1.40.0',
  napi: '6',
  llhttp: '2.0.4',
  openssl: '1.1.1f',
  cldr: '36.1',
  icu: '66.1',
  tz: '2019c',
  unicode: '13.0'
}
Logged in with the user id: 6013fe2d3ff3614ebd228efe
Connection[1]: Session[1]: client_reset_config = false, Realm exists = true, async open = false, client reset = false
Connection[1]: Connected to endpoint '52.16.113.157:443' (from '127.0.0.1:54663')
Connection[1]: Verifying server SSL certificate using 155 root certificates
[
  {
    _id: ObjectId("6013fec285d906e435716b75"),
    _partition: 'myPartition',
    name: 'Test event',
    status: 'Open'
  }
]
sync tasks -  [
  {
    _id: ObjectId("6013fec285d906e435716b75"),
    _partition: 'myPartition',
    name: 'Test event!',
    status: 'Open'
  }
]
Process 6652 has been interrupted
PS C:\Users\kraen.hansen\Projects\realm-js-issue-3535> electron .\index.js
electron : The term 'electron' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify 
that the path is correct and try again.
At line:1 char:1
+ electron .\index.js
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (electron:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS C:\Users\kraen.hansen\Projects\realm-js-issue-3535> npx electron index.js

{
  node: '12.18.3',
  v8: '8.7.220.31-electron.0',
  uv: '1.38.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.16.0',
  modules: '85',
  nghttp2: '1.41.0',
  napi: '6',
  llhttp: '2.0.4',
  http_parser: '2.9.3',
  openssl: '1.1.1',
  icu: '67.1',
  unicode: '13.0',
  electron: '11.2.1',
  chrome: '87.0.4280.141'
}
Logged in with the user id: 6013fe2d3ff3614ebd228efe
Connection[1]: Session[1]: client_reset_config = false, Realm exists = true, async open = false, client reset = false
Connection[1]: Connected to endpoint '34.241.208.56:443' (from '127.0.0.1:54669')
Connection[1]: Verifying server SSL certificate using 155 root certificates
[
  {
    _id: ObjectId("6013fec285d906e435716b75"),
    _partition: 'myPartition',
    name: 'Test event!',
    status: 'Open'
  },
  {
    _id: ObjectId("6014009875860910eaa0bee2"),
    _partition: 'myPartition',
    name: 'Test event',
    status: 'Open'
  }
]
sync tasks -  [
  {
    _id: ObjectId("6013fec285d906e435716b75"),
    _partition: 'myPartition',
    name: 'Test event!',
    status: 'Open'
  },
  {
    _id: ObjectId("6014009875860910eaa0bee2"),
    _partition: 'myPartition',
    name: 'Test event!!!',
    status: 'Open'
  }
]
```

**Comment by marcoancona** [comment]
This is weird, I cannot reproduce it anymore either. I have to say that I deleted the remote collection and stopped/restarted the Sync in the meanwhile, but now it seems to work fine so I will close this issue.

**Comment by bartoszhernas** [comment]
Hi, we have a similar issue with Electron 12 and Realm.

```
C:\Users\bartoszhernas>SET ELECTRON_ENABLE_STACK_DUMPING=true

C:\Users\bartoszhernas>C:\Users\bartoszhernas\AppData\Local\Programs\freeyourmusicrc\FreeYourMusicRC.exe

C:\Users\bartoszhernas>
ReleaseId: 2d7d071b2a3196bde8b7e0436731b89e2646e9fd
15:37:46.541 > Is windows: true
15:37:46.552 > os.release(): 10.0.21286
15:37:46.560 > Is dev: false
Original user agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) FreeYourMusicRC/6.0.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
Replaced user agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) FreeYourMusicRC/6.0.0 Chrome/89.0.4389.69 Safari/537.36
15:37:46.728 > Web contents [object Object] created
rendererLocation:  file://C:\Users\bartoszhernas\AppData\Local\Programs\freeyourmusicrc\resources\app.asar\build\index.html?userPath=C%3A%5CUsers%5Cbartoszhernas%5CAppData%5CRoaming%5CFreeYourMusicRC&deviceId=238033c100a4b6ddcc7cbea41a85bccb9fb91f80c302b01f7f296ec8e98e5cc2
Connection[1]: Session[1]: client_reset_config = false, Realm exists = true, async open = false, client reset = false
Connection[1]: Connected to endpoint '34.241.208.56:443' (from '127.0.0.1:53807')
Connection[1]: Verifying server SSL certificate using 155 root certificates
15:37:50.141 > Checking for update
Received fatal exception 0xc06d007f
Backtrace:
        PackageSidFromProductId [0x00007FFDF93DD6A8+205438]
15:37:51.553 > Update for version 6.0.0 is not available (latest version: 6.0.0, downgrade is disallowed).
```

**Comment by bimusiek** [comment]
Some more info about @bartoszhernas issue as I am working with him.

The latest version it works with is Electron 10.4.0. 
Any Electron 11.x, 12.x or even beta 13.x crashes the app. 

We can see that Electron crashes the moment that Realm is initialised. 
If you need, we can provide you executable of exactly the same code built with Electron 10.4.0 (that works) and Electron 12.0.0 which crashes. 

The workaround for us is to ship Electron 10.4.0 for Windows users and Electron 12.0.0 for the rest of the platforms (so we can support ARM64 on Apple).

Any suggestions how we can debug the issue would be much appreciated. The only info we have is Backtrace: `PackageSidFromProductId`

**Comment by kneth** [comment]
Realm JavaScript v10.4.2 has a fix for this.
