### ISSUE TITLE
AWS Lambda Cannot find module /var/task/node_modules/realm/compiled/napi-v4_linux_x64/realm.node

### ISSUE THREAD

**Issue by cloudworkpro-sean** [realm/realm-js#3583]
I am trying to run a simple auth function on AWS Lambda using Realm-js with Server API Key authentication. When hitting the endpoint I get a node error. 
 
## Goals

I am trying to authenticate a server user using Realm

## Expected Results

return the user object

## Actual Results

```console
	ERROR	Uncaught Exception 	{
"errorType":"Runtime.ImportModuleError",
"errorMessage":"Error: Cannot find module '/var/task/node_modules/realm/compiled/napi-v4_linux_x64/realm.node'
Require stack:
- /var/task/node_modules/realm/lib/index.js
- /var/task/dist/login.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js","stack":["Runtime.ImportModuleError: Error: Cannot find module
'/var/task/node_modules/realm/compiled/napi-v4_linux_x64/realm.node'",
"Require stack:","- /var/task/node_modules/realm/lib/index.js","- /var/task/dist/login.js",
"- /var/runtime/UserFunction.js","- /var/runtime/index.js",
"    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
"    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)","    at Object.<anonymous> (/var/runtime/index.js:43:30)",
"    at Module._compile (internal/modules/cjs/loader.js:1063:30)",
"    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)",
"    at Module.load (internal/modules/cjs/loader.js:928:32)",
"    at Function.Module._load (internal/modules/cjs/loader.js:769:14)",
"    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)",
"    at internal/main/run_main_module.js:17:47"]}
```

## Steps to Reproduce

Deploy the following function to Lambda and make a post request to it.

## Code Sample

```javascript
import Realm from "realm";
const serverless = require('serverless-http')
const express = require('express')
const bodyParser = require('body-parser')
import { getSecret } from '@techlinksolutions/get-aws-secrets'

const app = express()
app.use(bodyParser.json())
const region = process.env.REGION

  async function login() {
    const secretRes = await getSecret('APP_ID_KEY_NAME', region)
 
    const id = secretRes.SecretString
    console.log(id);
    const config = {
        id,
    }
    const app = new Realm.App(config)
    
    const credentials = Realm.Credentials.serverApiKey(
          API_KEY_HERE
      );

    const user = await app.logIn(credentials);
    return user;
}

app.post('/auth/login', async function(req, res) {
    res.set({
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Credentials': true,
    })
    
    res.send(await login())
})

module.exports.handler = serverless(app)
```

## Version of Realm and Tooling

- Realm JS SDK Version: 10.2.0
- Node or React Native: Node
- Client OS & Version: MacOS Catalina 10.15.7
- Which debugger for React Native: N/A

**Comment by kneth** [comment]
The error message indicates that the Realm module isn't installed. As I recalled it, AWS has a bug which prevent Realm to work correctly - see #2509.

**Comment by cloudworkpro-sean** [comment]
Thanks @kneth! This should be included in the docs until it's fixed. I tried the work around in #2509 but its not working for me. Still getting the same error. I think we'll hold off using Realm for now. Thanks for the help!

**Comment by kneth** [comment]
@cloudworkpro-sean  https://github.com/realm/realm-js/pull/3591
