### ISSUE TITLE
Crash When running on Android

### ISSUE THREAD

**Issue by iyansr** [realm/realm-js#3904]
## Goals

Running on android normally

## Expected Results

Running on android normally

## Actual Results

Got Crash :

Name
FATAL EXCEPTION: create_react_context
Reason
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: librealm.so caused by: couldn't find DSO to load: libjsc.so result: 0 result: 0
Stacktrace
FATAL EXCEPTION: create_react_context
Process: com.valar.pintu.debug, PID: 6019
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: librealm.so caused by: couldn't find DSO to load: libjsc.so result: 0 result: 0
at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:825)
at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:673)
at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:611)
at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:559)
at io.realm.react.RealmReactModule.<clinit>(RealmReactModule.java:57)
at io.realm.react.RealmReactPackage.createNativeModules(RealmReactPackage.java:31)
at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1347)
at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1318)
at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1225)
at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1016)
at java.lang.Thread.run(Thread.java:919)

## Steps to Reproduce

instal realm package
run on android emulatoirs

## Version of Realm and Tooling

- Realm JS SDK Version: 10.6.1
- Node or React Native: Node v14.16.0 / RN 0.63.4
- Client OS & Version: Windows 10
- Which debugger for React Native: Flipper

**Comment by kneth** [comment]
`couldn't find DSO to load: libjsc.so` indicates that you are using Hermes. We currently don't support Hermes  - see #3792.

**Comment by iyansr** [comment]
> `couldn't find DSO to load: libjsc.so` indicates that you are using Hermes. We currently don't support Hermes - see #3792.

Yes, it works now, thanks
