### ISSUE TITLE
Realm and React-Native-Threads startup error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by SMhdAsadi** [realm/realm-js#4122]
### Description

I just updated realm to the latest beta version to test hermes support on Android. It bundles successfully but after running, I get this error:
```
Error: ENOENT: no such file or directory, open 'C:\Users\SMhd\project\http:\10.0.2.2:8081\index.thread.bundle?platform=android&dev=true&hot=false&minify=false'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at getCodeFrame (C:\Users\SMhd\project\node_modules\metro\src\Server.js:919:18)
    at Server._symbolicate (C:\Users\SMhd\project\node_modules\metro\src\Server.js:992:22)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Server._processRequest (C:\Users\SMhd\project\node_modules\metro\src\Server.js:403:7) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\SMhd\\project\\http:\\10.0.2.2:8081\\index.thread.bundle?platform=android&dev=true&hot=false&minify=false'
}
```
My app stucks on splash screen with no crashes, but nothing happens.
Seems like there is a problem with index.thread file which will be in another bundle file. It works on realm without hermes though.

### Stacktrace & log output

```shell
Error: ENOENT: no such file or directory, open 'C:\Users\SMhd\project\http:\10.0.2.2:8081\index.thread.bundle?platform=android&dev=true&hot=false&minify=false'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at getCodeFrame (C:\Users\SMhd\project\node_modules\metro\src\Server.js:919:18)
    at Server._symbolicate (C:\Users\SMhd\project\node_modules\metro\src\Server.js:992:22)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Server._processRequest (C:\Users\SMhd\project\node_modules\metro\src\Server.js:403:7) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\SMhd\\project\\http:\\10.0.2.2:8081\\index.thread.bundle?platform=android&dev=true&hot=false&minify=false'
}
Error: ENOENT: no such file or directory, open 'C:\Users\SMhd\project\http:\10.0.2.2:8081\index.thread.bundle?platform=android&dev=true&hot=false&minify=false'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at getCodeFrame (C:\Users\SMhd\project\node_modules\metro\src\Server.js:919:18)
    at Server._symbolicate (C:\Users\SMhd\project\node_modules\metro\src\Server.js:992:22)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Server._processRequest (C:\Users\SMhd\project\node_modules\metro\src\Server.js:403:7) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\SMhd\\project\\http:\\10.0.2.2:8081\\index.thread.bundle?platform=android&dev=true&hot=false&minify=false'
}
```

### Can you reproduce a bug?

Not yet

### Version

10.20.0-alpha.2

### What SDK flavour are you using?

Local Database only

### Platform OS and version(s)

Android 10 emulator

**Comment by tomduncalf** [comment]
Are you able to successfully create a new React Native project (not using Realm), using Hermes and react-native-threads? I can't see anything Realm-specific in the stack trace, so I am wondering if this might just be an issue with Hermes and react-native-threads.
