### ISSUE TITLE
npm install of realm@10.2.0 failed on arm64

### ISSUE THREAD

**Issue by npatil-boosterfuels** [realm/realm-js#4190]
I am trying to install realm@10.2.0 on arm64 platform. npm first tries to build realm from source (I assume it didn't find pre-compiled arm64 module?) but then fails with below error.

```
System env
## node -v
v12.22.7
## npm -v
6.14.15
## uname -a
Linux ff43634 5.4.24-iot-gate-imx8-2.4 #1 SMP PREEMPT Sat May 30 07:25:46 UTC 2020 aarch64 GNU/Linux

```
```
object-store.target.mk:173: recipe for target 'Release/obj.target/object-store/src/object-store/src/shared_realm.o' failed
make: *** [Release/obj.target/object-store/src/object-store/src/shared_realm.o] Error 1
make: Leaving directory '/usr/src/optimus/node_modules/realm/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.4.24-iot-gate-imx8-2.4
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--jobs=8" "--module=/usr/src/optimus/node_modules/realm/compiled/napi-v4_linux_arm64/realm.node" "--module_name=realm" "--module_path=/usr/src/optimus/node_modules/realm/compiled/napi-v4_linux_arm64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=4" "--node_napi_label=napi-v4"
gyp ERR! cwd /usr/src/optimus/node_modules/realm
gyp ERR! node -v v12.22.7
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --jobs=8 --module=/usr/src/optimus/node_modules/realm/compiled/napi-v4_linux_arm64/realm.node --module_name=realm --module_path=/usr/src/optimus/node_modules/realm/compiled/napi-v4_linux_arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=4 --node_napi_label=napi-v4' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/src/optimus/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1022:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Linux 5.4.24-iot-gate-imx8-2.4
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/src/optimus/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "-j" "8"
node-pre-gyp ERR! cwd /usr/src/optimus/node_modules/realm
node-pre-gyp ERR! node -v v12.22.7
node-pre-gyp ERR! node-pre-gyp -v v0.15.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --jobs=8 --module=/usr/src/optimus/node_modules/realm/compiled/napi-v4_linux_arm64/realm.node --module_name=realm --module_path=/usr/src/optimus/node_modules/realm/compiled/napi-v4_linux_arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=4 --node_napi_label=napi-v4' (1)
npm WARN deprecated-react-native-listview@0.0.6 requires a peer of react@* but none is installed. You must install peer dependencies yourself.
npm WARN deprecated-react-native-listview@0.0.6 requires a peer of react-native@* but none is installed. You must install peer dependencies yourself.
npm WARN optimus No description
npm WARN optimus No repository field.
npm WARN optimus No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! realm@10.2.0 install: `node-pre-gyp install --fallback-to-build -j 8 ${npm_config_arch:+--target_arch=${npm_config_arch}}`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the realm@10.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-04T22_03_50_028Z-debug.log

```

**Comment by kraenhansen** [comment]
Thanks for reporting this. Unfortunately we don't support 64bit ARM on Linux at the moment.

**Comment by npatil-boosterfuels** [comment]
Thanks for the confirmation. is there any info on how to successfully use realm-32 module in 64 bit env? I could force npm to install 32 bit module via npm_config_arch=arm. But 'node' at runtime try to load arm64 realm module so was wondering if there is any way to force node to use arm.

**Comment by kneth** [comment]
@npatil-boosterfuels Just a guess: you will have to configure multiarch on your Linux system and install node.js as 32 bits. Mixing 32 and 64 bits is likely to fail.
