### ISSUE TITLE
Cannot read property 'indexOf' of undefined 

### ISSUE THREAD

**Issue by dodoto** [realm/realm-js#4221]
### How frequently does the bug occur?

All the time

### Description

I removed node_modules and reinstalled. And then launched the project. After window opened, I got the error. 

### Stacktrace & log output

```shell
Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at Function.getFileName (D:\oa-desktop\node_modules\bindings\bindings.js:178:16)
    at bindings (D:\oa-desktop\node_modules\bindings\bindings.js:82:48)
    at getRealmConstructor (D:\oa-desktop\node_modules\realm\lib\index.js:34:37)
    at Object.<anonymous> (D:\oa-desktop\node_modules\realm\lib\index.js:59:26)
    at Object.<anonymous> (D:\oa-desktop\node_modules\realm\lib\index.js:68:3)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
```

### Can you reproduce the bug?

Yes, always

### Version

10.11.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

window 10

### Build environment

electron 12.0.0
node 16.13.1
@vue/cli 4.5.13

**Comment by kneth** [comment]
@dodoto Can you share your code? Or even better, provide a small reproduction case?

Electron can be difficult to work it. Did you follow our [guide](https://docs.mongodb.com/realm/sdk/node/integrations/electron/)?

**Comment by dodoto** [comment]
Thanks for your reply. I git reset my code and reinstall, it works well now.
