### ISSUE TITLE
Objects() return [[Circular]]

### ISSUE THREAD

**Issue by mTondenier** [realm/realm-js#4324]
### How frequently does the bug occur?

All the time

### Description

When i query my data with the objects() method, ig gete a [[Circular]] object instead of a normal array.

It happen since i updated to the hermes version of realm 

### Stacktrace & log output

```shell
LOG [[Circular]]
 LOG  {"advice": null, "alias": "[]", "authorInstagram": null, "description": null, "difficulty": 5, "equipment": "[\"parallettes\",\"Pas d'equipement\"]", "functionnalGroups": "[\"Epaules\",\"flexibilité des poignets\",\"Long biceps\",\"Dentelés\",\"Biceps flexibility\"]", "id": "3c5d36e6-658e-4ac2-b19a-f169e6993143", "name": "Elevated Planche Lean", "tags": "upperbody/push/bodyweight/isometric/no_assist", "videoAuthor": null}
 WARN  Possible Unhandled Promise Rejection (id: 1):
RangeError: Maximum nesting level in JSON stringifyer exceeded
RangeError: Maximum nesting level in JSON stringifyer exceeded
    at stringify (native)
    at _callee6$ (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.sworkout.app&modulesOnly=false&runModule=true:190626:39)
    at call (native)
    at tryCatch (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.sworkout.app&modulesOnly=false&runModule=true:24344:23)
    at invoke (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.sworkout.app&modulesOnly=false&runModule=true:24514:32)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.sworkout.app&modulesOnly=false&runModule=true:24386:30)
    at call (native)
    at tryCatch (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.sworkout.app&modulesOnly=false&runModule=true:24344:23)
    at invoke (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.sworkout.app&modulesOnly=false&runModule=true:24416:30)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.sworkout.app&modulesOnly=false&runModule=true:24426:21)
    at tryCallOne (/tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.sworkout.app&modulesOnly=false&runModule=true:30383:26)
    at _callTimer (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.sworkout.app&modulesOnly=false&runModule=true:30279:17)
    at _callReactNativeMicrotasksPass (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.sworkout.app&modulesOnly=false&runModule=true:30318:17)
    at callReactNativeMicrotasks (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.sworkout.app&modulesOnly=false&runModule=true:30527:44)
    at __callReactNativeMicrotasks (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.sworkout.app&modulesOnly=false&runModule=true:22676:46)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.sworkout.app&modulesOnly=false&runModule=true:22455:45)
    at __guard (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.sworkout.app&modulesOnly=false&runModule=true:22659:15)
    at flushedQueue (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.sworkout.app&modulesOnly=false&runModule=true:22454:21)
    at invokeCallbackAndReturnFlushedQueue (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.sworkout.app&modulesOnly=false&runModule=true:22447:33)
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

1. Create a schema like that : 

```
export const ExerciseSchema = {
     name: EXERCISE_SCHEMA,
     primaryKey: 'id',
     properties: {
          id: 'string',
          name: 'string',
          tags: 'string',
          functionnalGroups: 'string',
          difficulty: 'int',
          equipment: 'string',
          advice: 'string?',
          alias: 'string?',
          description: 'string?',
          videoAuthor: 'string?',
          authorInstagram: 'string?',
     },
};
```

2.  Use realm.create to add multiple entries like this one (tags, functionnalGroups, alias and equipment are stored as string): 

`{
"identifier":"3c5d36e6-658e-48c2-b19a-f169e6993146",
"name":"Elevated Planche Lean",
"tags":"upperbody/push/bodyweight/isometric/no_assist",
"functionnalGroups":["Epaules","flexibilité des poignets","Long biceps","Dentelés","Biceps flexibility"],
"alias":[],
"equipment":["parallettes","Pas d'equipement"],
"difficulty":5
}`

3. Query all with the objects method and log them: 

```
const exerciseList = realm.objects(EXERCISE_SUMMARY_SCHEMA);
console.log(exerciseList);       //Return [[Circular]]
console.log(exerciseList[0]);
```

### Version

10.20.0-beta.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Android 11

### Build environment

React native 0.67.2
React 17.0.2

**Comment by tomduncalf** [comment]
Hey @mTondenier, thanks for creating a new issue for this one.

I updated my sample app to contain your schema and to create a bunch of objects matching what you specified, and also to match your React Native version, but I still see the correct log output: https://github.com/tomduncalf/issue-4324-hermes/commit/6e380658e5257420d3638a7236eac725b95b6c63

Are you testing on a real device or an emulator? I only have an Android emulator here right now, so I suppose it's possible there is some difference there.

If you could try out my [sample app](https://github.com/tomduncalf/issue-4324-hermes) and check whether you see the issue, that would be really helpful. If you do not see the issue with that, then we can try to work out what else is going on in your app to cause this.

**Comment by mTondenier** [comment]
> 

I tried with your sample app and it works as it should. It's strange because it happen only with this version of realm, I don't understand why 🤔.

**Comment by tomduncalf** [comment]
What else is happening in your app that might be interesting? Are you storing other data in Realm except for this one schema in question?

If you’d like to share your source code in private, I would be happy to take a look but of course understand that’s not always possible. 

If you can’t do that I’d suggest temporarily stripping your app down to the bare minimum - remove all other code and dependencies, so it is basically a blank React Native screen which inserts some data in Realm and logs it out, nothing else, no other dependencies or code which could be interfering with Realm. 

If this simple case does not exhibit the issue, then start adding in parts of your app again until you find where it breaks. 

If it does exhibit the issue, then hopefully that minimal repro case is generic enough that you can share it with me either on GitHub or in private, and we can take a look in more detail.

**Comment by takameyer** [comment]
Closing as we aren't able to reproduce.  If someone can provide a way to reproduce this, feel free to reopen and provide an example.
