### ISSUE TITLE
Realm Sync doesn't work with Jest testing framework

### ISSUE THREAD

**Issue by mongodben** [realm/realm-js#4352]
### How frequently does the bug occur?

All the time

### Description

when performing all operations involving Realm Sync, the Jest testing framework doesn't work. It always throws the error: 

```
    : Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error:
```

however, the same tests work using Jasmine testing framework. 

### Stacktrace & log output

```shell
FAIL   JavaScript  Examples/derp.js (6.53 s)
  ● open synced realm

    : Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error:

      3 |
      4 | const REALM_APP_ID = "sync_test-ytdqo";
    > 5 | it("open synced realm", async () => {
        | ^
      6 |   const Car = {
      7 |     name: "Car",
      8 |     properties: {

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Object.<anonymous> (Examples/derp.js:5:1)

A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks.
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

1. create a node project with realm, jest, and jasmine
paste the following code into a file:

```js
import Realm from "realm";

const REALM_APP_ID = "YOUR_APP_ID";
it("open synced realm", async () => {
  const Car = {
    name: "Car",
    properties: {
      _id: "objectId",
      make: "string",
      model: "string",
      miles: "int",
    },
    primaryKey: "_id",
  };

  const app = new Realm.App({ id: REALM_APP_ID });

  await app.logIn(new Realm.Credentials.anonymous());

  // :code-block-start: open-synced-realm-online-with-car-schema
  const config = {
    schema: [Car], // predefined schema
    sync: {
      user: app.currentUser, // already logged in user
      partitionValue: "myPartition",
    },
  };

  const realm = await Realm.open(config);

  realm.close();
  expect(realm.isClosed).toBe(true);
});

```

2. set up a realm baas with sync and anonymous users enabled
3. test with jasmine and test will pass
4. test with jest and you'll get the error noted in the stacktrace section above

### Version

10.13.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

MacOS 11.6.3

### Build environment

n/a

### Cocoapods version

n/a

**Comment by mongodben** [comment]
closed by https://github.com/realm/realm-js/issues/4380, which more specifically diagnoses the problem.
