### ISSUE TITLE
exception when opening a synced Realm on 10.13.0

### ISSUE THREAD

**Issue by akunal1** [realm/realm-js#4406]
### How frequently does the bug occur?

All the time

### Description

when I am trying to open the realm it is throwing exceptions because of empty login user.

code : 

// sync config 
```

import Realm from 'realm';
import { Task } from '../schemas/Task';
// Returns the shared instance of the Realm app.
export function getRealmApp() {
  const appId = 'application-x-xxxxx'; // id hidden
  const appConfig = {
    id: appId,
    timeout: 10000,
  };
  return new Realm.App(appConfig);
}

async function anonymousLogin() {
  let user;
  try {
    const app = await getRealmApp(); // pass in the appConfig variable that you created earlier
 
    const credentials = await Realm.Credentials.anonymous();
    console.log('credentials', credentials);  // ---> {}
    user = await app.logIn(credentials);
    console.log('user', user); // ---> {}
    return user;
  } catch (error) {
    throw `Error logging in anonymously: ${JSON.stringify(error, null, 2)}`;
  }
}

export async function openRealm() {
  let user;
  let realm;
  try {
    user = await anonymousLogin();
    console.log(`Logged in with the user: ${user.identity}`); // --> undefined
    const config = {
      schema: [Task.schema],
      sync: {
        user: user,
        partitionValue: 'myPartition',
      },
    };

    realm = await Realm.open(config);
    return realm;
  } catch (error) {
    throw `Error opening realm: ${JSON.stringify(error, null, 2)}`;
  }
}

```

// UI 
```

import React from 'react';
import { View, Text, Button } from 'react-native'; 
import { openRealm } from '../../DB/configurations/sync.utils';
import styles from './dashboard.styles';

const Dashboard = () => {
  const writeDB = async () => {
    const realm = await openRealm();
    realm.write(() => {
      realm.create('Task', {
        _id: '123',
        name: 'go grocery shopping',
        status: 'Open',
      });
    });
    const DB = realm.objects('Task');
    console.log('DB data', DB);
  };

  const readDB = async () => {
    console.log('DB data');
  };

  return (
    <View style={styles.dashboardContainer}>
      <Text>Hello World</Text>
      <Button title="write" onPress={() => writeDB()} />
      <Button title="Read" onPress={() => readDB()} />
    </View>
  );
};

export default Dashboard;

```

output : 

 **LOG**  credentials {}
 **LOG**  user {}
 **LOG**  Logged in with the user: undefined
 **WARN**  Possible Unhandled Promise Rejection (id: 1):
"Error opening realm: {
  \"message\": \"Operation Canceled\",
  \"errorCode\": 1
}"

### Can you reproduce the bug?

Yes, always

### Version

"realm": "^10.13.0"

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Android

### Build environment

Which debugger for React Native: ..

**Comment by c316** [comment]
I set this up in my app and I'm getting the message

```
--many debug messages here--
[3] Connection[1]: Negotiated protocol version: 3
[2] Connection[1]: Will emit a ping in 15939 milliseconds
[4] Connection[1]: Session[1]: Received: ERROR "Permission denied (BIND, REFRESH) - request logs URL: https://realm.mongodb.com/groups/xyz/apps/xyz/logs?co_id=xyz" (error_code=206, try_again=true)
[2] Connection[1]: Session[1]: Suspended
[2] Connection[1]: Session[1]: Will attempt to resume session after 1000 milliseconds
[2] Connection[1]: Session[1]: Sending: UNBIND
[2] Connection[1]: Session[1]: Initiating deactivation
[2] Connection[1]: Session[1]: Deactivation completed
[3] Connection[1]: Allowing reconnection in 337 milliseconds
[4] Connection[1]: Disconnected
```

I replaced the realm url and ID above with xyz, I wasn't sure if that was sensitive info or not. 

In my case I get this same error message as @akunal1 but I am already logged in. This error seems to happen anytime Realm attempts to connect and retrieve data. As far as I can tell everything is still working, I just see this error. 


```
Unhandled promise rejection, Object {
  "errorCode": 1,
  "message": "Operation canceled",
}
at node_modules/core-js/internals/host-report-errors.js:5:32 in module.exports
at http://192.168.50.50:8081/index.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:266541:138 in dispatchEvent
at node_modules/core-js/modules/es.promise.js:170:23 in perform$argument_0
at node_modules/core-js/internals/perform.js:3:20 in module.exports
at node_modules/core-js/modules/es.promise.js:167:22 in call$argument_2
```

**Comment by ianpward** [comment]
Looks like your permissions are invalid. How are your permissions configured?

**Comment by c316** [comment]
@ianpward development mode is on. I haven't gotten to the point of setting any rules. 

<img width="688" alt="image" src="https://user-images.githubusercontent.com/3142974/161279944-a5ae3b30-afb1-42f6-968a-3998fe3bf01c.png">

**Comment by c316** [comment]
@ianpward that did resolve this for me. Thank you
