### ISSUE TITLE
Cant run jest tests m1 mac node 16 or 17 - Can't create protected reference: napi_status 1

### ISSUE THREAD

**Issue by thomasarogers** [realm/realm-js#4451]
### How frequently does the bug occur?

All the time

### Description

Trying to run my react native projects jest tests and cannot run them without getting the errors below. Tried with terminal in both rosetta and normal environments and with both node v16 and node v17 both the same issue. Everything works fine when running on devices and the projects builds ok its just we are unable to run any tests.

### Stacktrace & log output

```shell
Error: Can't create protected reference: napi_status 1
        at openLocalRealm (/Users/thomas/workspace/Singletrack-Mobile/node_modules/realm/lib/extensions.js:35:33)
        at Function.open (/Users/thomas/workspace/Singletrack-Mobile/node_modules/realm/lib/extensions.js:168:18)
        at fn (/Users/thomas/workspace/Singletrack-Mobile/tests/setup/TestUser.js:25:19)
        at tryCallTwo (/Users/thomas/workspace/Singletrack-Mobile/node_modules/promise/lib/core.js:45:5)
        at doResolve (/Users/thomas/workspace/Singletrack-Mobile/node_modules/promise/lib/core.js:200:13)
        at new Promise (/Users/thomas/workspace/Singletrack-Mobile/node_modules/promise/lib/core.js:66:3)
        at TestUser.setupTestUser (/Users/thomas/workspace/Singletrack-Mobile/tests/setup/TestUser.js:24:16)
        at fn (/Users/thomas/workspace/Singletrack-Mobile/tests/ModelManager.test.js:100:17)
        at tryCallTwo (/Users/thomas/workspace/Singletrack-Mobile/node_modules/promise/lib/core.js:45:5)
        at doResolve (/Users/thomas/workspace/Singletrack-Mobile/node_modules/promise/lib/core.js:200:13)
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

1. Write a jest test on an m1 mac which accesses or creates a realm instance
2.  Try and run the test

File TestUser.js logs point to line 25 Realm.open causing the issue:
<img width="538" alt="image" src="https://user-images.githubusercontent.com/42372294/160575297-301fc813-3109-4ca8-abac-c03184b79c2f.png">

Logs also point to ModelManager.test.js line 100 which is calling the above method:
<img width="505" alt="image" src="https://user-images.githubusercontent.com/42372294/160575550-587c45c5-60dc-4a1a-ba47-96aed6fa0785.png">

Erros received when trying to run Jest tests:
<img width="817" alt="image" src="https://user-images.githubusercontent.com/42372294/160575665-fe179622-5d09-4c28-b77f-ef11ce8831d9.png">

### Version

10.7.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

mac OS Montherey

### Build environment

Which debugger for React Native: ..
System:
    OS: macOS 12.2.1
    CPU: (8) arm64 Apple M1
    Memory: 191.31 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.8.0 - ~/.nvm/versions/node/v17.8.0/bin/node
    npm: 8.5.5 - ~/.nvm/versions/node/v17.8.0/bin/npm
    Watchman: 2022.01.31.00 - /opt/homebrew/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
  IDEs:
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.4 => 0.61.4
  npmGlobalPackages:
    react-native-cli: 2.0.1

### Cocoapods version

1.11.2

**Comment by kraenhansen** [comment]
Reading our changelog we did make changes affecting Jest on both the 10.8.0 and 10.9.0 release of our library.
Is it possible for you to upgrade to the latest version and verify that the problem is still there?

**Comment by thomasarogers** [comment]
Sure will have a look now, thanks

**Comment by thomasarogers** [comment]
Just tried with both 10.8 and 10.9 getting the same issue 
<img width="839" alt="image" src="https://user-images.githubusercontent.com/42372294/160585097-70327a6e-3236-4f9e-bdc1-cbab4a8e5ec3.png">

**Comment by kraenhansen** [comment]
Googling this, it does seem that we have a bug that other users have hit too: https://www.mongodb.com/community/forums/t/realm-open-throws-error-cant-create-protected-reference/129547/7

**Comment by thomasarogers** [comment]
Thanks for getting back to me so quickly, I will keep an eye on future updates to see if it fixes it

**Comment by kraenhansen** [comment]
Thanks for reporting this. As a temporary workaround I suggest downgrading Node.js, but I agree we need to get this resolved.

**Comment by mandrewsan** [comment]
I am no longer seeing this error using 11.0.0-rc.1.

**Comment by kneth** [comment]
@mandrewsan Thank you for your update. 

@thomasarogers Is it possible for you to upgrade to v11.0.0-rc.1?
