### ISSUE TITLE
Native module RealmReactModule tried to override RealmReactModule for module name Realm

### ISSUE THREAD

**Issue by zhqchen** [realm/realm-js#471]
I use react-native 0.26.3 and realm 0.13.2,  but when I finish linking my project and run, I got this problem blow....why???

java.lang.IllegalStateException: Native module RealmReactModule tried to override RealmReactModule for module name Realm. If this was your intention, return true from RealmReactModule#canOverrideExistingModule()
            at com.facebook.react.bridge.NativeModuleRegistry$Builder.add(NativeModuleRegistry.java:213)
            at com.facebook.react.ReactInstanceManagerImpl.processPackage(ReactInstanceManagerImpl.java:898)
            at com.facebook.react.ReactInstanceManagerImpl.createReactContext(ReactInstanceManagerImpl.java:825)
            at com.facebook.react.ReactInstanceManagerImpl.access$700(ReactInstanceManagerImpl.java:102)
            at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:198)
            at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:181)
            at android.os.AsyncTask$2.call(AsyncTask.java:292)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by appden** [comment]
It looks like the `RealmReactPackage` was somehow included twice. Can you check that it only appears once in the `getPackages()` method inside `MainActivity.java`?

**Comment by zhqchen** [comment]
Oh...yes, you are right.  RealmReactPackage was included twice, It's my
fault. Thank you very much.

2016-06-06 17:15 GMT+08:00 Scott Kyle <notifications@github.com>:

**Comment by mattisx** [comment]
I'm getting this upgrading my project to RN 0.39 (npm install react-native@0.39 --save && react-native upgrade) and not doing any other changes.

**Comment by lalosh** [comment]
Thank you @appden and the reason for the duplication was because I executed `react-native link` in the process of adding a new font..I deleted the duplicated lines and it works fine..thanks

**Comment by jacksonkr** [comment]
I ran into a similar problem and ran `react-native unlink [module-name]` which fixed my issue.
