### ISSUE TITLE
ERR! stack Error: Failed to execute '/Users/tenna/.nvm/versions/node/v14.17.5/bin/node

### ISSUE THREAD

**Issue by ChurikiTenna** [realm/realm-js#4965]
### How frequently does the bug occur?

All the time

### Description

 % yarn install
ERR! stack Error: Failed to execute '/Users/tenna/.nvm/versions/node/v14.17.5/bin/node

### Stacktrace & log output

```shell
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/tenna/Downloads/aitem/node_modules/node-gyp/lib/build.js:201:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 21.6.0
gyp ERR! command "/Users/tenna/.nvm/versions/node/v14.17.5/bin/node" "/Users/tenna/Downloads/aitem/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/tenna/Downloads/aitem/node_modules/realm/compiled/node-v83_darwin_arm64/realm.node" "--module_name=realm" "--module_path=/Users/tenna/Downloads/aitem/node_modules/realm/compiled/node-v83_darwin_arm64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /Users/tenna/Downloads/aitem/node_modules/realm
gyp ERR! node -v v14.17.5
gyp ERR! node-gyp -v v9.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/tenna/.nvm/versions/node/v14.17.5/bin/node /Users/tenna/Downloads/aitem/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/tenna/Downloads/aitem/node_modules/realm/compiled/node-v83_darwin_arm64/realm.node --module_name=realm --module_path=/Users/tenna/Downloads/aitem/node_modules/realm/compiled/node-v83_darwin_arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/tenna/Downloads/aitem/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Darwin 21.6.0
node-pre-gyp ERR! command "/Users/tenna/.nvm/versions/node/v14.17.5/bin/node" "/Users/tenna/Downloads/aitem/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/tenna/Downloads/aitem/node_modules/realm
node-pre-gyp ERR! node -v v14.17.5
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/Users/tenna/.nvm/versions/node/v14.17.5/bin/node /Users/tenna/Downloads/aitem/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/tenna/Downloads/aitem/node_modules/realm/compiled/node-v83_darwin_arm64/realm.node --module_name=realm --module_path=/Users/tenna/Downloads/aitem/node_modules/realm/compiled/node-v83_darwin_arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
```

### Can you reproduce the bug?

Yes, always

### Version

2.25.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

MacOS

### Build environment

Which debugger for React Native: ..

**Comment by kneth** [comment]
Realm JS v2.25.0 was released in March 2019, and node.js version 14 was released a year later. Please consider to a recent version of Realm JS (v10.21.1 is currently the latest)
