### ISSUE TITLE
React Native TypeScript template is broken

### ISSUE THREAD

**Issue by channeladam** [realm/realm-js#5199]
### How frequently does the bug occur?

All the time

### Description

I followed the instructions to create a new project using the template. Ran it, tried to add a Task and the error happened. Also there are TypeScript errors out of the box.

Expected the template to have no TypeScript errors, and the app to run and save a task description when the + button is pressed.

This is my second attempt at trying to get Realm working... my previous attempt was to add it into my existing app, but the babel plugin doesn't seem to be executing to add a schema prop  to my Realm.Object class... so I though I'd try the template as a minimal example - and here I am, saddened by many problems.

### Stacktrace & log output

```shell
This is the error when pressing the + button:

 LOG  Running "AwesomeRealmProjectReact2" with {"rootTag":1}
 ERROR  Error: Exception in HostFunction: Property must be of type 'object_id', got (function _default() {
          return new (_$$_REQUIRE(_dependencyMap[6], "@realm/react").Realm.BSON.ObjectId)();
        })
Error: ENOENT: no such file or directory, open '/home/AwesomeRealmProjectReact2/http:/10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomerealmprojectreact2&modulesOnly=false&runModule=true'
    at Object.openSync (node:fs:590:3)
    at Object.readFileSync (node:fs:458:35)
    at getCodeFrame (/home/AwesomeRealmProjectReact2/node_modules/metro/src/Server.js:1028:18)
    at Server._symbolicate (/home/AwesomeRealmProjectReact2/node_modules/metro/src/Server.js:1101:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Server._processRequest (/home/AwesomeRealmProjectReact2/node_modules/metro/src/Server.js:458:7) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/AwesomeRealmProjectReact2/http:/10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomerealmprojectreact2&modulesOnly=false&runModule=true'
}


=================================================================

In addition to the runtime error above, when performing static analysis with TypeScript's "tsc", the following errors are given:


__tests__/App-test.tsx:7:17 - error TS2307: Cannot find module '../App' or its corresponding type declarations.

7 import App from '../App';
                  ~~~~~~~~

app/components/LoginScreen.tsx:61:11 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(props: TextInputProps | Readonly<TextInputProps>): TextInput', gave the following error.
    Type '{ style: { borderWidth: number; borderColor: string; padding: number; height: number; marginVertical: number; backgroundColor: string; borderRadius: number; } | { shadowColor: string; shadowOffset: { ...; }; ... 9 more ...; borderRadius: number; } | { ...; }; ... 6 more ...; placeholder: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<TextInput> & Readonly<TextInputProps> & Readonly<...>'.
      Property 'autoCompleteType' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<TextInput> & Readonly<TextInputProps> & Readonly<...>'. Did you mean 'autoComplete'?
  Overload 2 of 2, '(props: TextInputProps, context: any): TextInput', gave the following error.
    Type '{ style: { borderWidth: number; borderColor: string; padding: number; height: number; marginVertical: number; backgroundColor: string; borderRadius: number; } | { shadowColor: string; shadowOffset: { ...; }; ... 9 more ...; borderRadius: number; } | { ...; }; ... 6 more ...; placeholder: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<TextInput> & Readonly<TextInputProps> & Readonly<...>'.
      Property 'autoCompleteType' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<TextInput> & Readonly<TextInputProps> & Readonly<...>'. Did you mean 'autoComplete'?

61           autoCompleteType="email"
             ~~~~~~~~~~~~~~~~


app/components/LoginScreen.tsx:74:11 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(props: TextInputProps | Readonly<TextInputProps>): TextInput', gave the following error.
    Type '{ style: { borderWidth: number; borderColor: string; padding: number; height: number; marginVertical: number; backgroundColor: string; borderRadius: number; } | { shadowColor: string; shadowOffset: { ...; }; ... 9 more ...; borderRadius: number; } | { ...; }; ... 5 more ...; placeholder: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<TextInput> & Readonly<TextInputProps> & Readonly<...>'.
      Property 'autoCompleteType' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<TextInput> & Readonly<TextInputProps> & Readonly<...>'. Did you mean 'autoComplete'?
  Overload 2 of 2, '(props: TextInputProps, context: any): TextInput', gave the following error.
    Type '{ style: { borderWidth: number; borderColor: string; padding: number; height: number; marginVertical: number; backgroundColor: string; borderRadius: number; } | { shadowColor: string; shadowOffset: { ...; }; ... 9 more ...; borderRadius: number; } | { ...; }; ... 5 more ...; placeholder: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<TextInput> & Readonly<TextInputProps> & Readonly<...>'.
      Property 'autoCompleteType' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<TextInput> & Readonly<TextInputProps> & Readonly<...>'. Did you mean 'autoComplete'?

74           autoCompleteType="password"
             ~~~~~~~~~~~~~~~~


app/models/Task.ts:24:18 - error TS2345: Argument of type '{ description: string; userId: string; }' is not assignable to parameter of type 'Unmanaged<Task>'.
  Type '{ description: string; userId: string; }' is missing the following properties from type 'OmittedRealmTypes<Task>': _id, isComplete, createdAt

24     super(realm, {description, userId: userId || '_SYNC_DISABLED_'});
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 4 errors in 3 files.

Errors  Files
     1  __tests__/App-test.tsx:7
     2  app/components/LoginScreen.tsx:61
     1  app/models/Task.ts:24
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

1. Follow the steps to init and run the template at https://github.com/realm/realm-js/tree/master/templates/react-native-template-realm-ts#readme
I am running Android.
2. In the app (yes it starts), type any value into the text input and press the + button
3. Boom - error.

### Version

Same as template - ^11.0.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Android 11 R API 30 - Pixel 5 emulator

### Build environment

Which debugger for React Native: Flipper

### Cocoapods version

NA

**Comment by channeladam** [comment]
Same runtime error when pressing the + button happens with the JS template as well.
https://github.com/realm/realm-js/tree/master/templates/react-native-template-realm-js

**Comment by takameyer** [comment]
@channeladam Great catch.  Our templates are generated from our `example` directory and it appears the `package.json` was overlooked.
To fix the issue you are having, and possibly other issues, please make the following updates:
```
    "@realm/react": "^0.4.1"
    "realm": "^11.3.1"
    "@realm/babel-plugin": "^0.1.1"
```

Thanks for trying realm out.  I'll get an update to the templates out ASAP.

**Comment by takameyer** [comment]
To address your comment:

> the babel plugin doesn't seem to be executing to add a schema prop to my Realm.Object class

The babel plugin replaces the need to create a static schema property on your class.  This allows you to use the properties of your class as the single source of truth.  We find this to be an improvement as it removes duplicate code and the potential for your types and schema to be out of sync.  

This is entirely optional, so if you want to define a schema yourself, feel free to remove the `babel-plugin` and go about it the old way.  We would, however, appreciate any feedback on any limitations you are hitting with the `babel-plugin`.

**Comment by takameyer** [comment]
Version 0.4.2 of the templates have been published.  I'm closing this issue.  If you are still experiencing the issue feel free to reopen.
