### ISSUE TITLE
Realm with react native not working (expo)

### ISSUE THREAD

**Issue by cyril36** [realm/realm-js#5430]
### How frequently does the bug occur?

Always

### Description

Hello,
I am trying to use Realm in my react-native application using expo.
I have installed the following package : 
```
npm install realm
npm install @realm/react
```
 Also followed the explanation from https://www.mongodb.com/developer/products/realm/using-expo-realm-expo-dev-client/

I have cloned the repository https://github.com/mongodb-developer/read-it-later-maybe and tried to launch the android app but it always crashed.

What can i do to fix this issue and make realm compatible with react-native and expo ?
Is it a version issue?(the documentation asks for Node 12 or higher)
If the version is the issue, which version should i use?

Additional information about my versions: 
Node : v18.12.1
expo-cli : 6.3.0
"@realm/react": "^0.4.3",
"expo": "~47.0.12",
"expo-dev-client": "~2.0.1",
"metro-core": "^0.75.0",
"react": "18.1.0",
"react-native": "0.70.5",
"realm": "^11.4.0",

### Stacktrace & log output

```shell
NODE_OPTIONS=--openssl-legacy-provider expo start --web
WARNING: The legacy expo-cli does not support Node +17. Migrate to the versioned Expo CLI (npx expo).

This command is being executed with the global Expo CLI. Learn more.
To use the local CLI instead (recommended in SDK 46 and higher), run:
› npx expo start

Starting project at /home/cyril/Adoption/ReactRealmJSTemplateApp
Starting Metro Bundler
Starting Webpack on port 19006 in development mode.
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █▀█ █▄█▀▀ ▄▀▄▀█ ▄▄▄▄▄ █
█ █   █ █▀▀▀█ ▀▀ █▀▀█▀█ █   █ █
█ █▄▄▄█ █▀ █▀▀▄█▀ █▀▄██ █▄▄▄█ █
█▄▄▄▄▄▄▄█▄▀ ▀▄█ █ █ ▀▄█▄▄▄▄▄▄▄█
█▄▄▄  █▄▄▄▄▀▄▀ ▄█▀▄▄ ▄▄▀▄▀▄█▄▀█
█▄▄▀█ █▄█▀█▄█▀▄▄ ▀█ █▄▀▀▄ ██▀██
█ ▀█▄█ ▄▀▀▄▄█▄▄▄█▀▄▄ ▄▄▀▄▀▄ █▀█
█ ▄▀▄  ▄▀ ██ ▄▄ ▄ █ ▀▄ ▄▀██▄▀██
█ █▀█ █▄▀▀▀ ▄▀▀███  ▀▄ ▀█▀▀ █▀█
█ █  ▀ ▄▀█▄██▀ ▄▄ ▄██▄▀ █▀▄▄▀██
█▄█▄▄▄█▄█▀█▀█▄█▄█▀▀█▀ ▄▄▄ ▀   █
█ ▄▄▄▄▄ █▄ █ ▄█▀ █▄█▄ █▄█ ▄▄▀██
█ █   █ █ ██▄▀▀▀▄ ▄▀█  ▄ ▄▄▄  █
█ █▄▄▄█ █  ██▀ ▄ ███▄ ▀▄▀ ▄█ ██
█▄▄▄▄▄▄▄█▄▄▄█▄█▄█▄▄███████▄▄███

› Metro waiting on exp://192.168.1.139:19000
› Scan the QR code above with Expo Go (Android) or the Camera app (iOS)

› Webpack waiting on http://192.168.1.139:19006
› Expo Webpack (web) is in beta, and subject to breaking changes!

› Press a │ open Android
› Press w │ open web

› Press r │ reload app
› Press m │ toggle menu

› Press ? │ show all commands

Logs for your project will appear below. Press Ctrl+C to exit.
[object Object]
[object Object]
[object Object]
WARNING in ./node_modules/@realm/react/dist/AppProvider.js
Module Warning (from ../../.nvm/versions/node/v18.12.1/lib/node_modules/expo-cli/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/cyril/Adoption/ReactRealmJSTemplateApp/node_modules/@realm/react/src/AppProvider.tsx' file: Error: ENOENT: no such file or directory, open '/home/cyril/Adoption/ReactRealmJSTemplateApp/node_modules/@realm/react/src/AppProvider.tsx'

WARNING in ./node_modules/@realm/react/dist/RealmProvider.js
Module Warning (from ../../.nvm/versions/node/v18.12.1/lib/node_modules/expo-cli/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/cyril/Adoption/ReactRealmJSTemplateApp/node_modules/@realm/react/src/RealmProvider.tsx' file: Error: ENOENT: no such file or directory, open '/home/cyril/Adoption/ReactRealmJSTemplateApp/node_modules/@realm/react/src/RealmProvider.tsx'

WARNING in ./node_modules/@realm/react/dist/UserProvider.js
Module Warning (from ../../.nvm/versions/node/v18.12.1/lib/node_modules/expo-cli/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/cyril/Adoption/ReactRealmJSTemplateApp/node_modules/@realm/react/src/UserProvider.tsx' file: Error: ENOENT: no such file or directory, open '/home/cyril/Adoption/ReactRealmJSTemplateApp/node_modules/@realm/react/src/UserProvider.tsx'

WARNING in ./node_modules/@realm/react/dist/cachedCollection.js
Module Warning (from ../../.nvm/versions/node/v18.12.1/lib/node_modules/expo-cli/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/cyril/Adoption/ReactRealmJSTemplateApp/node_modules/@realm/react/src/cachedCollection.ts' file: Error: ENOENT: no such file or directory, open '/home/cyril/Adoption/ReactRealmJSTemplateApp/node_modules/@realm/react/src/cachedCollection.ts'

WARNING in ./node_modules/@realm/react/dist/cachedObject.js
Module Warning (from ../../.nvm/versions/node/v18.12.1/lib/node_modules/expo-cli/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/cyril/Adoption/ReactRealmJSTemplateApp/node_modules/@realm/react/src/cachedObject.ts' file: Error: ENOENT: no such file or directory, open '/home/cyril/Adoption/ReactRealmJSTemplateApp/node_modules/@realm/react/src/cachedObject.ts'

WARNING in ./node_modules/@realm/react/dist/index.js
Module Warning (from ../../.nvm/versions/node/v18.12.1/lib/node_modules/expo-cli/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/cyril/Adoption/ReactRealmJSTemplateApp/node_modules/@realm/react/src/index.tsx' file: Error: ENOENT: no such file or directory, open '/home/cyril/Adoption/ReactRealmJSTemplateApp/node_modules/@realm/react/src/index.tsx'

WARNING in ./node_modules/@realm/react/dist/useObject.js
Module Warning (from ../../.nvm/versions/node/v18.12.1/lib/node_modules/expo-cli/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/cyril/Adoption/ReactRealmJSTemplateApp/node_modules/@realm/react/src/useObject.tsx' file: Error: ENOENT: no such file or directory, open '/home/cyril/Adoption/ReactRealmJSTemplateApp/node_modules/@realm/react/src/useObject.tsx'

WARNING in ./node_modules/@realm/react/dist/useQuery.js
Module Warning (from ../../.nvm/versions/node/v18.12.1/lib/node_modules/expo-cli/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/cyril/Adoption/ReactRealmJSTemplateApp/node_modules/@realm/react/src/useQuery.tsx' file: Error: ENOENT: no such file or directory, open '/home/cyril/Adoption/ReactRealmJSTemplateApp/node_modules/@realm/react/src/useQuery.tsx'

WARNING in ./node_modules/@realm/react/dist/useRealm.js
Module Warning (from ../../.nvm/versions/node/v18.12.1/lib/node_modules/expo-cli/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/cyril/Adoption/ReactRealmJSTemplateApp/node_modules/@realm/react/src/useRealm.tsx' file: Error: ENOENT: no such file or directory, open '/home/cyril/Adoption/ReactRealmJSTemplateApp/node_modules/@realm/react/src/useRealm.tsx'

ERROR in ./node_modules/bindings/bindings.js:5
Module not found: Can't resolve 'fs'
  3 |  */
  4 | 
> 5 | var fs = require('fs'),
  6 |   path = require('path'),
  7 |   fileURLToPath = require('file-uri-to-path'),
  8 |   join = path.join,

ERROR in ./node_modules/bindings/bindings.js:6
Module not found: Can't resolve 'path'
  4 | 
  5 | var fs = require('fs'),
> 6 |   path = require('path'),
  7 |   fileURLToPath = require('file-uri-to-path'),
  8 |   join = path.join,
  9 |   dirname = path.dirname,

ERROR in ./node_modules/file-uri-to-path/index.js:6
Module not found: Can't resolve 'path'
  4 |  */
  5 | 
> 6 | var sep = require('path').sep || '/';
  7 | 
  8 | /**
  9 |  * Module exports.

web compiled with 3 errors and 9 warnings
Started Metro Bundler
```
```


### Can you reproduce the bug?

Always

### Reproduction Steps

1) Install expo-cli and node
2) Clone the repository https://github.com/mongodb-developer/read-it-later-maybe 
3) npx expo start
4) app crashes

### Version

"realm": "^11.4.0", and "@realm/react": "^0.4.3",

### What services are you using?

Atlas App Services: Functions or GraphQL or DataAPI etc

### Are you using encryption?

No

### Platform OS and version(s)

Ubuntu 22.04.1 LTS

### Build environment

"react-native": "0.70.5",


### Cocoapods version

_No response_

**Comment by cyril36** [comment]
Hello,
After updating the realm package to 11.0.0, 
then executed yarn android , i get the following error at compiling : 

```
> Configure project :expo-manifests
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-modules-core
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Script '/home/cyril/Adoption/ReactRealmJSTemplateApp/node_modules/expo-modules-autolinking/scripts/android/autolinking_implementation.gradle' line: 272

* What went wrong:
A problem occurred evaluating project ':expo'.
> A problem occurred configuring project ':expo-modules-core'.
   > Failed to notify project evaluation listener.
      > SDK location not found. Define a valid SDK location with an ANDROID_HOME environment variable or by setting the sdk.dir path in your project's local properties file at '/home/cyril/Adoption/ReactRealmJSTemplateApp/android/local.properties'.
      > Could not get unknown property 'release' for SoftwareComponentInternal set of type org.gradle.api.internal.component.DefaultSoftwareComponentContainer.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':expo'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 10s
5 actionable tasks: 4 executed, 1 from cache
Error: /home/cyril/Adoption/ReactRealmJSTemplateApp/android/gradlew exited with non-zero code: 1
Error: /home/cyril/Adoption/ReactRealmJSTemplateApp/android/gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/home/cyril/Adoption/ReactRealmJSTemplateApp/node_modules/@expo/cli/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
    ...
    at Object.spawnAsync [as default] (/home/cyril/Adoption/ReactRealmJSTemplateApp/node_modules/@expo/cli/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at spawnGradleAsync (/home/cyril/Adoption/ReactRealmJSTemplateApp/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:72:46)
    at Object.assembleAsync (/home/cyril/Adoption/ReactRealmJSTemplateApp/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:52:18)
    at runAndroidAsync (/home/cyril/Adoption/ReactRealmJSTemplateApp/node_modules/@expo/cli/build/src/run/android/runAndroidAsync.js:31:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

Any idea why?

**Comment by cyril36** [comment]
I have succeed to partially compile it by adding the line : 
`dir.sdk = /home/my-path-to-Android-sdk/Android/Sdk` in the file `/myapp-path/android/local.properties`

Once the application is launching i gest the following error :
```
Android Bundling complete 4067ms
 ERROR  Error: Exception in HostObject::get(propName:Realm): java.lang.UnsatisfiedLinkError: couldn't find DSO to load: librealm.so caused by: dlopen failed: cannot locate symbol "__emutls_get_address" referenced by "/data/app/~~Yavi_7DHFIzBRYE-1lEGxQ==/com.cyril.moreau.adopt-P_cKswbdcbzZ4wtTd6vptw==/lib/x86/librealm.so"... result: 0
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
```

**Comment by riebel** [comment]
the following package.json is working for me (Expo SDK 48 beta):

```
{
  "name": "beta48",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@realm/react": "^0.4.3",
    "expo": "~48.0.0-beta.2",
    "expo-dev-client": "~2.1.1",
    "expo-splash-screen": "~0.18.1",
    "expo-status-bar": "~1.4.4",
    "react": "18.2.0",
    "react-native": "0.71.2",
    "react-native-get-random-values": "^1.8.0",
    "realm": "^11.4.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}
```

**Comment by takameyer** [comment]
`realm@11.4.0` is only compatible with `expo@48` and `react-native@0.71`.  You will have to either downgrade `realm` or upgrade `expo`.

**Comment by cyril36** [comment]
Hello,
Thank you for compatibility chart, it is very useful.
It works perfect for a simple project like https://github.com/mongodb-developer/read-it-later-maybe
But when i try with my own project, there are a lot more dependencies, and it is very hard to get everything working all together. 
I have tried the different versions present in the compatibility chart and all of them gives me the following error : 
```
A problem occurred evaluating project ':expo-dev-menu'.
> No matching aar for react-native-reanimated found. Upgrade react-native to 0.71.x or later in order to use the expo-dev-menu package.
```

Fortunately the latest version works for me 
Realm JavaScript | React Native | Expo | Hermes | npm | node
-- | -- | -- | -- | -- | --
11.4.0 | >= 0.71.0 | 48 |   | >= 7 | >= 13


However, i had to add the following file : 
`dir.sdk = /home/my-path-to-Android-sdk/Android/Sdk` in the file `/myapp-path/android/local.properties`

Also those versions work for prebuild app and i am able to execute it over an android emulator.

But when i try to publish using the development profile to use it on my own android phone such as :
`eas build --profile development --platform android` 
I get the following error : 
![1b850797-2451-4f44-af3c-45307a75e615](https://user-images.githubusercontent.com/16116562/219045083-278f9845-9165-4598-ba63-df55a85e2026.jpg)

However it works when i publish it using the preview profile such as : 
`eas build --profile preview --platform android`
 
Have you already seen the error on the picture?

**Comment by takameyer** [comment]
@cyril36 I haven't seen that yet.  Can you verify if this is a problem with `realm`?  Just want to rule out it isn't an issue with the Expo Beta.
The other possibility would be to use Expo 47 and Realm 11.3.1 and see if it works there.

**Comment by cyril36** [comment]
I have tried Expo 47 and Realm 11.3.1 and it does not work. I have the following error : 
```
A problem occurred evaluating project ':expo-dev-menu'.
> No matching aar for react-native-reanimated found. Upgrade react-native to 0.71.x or later in order to use the expo-dev-menu package.
```

I am currently using Expo 48 and Realm 11.4.0. I am already checking in Expo issues to find a solution

**Comment by takameyer** [comment]
@cyril36 Did you only downgrade the `expo` dependency?  If so you might also need to run `npx expo install --fix` to align any of expo's codpendencies.

**Comment by cyril36** [comment]
For the issue of string cannot be converted to JSONObject, I have created a new project using `npx create-expo-app AwesomeProject`
and then copy my code to this project and it worked.

I think the issue was because of the different installation i have done during the creation of my project :
First i have create the project with : 
```
$ npm i -g create-react-native-app
$ create-react-native-app my-project
```
and then include expo then upgrade it and make changes and so on and so artifact configuration may i mess up the process.

For me the solution was to create a new project using `npx create-expo-app `

I was not able to reproduce yet... but i will take a look later and open a ticket to expo project 

I hope this will help other people.

Thank you for your help

**Comment by Ovodo** [comment]
Hello, I am having a similar issue, everything works fine until I scan the QR code and my app doesn't open up in my expo go app. and I get no errors from my console. Kindly help me out. I am using this template  "npx expo-cli init ReactRealmJSTemplateApp -t @realm/expo-template-js". Thank you
