### ISSUE TITLE
Realm library doesn't work with Electron React Boilerplate

### ISSUE THREAD

**Issue by nguyen-tam** [realm/realm-js#5516]
### How frequently does the bug occur?

Always

### Description

Realm library doesn't work with Electron React Boilerplate. It throws this error "Module not found: Error: Can't resolve 'react-native' in './node_modules/realm/lib'"

### Stacktrace & log output

```shell
Uncaught Error: Unexpected execution environment (chromedebugger)
    at ./node_modules/realm/lib/index.js (index.js:23:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/renderer/dataAccess/test.ts (stackframe.js:143:2)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/renderer/sagas/sagas.ts (index.ts:10:2)
    at options.factory (react refresh:6:1)

WARNING in ./node_modules/realm/lib/utils.js 22:9-31

Critical dependency: the request of a dependency is an expression


WARNING in ./node_modules/realm/lib/utils.js 159:29-52

Module not found: Error: Can't resolve 'react-native' in './node_modules/realm/lib'
Did you mean './react-native'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories (/DIRECTORY/src, node_modules).
If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.
```

### Can you reproduce the bug?

Always

### Version

11.5.1

### What services are you using?

Atlas Device Sync

### Are you using encryption?

No

### Platform OS and version(s)

MacOS 12.6.2

### Build environment

Which debugger for React Native: ..
Electron

**Comment by kneth** [comment]
@nguyen-tam Thank you for reporting. We are aware that it might be non-trivial to get Realm, Electron, and React to work together.  We would to be able to provide a better experience at some point, for example to make `@realm/react` less React Native centric.

For now, the [Quick Start with Electron](https://www.mongodb.com/docs/realm/sdk/node/integrations/electron-cra/) is the best source of information.

**Comment by nguyen-tam** [comment]
> Quick Start with Electron

Thanks for your reply. I read that doc many times, but now my whole app is based on Electron React Boilerplate (ERB), then if I want to add Realm, I'll need to switch from ERB to Create React App, while ERB is much popular than CRA + Electron.

In the meantime, can you please update the [Quick Start with Electron](https://www.mongodb.com/docs/realm/sdk/node/integrations/electron-cra/) with ERB integration?
