### ISSUE TITLE
Electron - Could not locate the bindings file

### ISSUE THREAD

**Issue by rossicler-hostalky** [realm/realm-js#5618]
### How frequently does the bug occur?

Always

## Expected:
Initialize realm app and login with user (electron renderer process)

## What actually happened
Got an error when initializing the app

### Stacktrace & log output

```shell
Uncaught Error: Could not locate the bindings file. Tried:
→ /myproject/build/realm.node
→ /myproject/build/Debug/realm.node
→ /myproject/build/Release/realm.node
→ /myproject/out/Debug/realm.node
→ /myproject/Debug/realm.node
→ /myproject/out/Release/realm.node
→ /myproject/Release/realm.node
→ /myproject/build/default/realm.node
→ /myproject/compiled/16.14.2/darwin/x64/realm.node
→ /myproject/addon-build/release/install-root/realm.node
→ /myproject/addon-build/debug/install-root/realm.node
→ /myproject/addon-build/default/install-root/realm.node
→ /myproject/lib/binding/node-v106-darwin-x64/realm.node
at bindings (bindings.js:126:1)
at ./node_modules/realm/lib/index.js (index.js:26:1)
at __webpack_require__ (bootstrap:24:1)
at fn (hot module replacement:62:1)
at ./src/pages/Login.tsx (Home.tsx:19:1)
at __webpack_require__ (bootstrap:24:1)
at fn (hot module replacement:62:1)
at ./src/Routes.tsx (App.tsx:29:1)
at __webpack_require__ (bootstrap:24:1)
at fn (hot module replacement:62:1)
```

### Can you reproduce the bug?

Always

### Reproduction Steps

I'm using Electron + React with webpack and craco. Below is some of the configuration files that might be useful.

## craco.config.js
```
const nodeExternals = require("webpack-node-externals");

module.exports = {
  webpack: {
    configure: {
      target: "electron-renderer",
      externals: [
        nodeExternals({
          allowlist: [/webpack(\/.*)?/, "electron-devtools-installer"],
        }),
      ],
    },
  },
  ...
};
```

## webpack.dev.config.js

```
const webpack = require("webpack");
const path = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const { spawn } = require("child_process");

// Any directories you will be adding code/files into, need to be added to this array so webpack will pick them up
const defaultInclude = path.resolve(__dirname, "src");

module.exports = {
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        use: [{ loader: "babel-loader" }],
        include: defaultInclude,
      },
      {
        test: /\.ts?$/,
        use: [{ loader: "babel-loader" }, { loader: "ts-loader" }],
        include: defaultInclude,
      },
      {
        test: /\.tsx?$/,
        use: [{ loader: "babel-loader" }, { loader: "ts-loader" }],
        include: defaultInclude,
      },
      ... (some more css, image related config)
    ],
  },
  entry: "./src/index.tsx",
  // tell Webpack to load TypeScript files
  resolve: {
    // Look for modules in .ts(x) files first, then .js
    extensions: [".js", "jsx", ".ts", ".tsx"],

    alias: {
      ... (some more alias)
      "@realmDb": path.resolve(__dirname, "src/realm-db"),
    },
  },
  target: "electron-renderer",
  plugins: [
    new HtmlWebpackPlugin(),
    new webpack.DefinePlugin({
      "process.env.NODE_ENV": JSON.stringify("development"),
    }),
  ],
  devtool: "cheap-source-map",
  devServer: {
    contentBase: path.resolve(__dirname, "dist"),
    stats: {
      colors: true,
      chunks: false,
      children: false,
    },
    before() {
      spawn("electron", ["."], {
        shell: true,
        env: process.env,
        stdio: "inherit",
      })
        .on("close", (code) => process.exit(0))
        .on("error", (spawnError) => console.error(spawnError));
    },
  },
};
```

For the main process, I'm creating a window with nodeIntegration set to true and contextIsolation to false, so get started with Realm and other libraries that may require nodeIntegration. Sample code:

```
mainWindow = new BrowserWindow({
    ...
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
    },
  });
```

## Login.tsx

```
import Realm from "realm";

const Login = () => {
    useEffect(() => {
        const REALM_ID = "my-realmid";
        const appConfig = { id: REALM_ID };
        const app = new Realm.App(appConfig);
        // I don't even need to remove the comment from the below code, the error is already raised by the code above
        // const credentials = Realm.Credentials.emailPassword(username, password);
        // user = await app.logIn(credentials);      
    })

   return <div>Test</div>
}
```

### Version

^11.5.2

### What services are you using?

Atlas Device Sync

### Are you using encryption?

No

### Platform OS and version(s)

macOS Monterey 12.6

**Comment by kneth** [comment]
@rossicler-hostalky You might need https://webpack.js.org/loaders/node-loader/ or do as we do in Realm Studio: https://github.com/realm/realm-studio/blob/channel/major-13/configs/webpack.test.js#L28-L31

**Comment by rossicler-hostalky** [comment]
> @rossicler-hostalky You might need https://webpack.js.org/loaders/node-loader/ or do as we do in Realm Studio: https://github.com/realm/realm-studio/blob/channel/major-13/configs/webpack.test.js#L28-L31

I tried both, but couldn't get it working. I might be doing something wrong, I'll send here what I did exactly.

## Adding node-loader to webpack

`yarn add -D node-loader`

After installing I added this to the webpack config file:
```
...
rules: [
    ...,
    {
        test: /\.node$/,
        use: [{ loader: "node-loader" }],
    },
],
target: "electron-renderer",
node: {
    __dirname: false,
}
...
```

After this I ran the app again and got the same error as before.

## Trying to replicate Realm Studio

For this one I'm not really sure if I need to do anything else, but I just added the highlighted  code you sent me. So I added this to my webpack config file:
```
node: {
      // This will make __dirname equal the actual file
      __dirname: true,
    },
```

Thanks for the help, I'm somewhat new to electron, so I'm not really sure how to setup this correctly

**Comment by rossicler-hostalky** [comment]
I was able to fix the issue by adding these to my webpack config:
```
externals: [
    nodeExternals({
      // Anyting related to webpack, we want to keep in the bundle
      allowlist: [/webpack(\/.*)?/, "electron-devtools-installer"],
    }),
  ],
```

Now I got some error with @realm/react, but I'll open a new issue for that, since it isn't related to this one.

**Comment by kneth** [comment]
@rossicler-hostalky 

> I was able to fix the issue

Great to hear.

> Now I got some error with @realm/react

Currently `@realm/react` only support React Native but we are considering generalising the library to support React.

**Comment by rossicler-hostalky** [comment]
> 

I see, that would be really good, thanks for letting me know

**Comment by alishefaee** [comment]
This is my package.json file:
```
{
  "name": "waste-management",
  "private": true,
  "version": "0.0.0",
  "description": "Primary Waste Management",
  "main": "electron/main.js",
  "author": {
    "name": "ali shefaee",
    "email": "shafaprince2020@gmail.com"
  },
  "scripts": {
    "electron:dev": "electron .",
    "electron:build": "electron-builder"
  },
  "build": {
    "appId": "com.electron.wastemanagement",
    "productName": "WasteManagement",
    "afterPack": "./utils/removeLocales.js",
    "extraResources": [
      {
        "from": "./resources/",
        "to": "resources",
        "filter": [
          "**/*"
        ]
      }
    ],
    "win": {
      "target": [
        "nsis"
      ],
      "icon": "./icon/logo.png"
    },
    "nsis": {
      "oneClick": false,
      "createDesktopShortcut": true,
      "perMachine": true
    }
  },
  "dependencies": {
    "app-root-path": "^3.0.0",
    "bcryptjs": "^2.4.3",
    "body-parser": "^1.19.1",
    "connect-history-api-fallback": "^2.0.0",
    "cookie-parser": "~1.4.4",
    "cors": "^2.8.5",
    "cross-env": "^7.0.3",
    "dayjs": "^1.11.7",
    "dotenv": "^14.2.0",
    "electron-log": "^4.4.8",
    "electron-root-path": "^1.1.0",
    "express": "~4.16.1",
    "express-fileupload": "^1.2.1",
    "express-http-context": "^1.2.4",
    "fastest-validator": "^1.15.0",
    "form-data": "^4.0.0",
    "jsmodbus": "^4.0.6",
    "jsonwebtoken": "^8.5.1",
    "morgan": "~1.9.1",
    "node-schedule": "^2.1.0",
    "nodemailer": "^6.7.2",
    "open": "^8.4.0",
    "realm": "^11.9.0",
    "winston": "^3.8.2",
    "winston-daily-rotate-file": "^4.7.1",
    "write-excel-file": "^1.4.15"
  },
  "devDependencies": {
    "electron": "^22.0.1",
    "electron-builder": "^23.6.0",
    "http-server": "^0.10.0"
  }
}
```
and this is error that I got:
![Screenshot 2023-05-28 141934](https://github.com/realm/realm-js/assets/47412484/988d61c4-a8d2-4f91-a304-dc764e6947af)
I'm not using react or react-native or webpack. and in development it is working fine after packaging and installing it does not work.

**Comment by alishefaee** [comment]
I used `pnpm` to `yarn` and the problem got away. I think the way `pnpm` manages modules and cache caused this error.
