### ISSUE TITLE
Cannot access `Realm.OpenRealmTimeOutBehavior.OpenLocalRealm` enum

### ISSUE THREAD

**Issue by mongodben** [realm/realm-js#5627]
### How frequently does the bug occur?

Always

### Description

when using `Realm.OpenRealmTimeOutBehavior.OpenLocalRealm` enum in TS code, i get the error: `    TypeError: Cannot read properties of undefined (reading 'OpenLocalRealm')`

i believe this issue relates to https://github.com/realm/realm-js/issues/5480

### Stacktrace & log output

```shell
this code: example usage: https://github.com/mongodb/docs-realm/blob/bbfd4b498d5645b4fb58f61f06cb9a2958e2aa1f/examples/react-native/__tests__/ts/realm-database/configure-realm-sync-timeout.test.tsx#L36

produces this output: 


 FAIL  __tests__/ts/realm-database/configure-realm-sync-timeout.test.tsx
  ● Instantiate AppWrapperTimeoutSync and test sync

    TypeError: Cannot read properties of undefined (reading 'OpenLocalRealm')

      34 |   const realmAccessBehavior: Realm.OpenRealmBehaviorConfiguration = {
      35 |     type: Realm.OpenRealmBehaviorType.DownloadBeforeOpen,
    > 36 |     timeOutBehavior: Realm.OpenRealmTimeOutBehavior.OpenLocalRealm,
         |                                                     ^
      37 |     timeOut: 1000,
      38 |   };
      39 |

      at OpenLocalRealm (__tests__/ts/realm-database/configure-realm-sync-timeout.test.tsx:36:53)
      at renderWithHooks (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6256:18)
      at mountIndeterminateComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10702:13)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12151:16)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15801:12)
      at workLoopSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15735:5)
      at renderRootSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15707:7)
      at performSyncWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15412:20)
      at flushSyncCallbacks (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2594:22)
      at flushActQueue (node_modules/react/cjs/react.development.js:2665:24)
```
```


### Can you reproduce the bug?

-- select --

### Reproduction Steps

running this file in the realm-docs unit testing suite https://github.com/mongodb/docs-realm/blob/bbfd4b498d5645b4fb58f61f06cb9a2958e2aa1f/examples/react-native/__tests__/ts/realm-database/configure-realm-sync-timeout.test.tsx

### Version

11.5.2

### What services are you using?

Atlas Device Sync

### Are you using encryption?

No

### Platform OS and version(s)

MacOS 11.6.3

### Build environment

n/a

### Cocoapods version

_No response_

**Comment by kneth** [comment]
@mongodben Thank you for reporting

**Comment by kneth** [comment]
@mongodben Oh, I believe it should be `timeOutBehavior: Realm.OpenRealmTimeOutBehavior.openLocalRealm` (notice the non-capital `o`)

**Comment by tamnguy** [comment]
I don't see OpenRealmTimeOutBehavior inside extensions.js But I do see 

realmConstructor.OpenRealmBehaviorType = {
      DownloadBeforeOpen: "downloadBeforeOpen",
      OpenImmediately: "openImmediately",
    };

I'm assuming the below is missing?


realmConstructor.OpenRealmTimeOutBehavior = {
      DownloadBeforeOpen: "downloadBeforeOpen",
      OpenImmediately: "openImmediately",
    };

openLocalRealm is the value but OpenLocalRealm is the property name for OpenRealmTimeOutBehavior

**Comment by kneth** [comment]
It should be fixed by v12 but if it is still observed, please create a new issue.
