### ISSUE TITLE
Crash react native app when split apk

### ISSUE THREAD

**Issue by DeepzUa** [realm/realm-js#5735]
### How frequently does the bug occur?

Always

### Description

When set def enableSeparateBuildPerCPUArchitecture = true application crash, but if not spit work is fine

React native version: 0.71.6

### Stacktrace & log output

```shell
04-14 21:19:54.506  1182  1304 I SDM     : HWCDisplayBuiltIn::GetOptimalRefreshRate: active_refresh_rate_: 60
04-14 21:19:54.508  9612  9639 V SoLoader: librealm.so not found on /data/data/com.vocx/lib-main
04-14 21:19:54.508  9612  9639 D SoLoader: librealm.so found on /data/app/~~WxkKq2SBeCoqAJ-IA_z3Ng==/com.vocx-wwIniKC7zjUdKjnMsJkaCw==/lib/arm64
04-14 21:19:54.508  9612  9639 D SoLoader: Not resolving dependencies for librealm.so
04-14 21:19:54.512  9612  9639 W System.err: java.lang.ClassNotFoundException: io.realm.react.util.SSLHelper
04-14 21:19:54.512  9612  9639 W System.err:    at java.lang.Runtime.nativeLoad(Native Method)
04-14 21:19:54.512  9612  9639 W System.err:    at java.lang.Runtime.nativeLoad(Runtime.java:1131)
04-14 21:19:54.512  9612  9639 W System.err:    at java.lang.Runtime.load0(Runtime.java:937)
04-14 21:19:54.512  9612  9639 W System.err:    at java.lang.System.load(System.java:1628)
04-14 21:19:54.512  9612  9639 W System.err:    at com.facebook.soloader.SoLoader$a.a(Unknown Source:201)
04-14 21:19:54.512  9612  9639 W System.err:    at com.facebook.soloader.d.h(Unknown Source:193)
04-14 21:19:54.512  9612  9639 W System.err:    at com.facebook.soloader.d.a(Unknown Source:2)
04-14 21:19:54.512  9612  9639 W System.err:    at com.facebook.soloader.b.a(Unknown Source:2)
04-14 21:19:54.512  9612  9639 W System.err:    at com.facebook.soloader.SoLoader.g(Unknown Source:69)
04-14 21:19:54.512  9612  9639 W System.err:    at com.facebook.soloader.SoLoader.t(Unknown Source:124)
04-14 21:19:54.512  9612  9639 W System.err:    at com.facebook.soloader.SoLoader.s(Unknown Source:2)
04-14 21:19:54.512  9612  9639 W System.err:    at com.facebook.soloader.SoLoader.q(Unknown Source:42)
04-14 21:19:54.512  9612  9639 W System.err:    at com.facebook.soloader.SoLoader.p(Unknown Source:1)
04-14 21:19:54.512  9612  9639 W System.err:    at io.realm.react.RealmReactModule.<clinit>(Unknown Source:2)
04-14 21:19:54.512  9612  9639 W System.err:    at io.realm.react.a.e(Unknown Source:8)
04-14 21:19:54.512  9612  9639 W System.err:    at com.facebook.react.c0$b.a(Unknown Source:6)
04-14 21:19:54.512  9612  9639 W System.err:    at com.facebook.react.c0$b.get(Unknown Source:0)
04-14 21:19:54.512  9612  9639 W System.err:    at com.facebook.react.bridge.ModuleHolder.create(Unknown Source:67)
04-14 21:19:54.512  9612  9639 W System.err:    at com.facebook.react.bridge.ModuleHolder.getModule(Unknown Source:20)
04-14 21:19:54.512  9612  9639 W System.err:    at com.facebook.react.bridge.JavaModuleWrapper.findMethods(Unknown Source:14)
04-14 21:19:54.512  9612  9639 W System.err:    at com.facebook.react.bridge.JavaModuleWrapper.getMethodDescriptors(Unknown Source:8)
04-14 21:19:54.512  9612  9639 W System.err:    at com.facebook.jni.NativeRunnable.run(Native Method)
04-14 21:19:54.512  9612  9639 W System.err:    at android.os.Handler.handleCallback(Handler.java:938)
04-14 21:19:54.512  9612  9639 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:99)
04-14 21:19:54.512  9612  9639 W System.err:    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0)
04-14 21:19:54.512  9612  9639 W System.err:    at android.os.Looper.loop(Looper.java:250)
04-14 21:19:54.512  9612  9639 W System.err:    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source:37)
04-14 21:19:54.512  9612  9639 W System.err:    at java.lang.Thread.run(Thread.java:923)
04-14 21:19:54.512  9612  9639 E SoLoader: couldn't find DSO to load: librealm.so caused by: io.realm.react.util.SSLHelper result: 0
04-14 21:19:54.513  9612  9639 E unknown:NativeModuleInitError: Failed to create NativeModule "Realm"
04-14 21:19:54.513  9612  9639 E unknown:NativeModuleInitError: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: librealm.so caused by: io.realm.react.util.SSLHelper result: 0
04-14 21:19:54.513  9612  9639 E unknown:NativeModuleInitError:         at com.facebook.soloader.SoLoader.g(Unknown Source:343)
04-14 21:19:54.513  9612  9639 E unknown:NativeModuleInitError:         at com.facebook.soloader.SoLoader.t(Unknown Source:124)
04-14 21:19:54.513  9612  9639 E unknown:NativeModuleInitError:         at com.facebook.soloader.SoLoader.s(Unknown Source:2)
04-14 21:19:54.513  9612  9639 E unknown:NativeModuleInitError:         at com.facebook.soloader.SoLoader.q(Unknown Source:42)
04-14 21:19:54.513  9612  9639 E unknown:NativeModuleInitError:         at com.facebook.soloader.SoLoader.p(Unknown Source:1)
04-14 21:19:54.513  9612  9639 E unknown:NativeModuleInitError:         at io.realm.react.RealmReactModule.<clinit>(Unknown Source:2)
04-14 21:19:54.513  9612  9639 E unknown:NativeModuleInitError:         at io.realm.react.a.e(Unknown Source:8)
04-14 21:19:54.513  9612  9639 E unknown:NativeModuleInitError:         at com.facebook.react.c0$b.a(Unknown Source:6)
04-14 21:19:54.513  9612  9639 E unknown:NativeModuleInitError:         at com.facebook.react.c0$b.get(Unknown Source:0)
04-14 21:19:54.513  9612  9639 E unknown:NativeModuleInitError:         at com.facebook.react.bridge.ModuleHolder.create(Unknown Source:67)
04-14 21:19:54.513  9612  9639 E unknown:NativeModuleInitError:         at com.facebook.react.bridge.ModuleHolder.getModule(Unknown Source:20)
04-14 21:19:54.513  9612  9639 E unknown:NativeModuleInitError:         at com.facebook.react.bridge.JavaModuleWrapper.findMethods(Unknown Source:14)
04-14 21:19:54.513  9612  9639 E unknown:NativeModuleInitError:         at com.facebook.react.bridge.JavaModuleWrapper.getMethodDescriptors(Unknown Source:8)
04-14 21:19:54.513  9612  9639 E unknown:NativeModuleInitError:         at com.facebook.jni.NativeRunnable.run(Native Method)
04-14 21:19:54.513  9612  9639 E unknown:NativeModuleInitError:         at android.os.Handler.handleCallback(Handler.java:938)
04-14 21:19:54.513  9612  9639 E unknown:NativeModuleInitError:         at android.os.Handler.dispatchMessage(Handler.java:99)
04-14 21:19:54.513  9612  9639 E unknown:NativeModuleInitError:         at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0)
04-14 21:19:54.513  9612  9639 E unknown:NativeModuleInitError:         at android.os.Looper.loop(Looper.java:250)
04-14 21:19:54.513  9612  9639 E unknown:NativeModuleInitError:         at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source:37)
04-14 21:19:54.513  9612  9639 E unknown:NativeModuleInitError:         at java.lang.Thread.run(Thread.java:923)
04-14 21:19:54.513  9612  9639 E unknown:NativeModuleInitError: Caused by: java.lang.ClassNotFoundException: io.realm.react.util.SSLHelper
04-14 21:19:54.513  9612  9639 E unknown:NativeModuleInitError:         at java.lang.Runtime.nativeLoad(Native Method)
04-14 21:19:54.513  9612  9639 E unknown:NativeModuleInitError:         at java.lang.Runtime.nativeLoad(Runtime.java:1131)
04-14 21:19:54.513  9612  9639 E unknown:NativeModuleInitError:         at java.lang.Runtime.load0(Runtime.java:937)
04-14 21:19:54.513  9612  9639 E unknown:NativeModuleInitError:         at java.lang.System.load(System.java:1628)
04-14 21:19:54.513  9612  9639 E unknown:NativeModuleInitError:         at com.facebook.soloader.SoLoader$a.a(Unknown Source:201)
04-14 21:19:54.513  9612  9639 E unknown:NativeModuleInitError:         at com.facebook.soloader.d.h(Unknown Source:193)
04-14 21:19:54.513  9612  9639 E unknown:NativeModuleInitError:         at com.facebook.soloader.d.a(Unknown Source:2)
04-14 21:19:54.513  9612  9639 E unknown:NativeModuleInitError:         at com.facebook.soloader.b.a(Unknown Source:2)
04-14 21:19:54.513  9612  9639 E unknown:NativeModuleInitError:         at com.facebook.soloader.SoLoader.g(Unknown Source:69)
04-14 21:19:54.513  9612  9639 E unknown:NativeModuleInitError:         ... 19 more
04-14 21:19:54.514  9612  9639 E ReactNativeJS: Error: Exception in HostObject::get for prop 'Realm': java.lang.UnsatisfiedLinkError: couldn't find DSO to load: librealm.so caused by: io.realm.react.util.SSLHelper result: 0, js engine: hermes
```

### Can you reproduce the bug?

Always

### Version

11.8.0

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

android

### Build environment

Which debugger for React Native: ..

**Comment by kneth** [comment]
@DeepzUa Thank you for reporting. It looks like `librealm.so` isn't distributed in your APK for some recent.

You are aware that `enableSeparateBuildPerCPUArchitecture` will go away in the next RN version? See https://github.com/facebook/react-native/pull/36341 and https://github.com/react-native-community/discussions-and-proposals/issues/602 for details.
