### ISSUE TITLE
Expo template for React Native not working

### ISSUE THREAD

**Issue by bogdan-pechounov** [realm/realm-js#5845]
### How frequently does the bug occur?

Always

### Description

I am trying to follow the [Bootstrap with Expo - React Native SDK](https://www.mongodb.com/docs/realm/sdk/react-native/bootstrap-with-expo/) tutorial, but I can't run the app on Android.

At first, I ignored the expo-cli warning.
```
>expo init MyAwesomeRealmApp --template @realm/expo-template
WARNING: The legacy expo-cli does not support Node +17. Migrate to the versioned Expo CLI (npx expo).
```
However, when trying to run the app on Android, nothing would happen. I also tried cloning from the [repo](https://github.com/realm/realm-js/tree/74470d0ecd2d9ddd07eaa7a1cb67f069a951ca74/templates/expo-template) directly, but nothing would get printed out on the terminal so it was hard to diagnose the issue.

Then, I tried using `npx create-expo-app`, but for some reason it is trying to find a file in cache.

### Stacktrace & log output

```shell
>npx create-expo-app --template @realm/expo-template
√ What is your app named? ... test
| Locating project files.node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\bpech\AppData\Local\Temp\.create-expo-app\template-cache\@realm\expo-template-0.5.1.tgz'
Emitted 'error' event on ReadStream instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\bpech\\AppData\\Local\\Temp\\.create-expo-app\\template-cache\\@realm\\expo-template-0.5.1.tgz'
}

Node.js v18.12.1
```
Not sure which version of Expo is used when using npx.
```
>npx create-expo-app --version
1.3.3
```
Based on this [compatibility chart](https://github.com/realm/realm-js/blob/main/COMPATIBILITY.md), using Node.js 18 should be fine.

### Can you reproduce the bug?

Always

### Version

11.7.0 (based on package.json in github repo)

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Windows 11

### Build environment

Which debugger for React Native: ..

**Comment by kneth** [comment]
Can it be fixed by [this trick](https://github.com/expo/expo/issues/20305#issuecomment-1361516186)?

**Comment by bogdan-pechounov** [comment]
I created a project with `expo init MyAwesomeRealmApp --template @realm/expo-template`, but I didn't find similar text in the `yarn.lock` file. 
![image](https://github.com/realm/realm-js/assets/119967588/aa84fbb8-0223-4c4a-83de-d61283e08bed)
![image](https://github.com/realm/realm-js/assets/119967588/f3d513c4-0384-4932-a875-a854ee383472)
![image](https://github.com/realm/realm-js/assets/119967588/00cdca28-e04c-4a19-beb1-e3a56193a1fb)

When I scan the QR code on my Android device, the "Scan an Expo QR code" screen crashes without any logs.

![image](https://github.com/realm/realm-js/assets/119967588/e27d56b0-3d68-4ae5-941b-d67aaec0efab)

**Comment by jolancornevin** [comment]
Hello!

I have the same issue. 

I ran `expo init App --template @realm/expo-template` and then `npm run start` but scanning the QR code on my Android phone does nothing. The Expo app opens the camera, scan the code and then just close the camera and shows me the initial screen again. I've tried to enter the url too, but nothing happens when I press enter. I don't have any error page being shown to me. I have no logs either.

I'm on MacOS, so `npm run ios` is working. But I have an android too and I'm not able to run it on my device via expo go. I didn't try to run the app on the android simulator.

Thxs for your help :)

**Comment by takameyer** [comment]
@jolancornevin Expo Go is not compatible with apps using 3rd party libraries, such as Realm.  However, you can compile a dev client version either locally or using EAS by running `npm run android`.  The application created with this build will be compatible with the QR code shown when typing `npm run start`.

**Comment by bogdan-pechounov** [comment]
Ah I didn't realize Expo Go had such a limitation. I thought it was simply used to connect your device with your computer without having to type an IP address.

"Expo Go is a native app that is installed on your device. When you run npx expo start in your project, Expo CLI **starts a development server** and generates a QR code. You can then open the Expo Go app on your device and scan the QR code **to connect to the dev server.**" [How it works](https://docs.expo.dev/get-started/expo-go/#how-it-works)

I deleted Android Studio due to limited resources, so I didn't try `npm run android`. I did try the web version however (after installing web dependencies for React Native `npx expo install react-native-web@~0.18.10 react-dom@18.2.0 @expo/webpack-config@^18.0.1`). Since it didn't work, I assumed the same would have happened with `npm run android`.
```
› Press ? │ show all commands

› Open in the web browser...
(node:21084) [DEP_WEBPACK_DEV_SERVER_CONSTRUCTOR] DeprecationWarning: Using 'compiler' as the first argument is deprecated. Please use 'options' as the first argument and 'compiler' as the second argument.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:21084) [DEP_WEBPACK_DEV_SERVER_LISTEN] DeprecationWarning: 'listen' is deprecated. Please use the async 'start' or 'startCallback' method.     
› Press ? │ show all commands
WARNING in ./node_modules/@realm/react/dist/AppProvider.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\bpech\Me\Learning\Practice\react-native-practice\MyAwesomeRealmApp\node_modules\@realm\react\src\AppProvider.tsx' file: Error: ENOENT: no such file or directory, open 'C:\Users\bpech\Me\Learning\Practice\react-native-practice\MyAwesomeRealmApp\node_modules\@realm\react\src\AppProvider.tsx'

WARNING in ./node_modules/@realm/react/dist/RealmProvider.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\bpech\Me\Learning\Practice\react-native-practice\MyAwesomeRealmApp\node_modules\@realm\react\src\RealmProvider.tsx' file: Error: ENOENT: no such file or directory, open 'C:\Users\bpech\Me\Learning\Practice\react-native-practice\MyAwesomeRealmApp\node_modules\@realm\react\src\RealmProvider.tsx'

WARNING in ./node_modules/@realm/react/dist/UserProvider.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\bpech\Me\Learning\Practice\react-native-practice\MyAwesomeRealmApp\node_modules\@realm\react\src\UserProvider.tsx' file: Error: ENOENT: no such file or directory, open 'C:\Users\bpech\Me\Learning\Practice\react-native-practice\MyAwesomeRealmApp\node_modules\@realm\react\src\UserProvider.tsx'

WARNING in ./node_modules/@realm/react/dist/cachedCollection.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\bpech\Me\Learning\Practice\react-native-practice\MyAwesomeRealmApp\node_modules\@realm\react\src\cachedCollection.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\bpech\Me\Learning\Practice\react-native-practice\MyAwesomeRealmApp\node_modules\@realm\react\src\cachedCollection.ts'

WARNING in ./node_modules/@realm/react/dist/cachedObject.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\bpech\Me\Learning\Practice\react-native-practice\MyAwesomeRealmApp\node_modules\@realm\react\src\cachedObject.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\bpech\Me\Learning\Practice\react-native-practice\MyAwesomeRealmApp\node_modules\@realm\react\src\cachedObject.ts'

WARNING in ./node_modules/@realm/react/dist/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\bpech\Me\Learning\Practice\react-native-practice\MyAwesomeRealmApp\node_modules\@realm\react\src\index.tsx' file: Error: ENOENT: no such file or directory, open 'C:\Users\bpech\Me\Learning\Practice\react-native-practice\MyAwesomeRealmApp\node_modules\@realm\react\src\index.tsx'

WARNING in ./node_modules/@realm/react/dist/useObject.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\bpech\Me\Learning\Practice\react-native-practice\MyAwesomeRealmApp\node_modules\@realm\react\src\useObject.tsx' file: Error: ENOENT: no such file or directory, open 'C:\Users\bpech\Me\Learning\Practice\react-native-practice\MyAwesomeRealmApp\node_modules\@realm\react\src\useObject.tsx'

WARNING in ./node_modules/@realm/react/dist/useQuery.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\bpech\Me\Learning\Practice\react-native-practice\MyAwesomeRealmApp\node_modules\@realm\react\src\useQuery.tsx' file: Error: ENOENT: no such file or directory, open 'C:\Users\bpech\Me\Learning\Practice\react-native-practice\MyAwesomeRealmApp\node_modules\@realm\react\src\useQuery.tsx'

WARNING in ./node_modules/@realm/react/dist/useRealm.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\bpech\Me\Learning\Practice\react-native-practice\MyAwesomeRealmApp\node_modules\@realm\react\src\useRealm.tsx' file: Error: ENOENT: no such file or directory, open 'C:\Users\bpech\Me\Learning\Practice\react-native-practice\MyAwesomeRealmApp\node_modules\@realm\react\src\useRealm.tsx'

WARNING in ./node_modules/realm/lib/utils.js:22
Critical dependency: the request of a dependency is an expression
  20 | const require_method = require;
  21 | function node_require(module) {
> 22 |   return require_method(module);
  23 | }
  24 |
  25 | /**

ERROR in ./node_modules/bindings/bindings.js:5
Module not found: Can't resolve 'fs'
  3 |  */
  4 |
> 5 | var fs = require('fs'),
  6 |   path = require('path'),
  7 |   fileURLToPath = require('file-uri-to-path'),
  8 |   join = path.join,

ERROR in ./node_modules/bindings/bindings.js:6
Module not found: Can't resolve 'path'
  4 |
  5 | var fs = require('fs'),
> 6 |   path = require('path'),
  7 |   fileURLToPath = require('file-uri-to-path'),
  8 |   join = path.join,
  9 |   dirname = path.dirname,

ERROR in ./node_modules/file-uri-to-path/index.js:6
Module not found: Can't resolve 'path'
  4 |  */
  5 |
> 6 | var sep = require('path').sep || '/';
  7 |
  8 | /**
  9 |  * Module exports.

web compiled with 3 errors and 10 warnings
```

**Comment by takameyer** [comment]
@bogdan-pechounov This [part of the documentation](https://docs.expo.dev/get-started/expo-go/#production) explains a bit deeper:

> You can create your own Expo Go type app by using the [expo-dev-client](https://docs.expo.dev/develop/development-builds/introduction/) package. This package allows you to create a native client with any custom native code or configuration or a third-party library that requires configuring native code. For more information, see [development builds](https://docs.expo.dev/develop/development-builds/introduction/).

Realm is also not currently compatible with the browser, so you will only be able to run on native devices/simulators/emulators.

**Comment by bogdan-pechounov** [comment]
(`npm start` does use the dev client: `expo start --dev-client`)

Just tried `yarn android` after `expo init MyAwesomeRealmApp --template @realm/expo-template` (after installing Android Studio 2022.2.1):
```
>yarn android

📝  Android package Learn more: https://expo.fyi/android-package

√ What would you like your Android package name to be? ... com.anonymous.MyAwesomeRealmApp

√ Created native project | gitignore skipped
› Metro skipped: Project metro.config.js does not match prebuild template.
› Ensure the project uses expo/metro-config.
  Learn more: https://docs.expo.dev/guides/customizing-metro
√ Updated package.json and added index.js entry point for iOS and Android
› Installing using yarn
> yarn install
√ Config synced
› Building app...
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file 'C:\Users\bpech\Me\Learning\Practice\react-native-practice\MyAwesomeRealmApp\android\settings.gradle' (C:\Users\bpech\.gradle\caches\7.5.1\scripts\edm7kfu5cmdepx0nz72edz7m5).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 63

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Error: C:\Users\bpech\Me\Learning\Practice\react-native-practice\MyAwesomeRealmApp\android\gradlew.bat exited with non-zero code: 1
Error: C:\Users\bpech\Me\Learning\Practice\react-native-practice\MyAwesomeRealmApp\android\gradlew.bat exited with non-zero code: 1
    at ChildProcess.completionListener (C:\Users\bpech\Me\Learning\Practice\react-native-practice\MyAwesomeRealmApp\node_modules\@expo\cli\node_modules\@expo\spawn-async\build\spawnAsync.js:52:23)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at cp.emit (C:\Users\bpech\Me\Learning\Practice\react-native-practice\MyAwesomeRealmApp\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
    ...
    at Object.spawnAsync [as default] (C:\Users\bpech\Me\Learning\Practice\react-native-practice\MyAwesomeRealmApp\node_modules\@expo\cli\node_modules\@expo\spawn-async\build\spawnAsync.js:17:21)
    at spawnGradleAsync (C:\Users\bpech\Me\Learning\Practice\react-native-practice\MyAwesomeRealmApp\node_modules\@expo\cli\build\src\start\platforms\android\gradle.js:72:46)
    at Object.assembleAsync (C:\Users\bpech\Me\Learning\Practice\react-native-practice\MyAwesomeRealmApp\node_modules\@expo\cli\build\src\start\platforms\android\gradle.js:52:18)
    at runAndroidAsync (C:\Users\bpech\Me\Learning\Practice\react-native-practice\MyAwesomeRealmApp\node_modules\@expo\cli\build\src\run\android\runAndroidAsync.js:31:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I think the problem is that `C:\Users\bpech\.gradle\caches\7.5.1\scripts\edm7kfu5cmdepx0nz72edz7m5\settings` is empty, but I don't know why.
![image](https://github.com/realm/realm-js/assets/119967588/6a08cc5b-b8c8-497b-9068-714e5917058c)

MyAwesomeRealmApp\android\settings.gradle file:
```
rootProject.name = 'MyAwesomeRealmApp'

apply from: new File(["node", "--print", "require.resolve('expo/package.json')"].execute(null, rootDir).text.trim(), "../scripts/autolinking.gradle");
useExpoModules()

apply from: new File(["node", "--print", "require.resolve('@react-native-community/cli-platform-android/package.json')"].execute(null, rootDir).text.trim(), "../native_modules.gradle");
applyNativeModulesSettingsGradle(settings)

include ':app'
includeBuild(new File(["node", "--print", "require.resolve('react-native-gradle-plugin/package.json')"].execute(null, rootDir).text.trim()).getParentFile())
```

**Comment by bogdan-pechounov** [comment]
My Java and Gradle versions weren't [compatible](https://stackoverflow.com/questions/72968643/the-jdk-18-0-1-isnt-compatible-with-gradle-4-4-1). After setting `JAVA_HOME` to `C:\Program Files\Java\jdk-17` instead of jdk-19, I also had to [set the jdk location](https://stackoverflow.com/questions/27620262/sdk-location-not-found-define-location-with-sdk-dir-in-the-local-properties-fil) in the android folder of the react native project (by adding a `local.properties` file with `sdk.dir=C:\\Users\\bpech\\AppData\\Local\\Android\\sdk`).

After many minutes of building the app, I get the following error: 
```
> Task :app:mergeDebugNativeLibs FAILED
w: Detected multiple Kotlin daemon sessions at build\kotlin\sessions

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:                                                                                                                                       
Execution failed for task ':app:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeNativeLibsTask$MergeNativeLibsTaskWorkAction
   > There is not enough space on the disk

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

BUILD FAILED in 16m 8s
370 actionable tasks: 251 executed, 114 from cache, 5 up-to-date
Error: C:\Users\bpech\Me\Learning\Practice\react-native-practice\MyAwesomeRealmApp\android\gradlew.bat exited with non-zero code: 1
Error: C:\Users\bpech\Me\Learning\Practice\react-native-practice\MyAwesomeRealmApp\android\gradlew.bat exited with non-zero code: 1
    at ChildProcess.completionListener (C:\Users\bpech\Me\Learning\Practice\react-native-practice\MyAwesomeRealmApp\node_modules\@expo\cli\node_modules\@expo\spawn-async\build\spawnAsync.js:52:23)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at cp.emit (C:\Users\bpech\Me\Learning\Practice\react-native-practice\MyAwesomeRealmApp\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
    ...
    at Object.spawnAsync [as default] (C:\Users\bpech\Me\Learning\Practice\react-native-practice\MyAwesomeRealmApp\node_modules\@expo\cli\node_modules\@expo\spawn-async\build\spawnAsync.js:17:21)
    at spawnGradleAsync (C:\Users\bpech\Me\Learning\Practice\react-native-practice\MyAwesomeRealmApp\node_modules\@expo\cli\build\src\start\platforms\android\gradle.js:72:46)
    at Object.assembleAsync (C:\Users\bpech\Me\Learning\Practice\react-native-practice\MyAwesomeRealmApp\node_modules\@expo\cli\build\src\start\platforms\android\gradle.js:52:18)
    at runAndroidAsync (C:\Users\bpech\Me\Learning\Practice\react-native-practice\MyAwesomeRealmApp\node_modules\@expo\cli\build\src\run\android\runAndroidAsync.js:31:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

```
"dependencies": {
    "@realm/react": "^0.4.3",
    "expo": "~48.0.15",
    "expo-dev-client": "~2.1.6",
    "expo-splash-screen": "~0.18.2",
    "expo-status-bar": "~1.4.2",
    "react": "18.2.0",
    "react-native": "0.71.8",
    "react-native-get-random-values": "~1.8.0",
    "realm": "11.7.0"
  },
```

I have 4GB of storage left, is this not enough? It's also strange that there is a StackOverflowError. I was able to run other Expo apps on the Android emulator and it didn't take that long to build. [This](https://stackoverflow.com/questions/67135414/w-detected-multiple-kotlin-daemon-sessions-at-build-kotlin-sessions) might be related (similar `Detected multiple Kotlin daemon sessions` issue with react-native: 0.63.2).

**Comment by takameyer** [comment]
@bogdan-pechounov Thanks for the detailed info.  We will investigate and get back to you soon.
