### ISSUE TITLE
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: librealm.so Failed to create "Realm"

### ISSUE THREAD

**Issue by nabilashraf** [realm/realm-js#6022]
### How frequently does the bug occur?

Always

### Description

Installed realm with version 11.10.1 with react-native 0.71.4. App is working fine locally but release version is crashing as soon the app opens up.

Here's how I have initialized my Realm 
```
import Realm from 'realm';
import configuration from './models';

let app;

// Returns the shared instance of the Realm app.
export function getRealmApp() {
  if (app === undefined) {
    app = new Realm(configuration);
  }
  return app;
}
```

Where required I have import the getRealmApp and initialized it to a constant e.g. const app = getRealmApp()

Earlier i tried to use it as 
```
const app = new Realm(configuration)
```
This is my configuration file 
```
// global
const KeySchema = {
  name: 'Key',
  properties: {
    key: 'string',
    value: 'string',
  },
  primaryKey: 'key',
};

// create form entry schema
const FormEntrySchema = {
  name: 'OfflineFormEntry',
  properties: {
    _id: 'string',
    formId: 'string',
    data: 'string',
  },
  primaryKey: '_id',
};

const TaskEntrySchema = {
  name: 'OfflineTaskEntry',
  properties: {
    _id: 'string',
    data: 'string',
  },
  primaryKey: '_id',
};

const ProcessEntrySchema = {
  name: 'OfflineProcessEntry',
  properties: {
    _id: 'string',
    processId: 'string',
    data: 'string',
  },
  primaryKey: '_id',
};

const OfflineFileSchema = {
  name: 'OfflineFile',
  properties: {
    id: 'string',
    localPath: 'string',
  },
  primaryKey: 'id',
};

const configuration = {
  schema: [
    KeySchema,
    FormEntrySchema,
    ProcessEntrySchema,
    TaskEntrySchema,
    OfflineFileSchema,
  ],
  // deleteRealmIfMigrationNeeded: true,
};

export default configuration;
```

### Stacktrace & log output

```shell
Failed to create NativeModule "Realm"
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: librealm.so caused by: io.realm.react.util.SSLHelper result: 0
	at com.facebook.soloader.SoLoader.g(Unknown Source:343)
	at com.facebook.soloader.SoLoader.t(Unknown Source:124)
	at com.facebook.soloader.SoLoader.s(Unknown Source:2)
	at com.facebook.soloader.SoLoader.q(Unknown Source:42)
	at com.facebook.soloader.SoLoader.p(Unknown Source:1)
	at io.realm.react.RealmReactModule.<clinit>(Unknown Source:2)
	at io.realm.react.a.getModule(Unknown Source:8)
	at com.facebook.react.a0$b.a(Unknown Source:6)
	at com.facebook.react.a0$b.get(Unknown Source:0)
	at com.facebook.react.bridge.ModuleHolder.create(Unknown Source:67)
	at com.facebook.react.bridge.ModuleHolder.getModule(Unknown Source:20)
	at com.facebook.react.bridge.JavaModuleWrapper.findMethods(Unknown Source:14)
	at com.facebook.react.bridge.JavaModuleWrapper.getMethodDescriptors(Unknown Source:8)
	at com.facebook.jni.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0)
	at android.os.Looper.loop(Looper.java:223)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source:37)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.ClassNotFoundException: io.realm.react.util.SSLHelper
	at java.lang.Runtime.nativeLoad(Native Method)
	at java.lang.Runtime.nativeLoad(Runtime.java:1131)
	at java.lang.Runtime.load0(Runtime.java:937)
	at java.lang.System.load(System.java:1628)
	at com.facebook.soloader.SoLoader$a.a(Unknown Source:201)
	at com.facebook.soloader.c.a(Unknown Source:76)
	at com.facebook.soloader.SoLoader.g(Unknown Source:69)
	... 19 more
```

### Can you reproduce the bug?

Always

### Reproduction Steps

Install realm from npm
Install react-native version 0.71.4

### Version

11.10.1

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Android 

### Build environment

Which debugger for React Native: ..

System:
    OS: macOS 13.4.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 632.38 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: 2022.10.03.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 28, 29, 30, 31, 33
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by nabilashraf** [comment]
Can someone help ? Need to resolve this urgently.

**Comment by takameyer** [comment]
@nabilashraf This is similar to (#6026).  I'll perhaps the `.so` was somehow missing from this release.  I'll investigate immediately

**Comment by takameyer** [comment]
@nabilashraf I have attempted to reproduce this with an intel mac on android, using React Native 0.71.4 and Realm 11.10.1.  Everything worked as intended.  The error message indicates that the `realm.so` is missing.  Can you verify that `node_modules/realm/react-native/android/src/main/jniLibs/x86` exists and is not empty?

**Comment by takameyer** [comment]
@nabilashraf I would also be interested in seeing if our v12 release candidate would work on your setup.  You can try it out with `npm install realm@next`

**Comment by nabilashraf** [comment]
I'll try this out and get back to you.

**Comment by kneth** [comment]
@nabilashraf Did you have a chance to try v12?
