### ISSUE TITLE
Error defining property in Realm schema for React Native app

### ISSUE THREAD

**Issue by mayankkumawat** [realm/realm-js#6025]
### How frequently does the bug occur?

Always

### Description

Invalid type declaration for property 'completedSampleTreesCount' on 'Inventory': Cannot use shorthand '?' in 'type' when defining property objects.

### Stacktrace & log output

```shell
Error: Invalid type declaration for property 'completedSampleTreesCount' on 'Inventory': Cannot use shorthand '?' in 'type' or 'objectType' when defining property objects.
Error: Invalid type declaration for property 'completedSampleTreesCount' on 'Inventory': Cannot use shorthand '?' in 'type' or 'objectType' when defining property objects.
    at construct (native)
    at Wrapper (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.pftp.treemapper:26631:64)
    at construct (native)
    at _createSuperInternal (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.pftp.treemapper:190833:406)
    at call (native)
    at SchemaParseError (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.pftp.treemapper:194667:27)
    at construct (native)
    at _createSuperInternal (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.pftp.treemapper:190833:406)
    at call (native)
    at PropertySchemaParseError (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.pftp.treemapper:194692:30)
    at anonymous (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.pftp.treemapper:203288:42)
    at assert (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.pftp.treemapper:194867:44)
    at assertNotUsingShorthand (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.pftp.treemapper:203279:11)
    at normalizePropertySchemaObject (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.pftp.treemapper:203203:28)
    at normalizePropertySchema (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.pftp.treemapper:203125:117)
    at normalizePropertySchemas (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.pftp.treemapper:203111:64)
    at normalizeObjectSchema (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.pftp.treemapper:203102:43)
    at map (native)
    at normalizeRealmSchema (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.pftp.treemapper:203058:27)
    at transformConfig (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.pftp.treemapper:202147:69)
    at Realm (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.pftp.treemapper:201321:58)
    at ProgressRealmPromise (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.pftp.treemapper:202616:32)
    at open (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.pftp.treemapper:201977:40)
    at anonymous (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.pftp.treemapper:208470:26)
    at tryCallTwo (/Users/distiller/react-native/packages/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/Users/distiller/react-native/packages/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/Users/distiller/react-native/packages/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:82:14)
    at deleteOldLogs (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.pftp.treemapper:208469:23)
    at ?anon_0_ (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.pftp.treemapper:357111:33)
    at next (native)
    at asyncGeneratorStep (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.pftp.treemapper:27881:26)
    at _next (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.pftp.treemapper:27900:29)
    at tryCallOne (/Users/distiller/react-native/packages/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/Users/distiller/react-native/packages/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.pftp.treemapper:34510:26)
    at _callTimer (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.pftp.treemapper:34389:17)
    at _callReactNativeMicrotasksPass (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.pftp.treemapper:34434:17)
    at callReactNativeMicrotasks (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.pftp.treemapper:34640:44)
    at __callReactNativeMicrotasks (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.pftp.treemapper:3284:46)
    at anonymous (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.pftp.treemapper:3058:45)
    at __guard (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.pftp.treemapper:3257:15)
    at flushedQueue (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.pftp.treemapper:3057:21)
    at invokeCallbackAndReturnFlushedQueue (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.pftp.treemapper:3051:33)
```

### Can you reproduce the bug?

Always

### Reproduction Steps

1. after building the app with command npx react-native run-ios

### Version

12.0.0-rc.1

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

IOS & Android

### Build environment

Which debugger for React Native: ..
Flipper
React Native 0.72.3

### Cocoapods version

1.12.1

**Comment by takameyer** [comment]
@mayankkumawat There was some changes in v12 to schema definitions.  If you want to declare an optional field then do it like this:
```
const Person = {
  name: "Person",
  properties: {
    name: "string",
    dog: { type: "Dog", optional: true }
  }
}
```

**Comment by mayankkumawat** [comment]
> @mayankkumawat There was some changes in v12 to schema definitions. If you want to declare an optional field then do it like this:
> 
> ```
> const Person = {
>   name: "Person",
>   properties: {
>     name: "string",
>     dog: { type: "Dog", optional: true }
>   }
> }
> ```

So from now we cannot user `?` shorthand for optional field ? Cause in the [doc](https://www.mongodb.com/docs/realm/sdk/react-native/model-data/define-a-realm-object-model/#declare-an-optional-property), it is not mentioned that we should avoid using `?` for optional field.
