### ISSUE TITLE
Realm Jest tests do not work with React Native

### ISSUE THREAD

**Issue by sharq1** [realm/realm-js#603]
I cannot run snapshot tests because when Realm is imported along with React Native I get following error:
```javascript
    SyntaxError: Unexpected token import

      at transformAndBuildScript (node_modules/jest-runtime/build/transform.js:284:10)
      at Object.<anonymous> (node_modules/realm/lib/index.js:30:24)
```

This simple example shows the problem. It passes until you uncomment `import 'react-native'` line
```javascript
'use strict'

// import 'react-native'
import Realm from 'realm'

describe('Realm-RN', () => {
  it('should pass', () => {
    expect(true).toEqual(true)
  })
})
```

**Comment by sharq1** [comment]
My `package.json` contents:

```javascript
  "jest": {
    "preset": "jest-react-native",
    "moduleNameMapper": {
      "\\./datepicker$": "<rootDir>/node_modules/tcomb-form-native/lib/templates/bootstrap/datepicker.ios.js"
    },
    "preprocessorIgnorePatterns": [
      "node_modules/(?!react-native|tcomb-form-native|apsl-react-native-button)"
    ],
    "testRegex": "(/__tests__/.*|\\.(test))\\.js$",
    "collectCoverage": true,
    "verbose": true
  },
  "standard": {
    "globals": [
      "jest",
      "expect",
      "it",
      "describe",
      "fetch",
      "beforeEach"
    ],
    "parser": "babel-eslint"
  },
```
```javascript
  "dependencies": {
    "@remobile/react-native-cache-image": "^1.0.0",
    "@remobile/react-native-cordova": "^1.0.9",
    "@remobile/react-native-sqlite": "^1.0.1",
    "analytics-node": "^2.1.0",
    "immutable": "3.8.1",
    "key-mirror": "^1.0.1",
    "lodash": "^4.12.0",
    "raven-js": "^3.2.1",
    "react": "15.3.1",
    "react-native": "0.32.0",
    "react-native-cache-image": "^1.0.0",
    "react-native-code-push": "^1.12.2-beta",
    "react-native-device-info": "^0.9.5",
    "react-native-drawer": "^2.2.4",
    "react-native-fbsdk": "^0.3.0",
    "react-native-fs": "^1.4.0",
    "react-native-gesture-recognizers": "^0.2.3",
    "react-native-i18n-complete": "git+https://git@github.com/sharq1/react-native-i18n-complete.git",
    "react-native-image-picker": "^0.18.17",
    "react-native-invertible-scroll-view": "^1.0.0",
    "react-native-keyboard-aware-scroll-view": "^0.1.2",
    "react-native-linear-gradient": "^1.5.7",
    "react-native-navbar": "git+https://git@github.com/sharq1/react-native-navbar",
    "react-native-page-swiper": "^0.1.0",
    "react-native-radio-buttons": "^0.11.0",
    "react-native-router-flux": "3.32.0",
    "react-native-scrollable-tab-view": "^0.4.2",
    "react-native-simple-store": "1.0.1",
    "react-native-simpledialog-android": "git+https://git@github.com/wookiem/react-native-simpledialog-android.git",
    "react-native-tabs": "^1.0.7",
    "react-native-vector-icons": "^2.1.0",
    "react-redux": "4.4.5",
    "realm": "git+https://git@github.com/realm/realm-js.git",
    "redux": "3.5.2",
    "redux-thunk": "2.1.0",
    "regenerator": "^0.8.46",
    "tcomb-form-native": "0.5.3",
    "undefined": "0.1.0",
    "underscore": "^1.8.3",
    "validate.js": "^0.9.0"
  },
  "devDependencies": {
    "asset-require-hook": "^1.0.2",
    "babel-core": "6.14.0",
    "babel-eslint": "^6.0.4",
    "babel-jest": "15.0.0",
    "babel-plugin-jsx-underscore": "^0.1.0",
    "babel-preset-airbnb": "^2.0.0",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react-native": "^1.9.0",
    "chai": "3.5.0",
    "chai-enzyme": "0.5.0",
    "docker": "^0.2.14",
    "enzyme": "2.4.1",
    "eslint": "^2.9.0",
    "eslint-plugin-react": "^5.0.1",
    "eslint-plugin-react-native": "^1.0.2",
    "flow-bin": "0.30.0",
    "istanbul": "0.4.3",
    "jasmine-node": "^1.14.5",
    "jest": "15.1.1",
    "jest-cli": "15.1.1",
    "jest-react-native": "15.0.0",
    "mocha": "3.0.1",
    "mockery": "^1.7.0",
    "react-addons-test-utils": "15.3.1",
    "react-dom": "15.3.1",
    "react-native-mock": "^0.2.6",
    "react-test-renderer": "15.3.1",
    "redux-mock-store": "1.1.2",
    "rnpm-plugin-upgrade": "^0.26.0",
    "sinon": "^1.17.4",
    "supertest": "^1.2.0",
    "standard": "^8.0.0"
  }
```

**Comment by fealebenpae** [comment]
Hey @sharq1,

It looks as if Jest isn't running all the JavaScript files through the Babel preprocessor before transforming them and thus chokes on some ES6 syntax. I'm not an expert on Jest and Babel, though, so I can't hazard a guess as to why that might be so.

Have you tried reversing the order of import statements? Does it still happen if you import any other module and Realm?

**Comment by sharq1** [comment]
@fealebenpae it crossed my mind to reverse the imports order, but it seemed ridiculous as a solution, but looks like it actually works! Thanks!

Shall I pass the issue to Jest?

**Comment by fealebenpae** [comment]
I guess so. Maybe someone more familiar with Jest would know what causes this.

**Comment by johannesschirrmeister** [comment]
Let me chime in with some half knowledge: Adding 'node_modules/realm' to ```preprocessorIgnorePatterns``` solved this issue for me.

Example:
`    "preprocessorIgnorePatterns": [
      "node_modules/(?!react-native|react|realm)"
    ]`

Vague attempt of an explanation: Something goes wrong when transpiling Realm, but that step isn't necessary and we solve the problem by skipping that step.

**Comment by billpatterson** [comment]
Making this change to my (react native) project's package.json file fixed it for me:

`"jest": { "preset": "react-native", "transformIgnorePatterns": ["node_modules/(?!react-native|tcomb-form-native|apsl-react-native-button|react|realm)"] },`

This was based on a message spit out by 'npm test' that said this was the updated version of preprocessorIgnorePatterns.

Don't really have any understanding of what's going on here. Just posting a "this helped me" comment.
