### ISSUE TITLE
Failed to create NativeModule "Realm" in release build when proguard is enabled

### ISSUE THREAD

**Issue by stee1ix** [realm/realm-js#6074]
### How frequently does the bug occur?

Always

### Description

Android  release build is crashing on load.

### Stacktrace & log output

```shell
Failed to create NativeModule "Realm"
                                                                                                    java.lang.ExceptionInInitializerError
                                                                                                    	at io.realm.react.a.getModule(RealmReactPackage.java:9)
                                                                                                    	at com.facebook.react.f0$b.a(TurboReactPackage.java:7)
                                                                                                    	at com.facebook.react.f0$b.get(TurboReactPackage.java:1)
                                                                                                    	at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:68)
                                                                                                    	at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:21)
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.getModule(JavaModuleWrapper.java:3)
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.getConstants(JavaModuleWrapper.java:93)
                                                                                                    	at com.facebook.jni.NativeRunnable.run(Native Method)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:38)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: java.lang.ClassNotFoundException: io.realm.react.util.SSLHelper
                                                                                                    	at java.lang.Runtime.nativeLoad(Native Method)
                                                                                                    	at java.lang.Runtime.nativeLoad(Runtime.java:1126)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1080)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1661)
                                                                                                    	at o4.c.a(SystemDelegate.java:1)
                                                                                                    	at o4.a.e(NativeLoader.java:9)
                                                                                                    	at o4.a.d(NativeLoader.java:2)
                                                                                                    	at com.facebook.soloader.SoLoader.r(SoLoader.java:11)
                                                                                                    	at io.realm.react.RealmReactModule.<clinit>(RealmReactModule.java:3)
                                                                                                    	at io.realm.react.a.getModule(RealmReactPackage.java:9) 
                                                                                                    	at com.facebook.react.f0$b.a(TurboReactPackage.java:7) 
                                                                                                    	at com.facebook.react.f0$b.get(TurboReactPackage.java:1) 
                                                                                                    	at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:68) 
                                                                                                    	at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:21) 
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.getModule(JavaModuleWrapper.java:3) 
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.getConstants(JavaModuleWrapper.java:93) 
                                                                                                    	at com.facebook.jni.NativeRunnable.run(Native Method) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205) 
                                                                                                    	at android.os.Looper.loop(Looper.java:294) 
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:38) 
                                                                                                    	at java.lang.Thread.run(Thread.java:1012) 
```

### Can you reproduce the bug?

Always

### Version

12.0.0-rc.3

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Android

### Build environment

System:
  OS: macOS 13.5
  CPU: (10) arm64 Apple M2 Pro
  Memory: 65.56 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.17.1
    path: ~/.nvm/versions/node/v16.17.1/bin/node
  Yarn: Not Found
  npm:
    version: 8.15.0
    path: ~/.nvm/versions/node/v16.17.1/bin/npm
  Watchman:
    version: 2023.07.03.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10406996
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.19
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true

**Comment by stee1ix** [comment]
Please help. Need a solution urgently

**Comment by kneth** [comment]
@stee1ix Does it help if you add `-keep class io.realm.react.**` to your proguard configuration?

**Comment by murilo-alvesmelo** [comment]
If proguard has it enabled, this works!

**Comment by murilo-alvesmelo** [comment]
@kneth If proguard has it enabled, this works!

**Comment by kneth** [comment]
We should add it to the documentation 😄

**Comment by maulanakurniawan** [comment]
> @stee1ix Does it help if you add `-keep class io.realm.react.**` to your proguard configuration?

this works for me, thanks a lot @stee1ix !

**Comment by vrdevrocket** [comment]
> @stee1ix Does it help if you add `-keep class io.realm.react.**` to your proguard configuration?

Your solution worked very well, Thanks.
