### ISSUE TITLE
Can't create a field of type 'dictionary' `{}`

### ISSUE THREAD

**Issue by muddy-alex** [realm/realm-js#6130]
### How frequently does the bug occur?

-- select --

### Description

I am trying to create a dictionary type on my Schema, it resembles the following...

```
export class Log extends Realm.Object {
  _id!: Realm.BSON.ObjectId;
  topic!: string;
  recordedAt!: Date;
  data!: any;
  organisation!: Realm.BSON.ObjectId;

  public static schema: Realm.ObjectSchema = {
    name: 'Log',
    primaryKey: '_id',
    properties: {
      _id: 'objectId',
      topic: 'string',
      recordedAt: 'date',
      data: '{}',

      organisation: 'objectId',
    }
  };
}
```

This is inline with the documentation here: https://www.mongodb.com/docs/realm/sdk/node/model-data/data-types/dictionaries/

When I being the sync of the schema, an error is raised complaining that `{}` is an invalid type.

If I use `string{}` then the schema upload happens, however, I would like a dictionary supporting more than just string types.

### Stacktrace & log output

```shell
/Users/alex/Workspace/overwatch/node_modules/realm/src/assert.ts:35
    err = typeof err === "function" ? err() : err;
                                      ^
PropertySchemaParseError: Invalid type declaration for property 'data' on 'Log': The element type must be specified (Example: 'int{}')
    at /Users/alex/Workspace/xx/node_modules/realm/src/schema/normalize.ts:409:16
    at assert (/Users/alex/Workspace/xx/node_modules/realm/src/assert.ts:35:39)
    at normalizePropertySchemaShorthand (/Users/alex/Workspace/xx/node_modules/realm/src/schema/normalize.ts:191:5)
    at normalizePropertySchema (/Users/alex/Workspace/xx/node_modules/realm/src/schema/normalize.ts:168:7)
    at normalizePropertySchemas (/Users/alex/Workspace/xx/node_modules/realm/src/schema/normalize.ts:151:39)
    at normalizeObjectSchema (/Users/alex/Workspace/xx/node_modules/realm/src/schema/normalize.ts:137:17)
    at normalizeObjectSchema (/Users/alex/Workspace/xx/node_modules/realm/src/schema/normalize.ts:104:26)
    at Array.map (<anonymous>)
    at normalizeRealmSchema (/Users/alex/Workspace/xx/node_modules/realm/src/schema/normalize.ts:95:22)
    at Function.transformConfig (/Users/alex/Workspace/xx/node_modules/realm/src/Realm.ts:526:47) {
  objectName: 'Log',
  propertyName: 'data'
}
```
```


### Can you reproduce the bug?

-- select --

### Reproduction Steps

_No response_

### Version

nodejs: 12.1.0

### What services are you using?

Both Atlas Device Sync and Atlas App Services

### Are you using encryption?

No

### Platform OS and version(s)

OSX

### Build environment

NodeJS v16.20.2

### Cocoapods version

_No response_

**Comment by elle-j** [comment]
Hi @muddy-alex, Previously, `{}` was an implicit `mixed{}`. For v12, the element type must be explicitly specified in your schema. Thus, change `{}` to `mixed{}` and it should work fine 👍

**Comment by muddy-alex** [comment]
Was just about to say I've corrected the problem! Thanks for the reply 👌🏻
