### ISSUE TITLE
Constructor was not registered in the schema for this Realm

### ISSUE THREAD

**Issue by muddy-alex** [realm/realm-js#6131]
### How frequently does the bug occur?

Always

### Description

I'm trying to write data to RealmDB, but keep coming up against this error.

The actual MongoDB collection that 'Log' syncs with is a time-series collection.

Steps to resolve:

1. Re-initialize sync
2. Delete and recreate app

```
Error: Constructor was not registered in the schema for this Realm\n    at assert (/Users/alex/Workspace/xxx/node_modules/realm/src/assert.ts:39:13)\n    at ClassMap.get (/Users/alex/Workspace/xxx/node_modules/realm/src/ClassMap.ts:179:7)\n    at ClassMap.getHelpers (/Users/alex/Workspace/xxx/node_modules/realm/src/ClassMap.ts:193:30)\n    at Realm.create (/Users/alex/Workspace/xxx/node_modules/realm/src/Realm.ts:874:34)\n    at /Users/alex/Workspace/xxx/packages/sprout-logger-service/src/router.ts:12:31\n    at Realm.write (/Users/alex/Workspace/xxx/node_modules/realm/src/Realm.ts:1146:16)\n    at /Users/alex/Workspace/xxx/packages/sprout-logger-service/src/router.ts:11:17\n    at resolveMiddleware (/Users/alex/Workspace/xxx/node_modules/@trpc/server/dist/index.js:422:36)\n    at callRecursive (/Users/alex/Workspace/xxx/node_modules/@trpc/server/dist/index.js:458:38)\n    at next (/Users/alex/Workspace/xxx/node_modules/@trpc/server/dist/index.js:467:32)"
```

If I comment out the following line from `bundle.node.js:4566` (the one that throws the assertion error), then it writes to the DB correctly.

```
assert(result === arg || Object.getPrototypeOf(result) === arg, "Constructor was not registered in the schema for this Realm");
```

### Can you reproduce the bug?

-- select --

### Reproduction Steps

```ts
export const Point: ObjectSchema = {
  name: 'Point',
  embedded: true,
  properties: {
    type: { type: 'string', default: () => 'Point' },
    coordinates: { type: 'list', objectType: 'double' }
  },
};

export class Log extends Realm.Object {
  _id!: Realm.BSON.ObjectId;
  timestamp!: Date;
  topic!: string;
  value!: any;
  location!: Point;   // GeoJSON interface
  locationFix!: number;
  organisation!: Realm.BSON.ObjectId;

  public static schema: Realm.ObjectSchema = {
    name: 'Log',
    primaryKey: '_id',
    properties: {
      _id: 'objectId',
      timestamp: 'date',
      organisation: 'objectId',
      topic: 'string',
      value: 'mixed',
      location: 'Point',
      locationFix: 'int'
    }
  };
}

export const realm: Realm = await Realm.open({
  schema: [ Log, Point ],
  sync: {
    flexible: true,
    initialSubscriptions: {
      update: (subs, realm) => {
        try {
          subs.add(realm.objects(Log));
        } catch (e) {
          console.log('Sync Failed', e);
        }
      },
    },
    onError: (e) => {
      console.error('Sync Error!');
      console.error(e);
    },
    user // API Key user
  }
});
```

### Version

12.1.0

### What services are you using?

Both Atlas Device Sync and Atlas App Services

### Are you using encryption?

No

### Platform OS and version(s)

osx

### Build environment

NodeJS: 16.20.2

**Comment by muddy-alex** [comment]
Mixing ESM and CJS modules. Derp!
