### ISSUE TITLE
Metro failed to resolve node:fs in an Expo project when using Nx

### ISSUE THREAD

**Issue by timur-svoboda** [realm/realm-js#6163]
### How frequently does the bug occur?

Always

### Description

Metro tries to resolve `node:fs` module, which does not exist in the React Native environment. There are [conditional exports](https://nodejs.org/api/packages.html#conditional-exports) in **package.json** of Realm:

```json
"exports": {
  ".": {
    "types": "./types.d.cts",
    "node": "./index.node.js",
    "require": "./index.node.js",
    "react-native": "./index.react-native.js"
  },
  "./scripts/submit-analytics": "./scripts/submit-analytics.mjs",
  "./react-native.config.js": "./react-native.config.js",
  "./package.json": "./package.json",
  "./realm-constants.json": "./realm-constants.json"
},
```

Notice the line: `"require": "./index.node.js",`. The line tells Metro to load Node.js version of Realm whenever we import realm using `require()`. It so happened that `@nx/expo` uses `require()` to import Realm.

I could not find a good reason for that condition to be there, so I propose to remove `"require": "./index.node.js",` from exports.

### Stacktrace & log output

```shell
error: Error: Cannot resolve node:fs
    at C:\Users\Timur\Documents\nx-expo-realm-integration\node_modules\@nx\expo\plugins\metro-resolver.js:31:15
    at resolveRequest (C:\Users\Timur\Documents\nx-expo-realm-integration\node_modules\@expo\cli\build\src\start\server\metro\withMetroResolvers.js:50:24)
    at Object.resolve (C:\Users\Timur\Documents\nx-expo-realm-integration\node_modules\metro-resolver\src\resolve.js:47:12)
    at ModuleResolver.resolveDependency (C:\Users\Timur\Documents\nx-expo-realm-integration\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:79:31)
    at DependencyGraph.resolveDependency (C:\Users\Timur\Documents\nx-expo-realm-integration\node_modules\metro\src\node-haste\DependencyGraph.js:277:43)
    at Object.resolve (C:\Users\Timur\Documents\nx-expo-realm-integration\node_modules\metro\src\lib\transformHelpers.js:169:21)
    at Graph._resolveDependencies (C:\Users\Timur\Documents\nx-expo-realm-integration\node_modules\metro\src\DeltaBundler\Graph.js:473:35)
    at Graph._processModule (C:\Users\Timur\Documents\nx-expo-realm-integration\node_modules\metro\src\DeltaBundler\Graph.js:261:38)
    at async Graph._addDependency (C:\Users\Timur\Documents\nx-expo-realm-integration\node_modules\metro\src\DeltaBundler\Graph.js:372:20)
    at async Promise.all (index 0)
    at async Graph._processModule (C:\Users\Timur\Documents\nx-expo-realm-integration\node_modules\metro\src\DeltaBundler\Graph.js:322:5)
    at async Graph._addDependency (C:\Users\Timur\Documents\nx-expo-realm-integration\node_modules\metro\src\DeltaBundler\Graph.js:372:20)
    at async Promise.all (index 6)
    at async Graph._processModule (C:\Users\Timur\Documents\nx-expo-realm-integration\node_modules\metro\src\DeltaBundler\Graph.js:322:5)
    at async Graph._addDependency (C:\Users\Timur\Documents\nx-expo-realm-integration\node_modules\metro\src\DeltaBundler\Graph.js:372:20)
    at async Promise.all (index 2)
```

### Can you reproduce the bug?

Always

### Reproduction Steps

A sample repository with the bug: https://github.com/timur-svoboda/realm-node-fs-bug

To start the app, run `npx nx start test-app`. You can than open the app in the [Expo Go](https://expo.dev/client). The bug also persists in the [development client](https://docs.expo.dev/develop/development-builds/introduction/). 

### Version

12.2.0

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Android 12

**Comment by kneth** [comment]
I get the same result when building the supplied app. As we have never tested our packages with `nx`, we need to investigate what impact it has.

**Comment by karam1ashqar** [comment]
happens with me when I tried it in react-native 0.73.1, my upgrade was from 0.72.7 ( working version ), not sure if its really related to this package or something related to metro/babel configs
