### ISSUE TITLE
 Android | react-native  - Error: Could not find the Realm binary.

### ISSUE THREAD

**Issue by arshad-slate** [realm/realm-js#6204]
### How frequently does the bug occur?

Always

### Description

 I am always getting error " Error: Could not find the Realm binary.". Checked the troubleshooting steps and could see necessary binaries are already downloaded.

<img width="684" alt="Screenshot 2023-10-19 at 6 18 16 PM" src="https://github.com/realm/realm-js/assets/74181688/5ab13255-fd8d-44f2-b0b6-8e80e6551f6c">

`hermesEnabled = true
`
Following are the SDK versions used.
```
realm": ^12.2.1
@realm/react: ^0.6.1


react-native: 0.71.14
react: 18.2.0,
Node: 18.17.0 
Yarn: 1.22.19 
npm: 9.6.7
Watchman: 2023.09.18.00 
```

### Stacktrace & log output

```shell
Error: Could not find the Realm binary. Please consult our troubleshooting guide: https://www.mongodb.com/docs/realm-sdks/js/latest/#md:troubleshooting-missing-binary, js engine: hermes 
    at AppEnv (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.myapp.xxx.staging&modulesOnly=false&runModule=true:96545:122)
    at RCTView
    at View (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com..xxx.staging&modulesOnly=false&runModule=true:46852:43)
    at RCTView
    at View (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.myapp.xxx.staging&modulesOnly=false&runModule=true:46852:43)
    at AppContainer (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.myapp.xxx.staging&modulesOnly=false&runModule=true:46717:36)
    at myapp(RootComponent) (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.myapp.xxx.staging&modulesOnly=false&runModule=true:84655:28)
 LOG  isHermesisHermesisHermesisHermesisHermes isHermes yyyyy ========   true
 ERROR  Error: Could not find the Realm binary. Please consult our troubleshooting guide: https://www.mongodb.com/docs/realm-sdks/js/latest/#md:troubleshooting-missing-binary, js engine: hermes 
    at AppEnv (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.myapp.xxx.staging&modulesOnly=false&runModule=true:96545:122)
    at RCTView
    at View (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.myapp.xxx.staging&modulesOnly=false&runModule=true:46852:43)
    at RCTView
    at View (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.myapp.xxx.staging&modulesOnly=false&runModule=true:46852:43)
    at AppContainer (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.myapp.xxx.staging&modulesOnly=false&runModule=true:46717:36)
    at myapp(RootComponent) (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.myapp.xxx.staging&modulesOnly=false&runModule=true:84655:28)
 ERROR  TypeError: Cannot read property 'Action' of undefined

This error is located at:
    in AppEnv
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in myapp(RootComponent), js engine: hermes
 ERROR  TypeError: Cannot read property 'Action' of undefined

This error is located at:
    in AppEnv
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in myapp(RootComponent), js engine: hermes
```

### Can you reproduce the bug?

Always

### Version

12.2.1

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Android API lever 31+

### Build environment

```
realm": ^12.2.1
@realm/react: ^0.6.1


react-native: 0.71.14
react: 18.2.0,
Node: 18.17.0 
Yarn: 1.22.19 
npm: 9.6.7
Watchman: 2023.09.18.00 
```

**Comment by arshad-slate** [comment]
@takameyer Downloading the template gave error you must user `ruby >=2.7.0`. Mine was `2.6.10`. Upgraded ruby version to `3.2.2` and was able to download the template.

Running template on android throws the following error:

```
error: Error: Unable to resolve module realm/realm-constants.json from /Users/fuser/Downloads/AwesomeRealmProject/node_modules/realm/dist/bundle.react-native.js: realm/realm-constants.json could not be found within the project or in these directories:
  node_modules/realm/node_modules
  node_modules
  4 | var reactNative = require('react-native');
  5 | var bson = require('bson');
> 6 | var realmConstants_json = require('realm/realm-constants.json');
    |                                    ^
  7 |
  8 | function _interopNamespaceDefault(e) {
  9 |   var n = Object.create(null);
    at ModuleResolver.resolveDependency (/Users/fuser/Downloads/AwesomeRealmProject/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:139:15)
    at DependencyGraph.resolveDependency (/Users/fuser/Downloads/AwesomeRealmProject/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/node-haste/DependencyGraph.js:277:43)
    at Object.resolve (/Users/fuser/Downloads/AwesomeRealmProject/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/lib/transformHelpers.js:169:21)
    at Graph._resolveDependencies (/Users/fuser/Downloads/AwesomeRealmProject/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/Graph.js:473:35)
    at Graph._processModule (/Users/fuser/Downloads/AwesomeRealmProject/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/Graph.js:261:38)
    at async Graph._addDependency (/Users/fuser/Downloads/AwesomeRealmProject/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/Graph.js:372:20)
    at async Promise.all (index 0)
    at async Graph._processModule (/Users/fuser/Downloads/AwesomeRealmProject/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/Graph.js:322:5)
    at async Graph._addDependency (/Users/fuser/Downloads/AwesomeRealmProject/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/Graph.js:372:20)
    at async Promise.all (index 8)

```

**Comment by takameyer** [comment]
@arshad-slate curious...in both projects it appears metro is having issues accessing `node_modules/realm`.  Is there perhaps some sort of global configuration on your system that could be affecting this?

**Comment by takameyer** [comment]
@arshad-slate I can reproduce the second issue.  We will look into that now.

**Comment by takameyer** [comment]
@arshad-slate Can you try, in both projects, the following:
```
rm -rf node_modules/realm
npm install realm
```
And then try building again.  I have witnessed some post-install scripts being skipped with the template and this should make sure our package settles down as expected after install.

**Comment by cyang2020** [comment]
had the same issue where this only appeared in debug mode for IOS

**Comment by suntan-superman** [comment]
I have been having the same problem on my Windows machine and using an iOS device for testing. I have downloaded multiple templates and online samples, and get the same problem each and every time. I have tried EVERYTHING. I even download this sample and got the same problem: I even followed this example step-by-step. Everything worked fine until I got to the step where I added the code to import realm: (https://dev.to/aaronksaunders/realm-database-expo-sdk-49-and-expo-router-getting-started-434e). Please help

**Comment by suntan-superman** [comment]
> @arshad-slate Can you try, in both projects, the following:
> 
> ```
> rm -rf node_modules/realm
> npm install realm
> ```
> 
> And then try building again. I have witnessed some post-install scripts being skipped with the template and this should make sure our package settles down as expected after install.

The problem persists. I have tried multiple sample projects and templates to no avail. Using Windows, Expo, React Native and an iOS device. FYI, I have successfully used Mongoose with my Web-based app with zero problems.

**Comment by damo21** [comment]
> > @arshad-slate Can you try, in both projects, the following:
> > ```
> > rm -rf node_modules/realm
> > npm install realm
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And then try building again. I have witnessed some post-install scripts being skipped with the template and this should make sure our package settles down as expected after install.
> 
> The problem persists. I have tried multiple sample projects and templates to no avail. Using Windows, Expo, React Native and an iOS device. FYI, I have successfully used Mongoose with my Web-based app with zero problems.

same problem for me, you managed to find a way around it?

**Comment by suntan-superman** [comment]
I created a simple sample project using the following command:

expo init realmTest --template @realm/expo-template

Afterwards I simply tried to run the program using the following command:

[cid:fd2a352e-d717-4f03-af2e-ea943670857f]

This is the result:

[cid:8e408327-17e4-46c7-891c-7868462480c8]

I researched it and it seems as though the problem was fixed a while back but it seems like it really wasn't. So I switched to Expo Go and this was the result when I tried to read using the iPhone camera:

[cid:85728ae4-e023-4bda-9516-7c2e3c3c423d]

No usable data found. Any ideas?

________________________________

**Comment by takameyer** [comment]
@suntan-superman Your screenshots are not visible.  Can you update your comment so we can see what commands you attempted?

**Comment by suntan-superman** [comment]
Of course. I apologize for that.

After building the example project using: expo init realmTest --template @realm/expo-template

I ran: yarn start #
The result was as follows:
yarn run v1.22.19
warning ..\..\package.json: No license field
The Metro Bundler started successfully yet when I tried to run the project in the Android emulator I got the following message:
Required package 'android.package' is not found in the project app.json

When I tried to run the project using the Expo Go and an iPhone, I got the error message 'No Usable Data Found' when scanning the QR code.

I did not touch the code and after building the fresh project. The package.json looks like this:

{
  "name": "realmtest",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios"
  },
  "dependencies": {
    ***@***.***/react": "^0.6.0",
    "expo": "^49.0.8",
    "expo-dev-client": "~2.4.8",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-native": "0.72.4",
    "react-native-get-random-values": "~1.9.0",
    "realm": "12.0.0"
  },
  "devDependencies": {
    ***@***.***/core": "^7.22.5",
    ***@***.***/plugin-proposal-decorators": "^7.22.5",
    ***@***.***/babel-plugin": "^0.1.1",
    ***@***.***/react": "~18.2.13",
    "typescript": "^5.1.3"
  },
  "license": "Apache-2.0",
  "private": true
}

The app.json looks like this:

{
  "expo": {
    "name": "realmTest",
    "slug": "realmTest",
    "version": "1.0.0",
    "assetBundlePatterns": [
      "**/*"
    ]
  }
}

This is the index.js file:

import 'expo-dev-client';
import 'react-native-get-random-values';
import React from 'react';
import {registerRootComponent} from 'expo'
import {AppWrapperNonSync} from './app/AppWrapperNonSync';
import {AppWrapperSync} from './app/AppWrapperSync';
import {SYNC_CONFIG} from './sync.config';

const App = () =>
  SYNC_CONFIG.enabled ? (
    <AppWrapperSync appId={SYNC_CONFIG.appId} />
  ) : (
    <AppWrapperNonSync />
  );

registerRootComponent(App);

Please let me know if you need anything else. As a side note, I have been using JS rather than TypeScript for my main project.
________________________________

**Comment by kneth** [comment]
@suntan-superman Expo Go does not support Realm - please see https://github.com/realm/realm-js/issues/6193#issuecomment-1757270090
