### ISSUE TITLE
Email Password Authentication Flow Breaks With Consecutive Logins From Different users

### ISSUE THREAD

**Issue by saniyusuf** [realm/realm-js#6331]
### How frequently does the bug occur?
Always

### Description
Consider the following case:
User A logs into an app via the email/password authentication flow. Everything works perfectly, and the Custom_data is correctly attached. 
User A then logs out of the app successfully. 
User B now attempts to log into the app, and everything works, but the flow breaks with a 401. This is happening as the realm-web SDK sends the deleted token from the already logged-out User A to the server, hence the 401 error.

With a quick refresh of the web page, everything works, and the correct token is sent off.

This is reproducible every single time. 
I am on a windows machine, working in an Angular environment. 

### Stacktrace & log output
```shell
core.mjs:7629 ERROR Error: Uncaught (in promise): Error: Request failed (POST https://realm.mongodb.com/api/client/v2.0/auth/session): token contains an invalid number of segments (status 401)
Error: Request failed (POST https://realm.mongodb.com/api/client/v2.0/auth/session): token contains an invalid number of segments (status 401)
    at bundle.dom.es.js:2863:24
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:25:1)
    at _ZoneDelegate.invoke (zone.js:372:26)
    at Object.onInvoke (core.mjs:26267:33)
    at _ZoneDelegate.invoke (zone.js:371:52)
    at Zone.run (zone.js:134:43)
    at zone.js:1275:36
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at resolvePromise (zone.js:1211:31)
    at zone.js:1118:17
    at zone.js:1134:33
    at _ZoneDelegate.invoke (zone.js:372:26)
    at Object.onInvoke (core.mjs:26267:33)
    at _ZoneDelegate.invoke (zone.js:371:52)
    at Zone.run (zone.js:134:43)
    at zone.js:1275:36
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:26254:33)
handleError @ core.mjs:7629
```

### Can you reproduce the bug?
Always

### Reproduction Steps
Log in as a user (User A) via email password. 
Logout as same user (User A) 

Then log in as a new user(User B) without refreshing.

### Version
1.7.0

### What services are you using?
Atlas App Services: Functions or GraphQL or DataAPI etc

### Are you using encryption?
No

### Platform OS and version(s)
Mac Sonoma 14.2

### Build environment
Angular

**Comment by kneth** [comment]
@saniyusuf 

Thank you for reporting. As you can reproduce it, can you create a small example for us?

**Comment by nirinchev** [comment]
Closing due to inactivity.
