### ISSUE TITLE
Realm JS Sync Configuration Error: 'manual' ClientReset Mode Requires 'error' or 'clientReset.onManual' Callbacks

### ISSUE THREAD

**Issue by Bartolg** [realm/realm-js#6419]
### How frequently does the bug occur?

Always

### Description

Encountered an exception in Realm JS when configuring Sync with 'manual' clientReset mode. Despite supplying the 'error' callback as per documentation, the application throws an error stating that either 'error' or 'clientReset.onManual' (or both) are required. This occurs even when the 'error' callback is already provided. The issue seems to be in how Realm JS interprets the configuration for the 'manual' clientReset mode. This leads to confusion and potential misconfiguration, hindering proper error handling in sync scenarios.

### Stacktrace & log output

```shell
LOG  25/01/2024, 16:06:53 | ERROR | Unexpected error occurred: {"stack":"Error: Exception in HostFunction: For clientReset: 'manual', it is require to set either 'error', 'clientReset.onManual' or both\n    at Realm (native)\n    at apply (native)\n    at Realm (JavaScript:8:41)\n    at initRealm (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.yodelutr&modulesOnly=false&runModule=true:152095:44)\n    at getMiddlewareConfiguration (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.yodelutr&modulesOnly=false&runModule=true:152116:16)\n    at deleteExpiredRealmFilesAndDirs (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.yodelutr&modulesOnly=false&runModule=true:151093:153)\n    at initialiseFileSystem (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.yodelutr&modulesOnly=false&runModule=true:151121:35)\n    at apply (native)\n    at runCallEffect (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.yodelutr&modulesOnly=false&runModule=true:136869:28)\n    at runEffect (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.yodelutr&modulesOnly=false&runModule=true:137463:21)\n    at digestEffect (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.yodelutr&modulesOnly=false&runModule=true:137522:21)\n    at next (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.yodelutr&modulesOnly=false&runModule=true:137424:23)\n    at currCb (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.yodelutr&modulesOnly=false&runModule=true:137505:11)\n    at tryCallOne (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/Release/3e1c4z49/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)\n    at anonymous (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/Release/3e1c4z49/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)\n    at apply (native)\n    at anonymous (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.yodelutr&modulesOnly=false&runModule=true:34978:26)\n    at _callTimer (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.yodelutr&modulesOnly=false&runModule=true:34857:17)\n    at _callReactNativeMicrotasksPass (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.yodelutr&modulesOnly=false&runModule=true:34902:17)\n    at callReactNativeMicrotasks (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.yodelutr&modulesOnly=false&runModule=true:35108:44)\n    at __callReactNativeMicrotasks (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.yodelutr&modulesOnly=false&runModule=true:3261:46)\n    at anonymous (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.yodelutr&modulesOnly=false&runModule=true:3035:45)\n    at __guard (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.yodelutr&modulesOnly=false&runModule=true:3234:15)\n    at flushedQueue (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.yodelutr&modulesOnly=false&runModule=true:3034:21)\n    at invokeCallbackAndReturnFlushedQueue (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.yodelutr&modulesOnly=false&runModule=true:3028:33)","message":"Exception in HostFunction: For clientReset: 'manual', it is require to set either 'error', 'clientReset.onManual' or both"}
```

### Can you reproduce the bug?

Always

### Reproduction Steps

sync config:
path: this.path,
sync: {
        user: this.user,
        partitionValue: this.partitionKey,
        existingRealmFileBehavior: this.existingRealmBehaviour,
        newRealmFileBehavior: this.newRealmFileBehavior,
        clientReset: {
          mode: 'manual',
        },
        error: this.syncErrorHandler,
},

### Version

11.10.2

### What services are you using?

Both Atlas Device Sync and Atlas App Services

### Are you using encryption?

Yes

### Platform OS and version(s)

android v33

### Build environment

Which debugger for React Native: ..

**Comment by kneth** [comment]
@Bartolg 

> leads to confusion and potential misconfiguration

We agree, and in version 12.2.0 we cleaned it up. Also notice we have had fixed to client reset until version 12.4.0, and we strongly recommend that you upgrade to a more recent version.
