### ISSUE TITLE
Install realm 404 error

### ISSUE THREAD

**Issue by 2rajpx** [realm/realm-js#659]
Hi guys
Can you solve my problem?
```
C:\Users\2raj\Documents\React Native Projects\KidNums>npm install --save realm
\
> realm@0.15.0 install C:\Users\2raj\Documents\React Native Projects\KidNums\node_modules\realm
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://static.realm.io/node-pre-gyp/realm-v0.15.0-node-v46-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for realm@0.15.0 and node@4.4.7 (node-v46 ABI) (falling back to source compile with node-gyp)

C:\Users\2raj\Documents\React Native Projects\KidNums\node_modules\realm>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

C:\Users\2raj\Documents\React Native Projects\KidNums\node_modules\realm>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build "--module=C:\Users\2raj\Documents\React Native Projects\KidNums\node_modules\realm\compiled\node-v46_win32_x64\realm.node" --module_name=realm "--module_path=C:\Users\2raj\Documents\React Native Projects\KidNums\node_modules\realm\compiled\node-v46_win32_x64" )  else (node "" configure --fallback-to-build "--module=C:\Users\2raj\Documents\React Native Projects\KidNums\node_modules\realm\compiled\node-v46_win32_x64\realm.node" --module_name=realm "--module_path=C:\Users\2raj\Documents\React Native Projects\KidNums\node_modules\realm\compiled\node-v46_win32_x64" )
gyp ERR! configure error
gyp ERR! stack Error: Python executable "C:\Program Files (x86)\Python35-32\python.EXE" is v3.5.2, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:406:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:395:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:204:7)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at Socket.emit (events.js:169:7)
gyp ERR! stack     at Pipe._onclose (net.js:486:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\2raj\\Documents\\React Native Projects\\KidNums\\node_modules\\realm\\compiled\\node-v46_win32_x64\\realm.node" "--module_name=realm" "--module_path=C:\\Users\\2raj\\Documents\\React Native Projects\\KidNums\\node_modules\\realm\\compiled\\node-v46_win32_x64"
gyp ERR! cwd C:\Users\2raj\Documents\React Native Projects\KidNums\node_modules\realm
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\2raj\Documents\React Native Projects\KidNums\node_modules\realm\compiled\node-v46_win32_x64\realm.node --module_name=realm --module_path=C:\Users\2raj\Documents\React Native Projects\KidNums\node_modules\realm\compiled\node-v46_win32_x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\2raj\Documents\React Native Projects\KidNums\node_modules\realm\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.10240
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\2raj\\Documents\\React Native Projects\\KidNums\\node_modules\\realm\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\2raj\Documents\React Native Projects\KidNums\node_modules\realm
node-pre-gyp ERR! node -v v4.4.7
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\2raj\Documents\React Native Projects\KidNums\node_modules\realm\compiled\node-v46_win32_x64\realm.node --module_name=realm --module_path=C:\Users\2raj\Documents\React Native Projects\KidNums\node_modules\realm\compiled\node-v46_win32_x64' (1)
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "realm"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE

npm ERR! realm@0.15.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the realm@0.15.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the realm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs realm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls realm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\2raj\Documents\React Native Projects\KidNums\npm-debug.log
```

**Comment by kristiandupont** [comment]
@2rajpx sadly, we don't support Windows yet. OSX and Linux only at this point.
