### ISSUE TITLE
Could not find realm binary when show react-native component in native  iOS  app

### ISSUE THREAD

**Issue by Mekongoabanda** [realm/realm-js#6803]
### How frequently does the bug occur?

Always

### Description

Hello guys, i hope you're well
Has anyone ever had a problem with Realm when they want to use a react-native component in an iOS ViewController?
Error: **Could not find real binary**
I have already tried several possible solutions (the one proposed in log included). For information:
- I don't use new arch
- "@realm/react": "0.8.0",
- "react": "18.2.0",
- "react-native": "0.74.1",
- in native part, i use #import <React/RCTRootView.h> , #import <React/RCTBundleURLProvider.h>

For example, in my index.js i've try to show ModuleEntryPoint.tsx registred like that: 
AppRegistry.registerComponent("ModuleEntryPoint", () => ModuleEntryPoint);
When i call it from my native code (Objective-C or Swift). 
and I use Realm in ModuleEntryPoint.tsx I have this error, but when I do not use realm my compsant is displayed normally and works well
I need help

### Stacktrace & log output

```shell
** Error**: 
Could not find the Realm binary. Please consult our troubleshooting guide: https://www.mongodb.com/docs/realm-sdks/js/latest/#md:troubleshooting-missing-binary
Error: Unable to resolve module ./node_modules/realm/binding/generated/native.react-native from /Users/yannickedouard/Documents/ADHP/Coherohealth/.: 

None of these files exist:
  * node_modules/realm/binding/generated/native.react-native(.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * node_modules/realm/binding/generated/native.react-native/index(.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:112:15)
    at DependencyGraph.resolveDependency (/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at /node_modules/metro/src/lib/transformHelpers.js:156:21
    at Server._resolveRelativePath (/node_modules/metro/src/Server.js:1023:12)
    at async Server._explodedSourceMapForBundleOptions (node_modules/metro/src/Server.js:971:35)
    at async Promise.all (index 0)
    at async Server._symbolicate (/node_modules/metro/src/Server.js:928:26)
    at async Server._processRequest (node_modules/metro/src/Server.js:394:7)
```

### Can you reproduce the bug?

Always

### Reproduction Steps

- Have React project with realm
- Try to show React component where realm is used  in UIViewController in native app
- launch your native app with Xcode (make sure that metro serveur running on port (8081 by default)

### Version

react version 0.74.1

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS (all versions)

### Build environment

Which debugger for React Native: ..

### Cocoapods version

1.14.3

**Comment by gumiranda** [comment]
same issue here

 "react-native": "0.74.5", 
"realm": "20.1.0",

**Comment by Gguigre** [comment]
Same for me 

"expo": "53.0.13",
"realm": "^12.14.2",

It happens only on the first run, if I reload the app it works fine.
