### ISSUE TITLE
Stabalize `OpenBehaviour` tests

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#6815]
These two tests were consistently failing on Android until I deleted the `avd-29` cache.
I suspect it's because the device stored a snapshot containing a `.realm` file which is now available and loaded instead of generating the timeout.

```
  1) OpenBehaviour
       timeout when opening new synced realm with downloadBeforeOpen and openLocal set opens an empty local realm.:

      AssertionError: expected 1 to equal +0
      + expected - actual

      -1
      +0
      
      at proxy trap (native)
      at ?anon_0_ (main.android.jsbundle:163324:80)
      at next (native)
      at asyncGeneratorStep (main.android.jsbundle:9761:19)
      at _next (main.android.jsbundle:9775:29)
      at tryCallOne (address at InternalBytecode.js:1:1180)
      at anonymous (address at InternalBytecode.js:1:1874)

  2) OpenBehaviour
       timeout when opening an existing synced realm with downloadBeforeOpen and openLocal set opens an empty local realm.:

      AssertionError: expected 1 to equal +0
      + expected - actual

      -1
      +0
      
      at proxy trap (native)
      at ?anon_0_ (main.android.jsbundle:163394:80)
      at next (native)
      at asyncGeneratorStep (main.android.jsbundle:9761:19)
      at _next (main.android.jsbundle:9775:29)
      at tryCallOne (address at InternalBytecode.js:1:1180)
      at anonymous (address at InternalBytecode.js:1:1874)
```

**Comment by kraenhansen** [comment]
Pretty frustrating 🤔 I ran the test 20 times locally against a BaaSaaS server without reproducing this 😕

**Comment by kneth** [comment]
See also https://github.com/realm/realm-js/issues/6839
