### ISSUE TITLE
Execution failed for task ':realm:configureCMakeDebug[x86]'.

### ISSUE THREAD

**Issue by RCHixon** [realm/realm-js#6948]
### How frequently does the bug occur?

Always

### Description

Running 'yarn android' produces the title error.

### Stacktrace & log output

```shell
chrishixon@NA0GV921XJ1OSX MobileRE % yarn android
yarn run v1.22.22
$ react-native run-android
(node:81397) ExperimentalWarning: CommonJS module /Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/node_modules/@react-native-community/cli-tools/build/fetch.js is loading ES Module /Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/node_modules/node-fetch/src/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
info JS server already running.
info Installing the app...

> Configure project :expo-application
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-constants
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-file-system
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-font
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-intent-launcher
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-keep-awake
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-localization
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-modules-core
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-splash-screen
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo

Using expo modules
  - expo-application (5.1.1)
  - expo-constants (14.2.1)
  - expo-file-system (15.2.2)
  - expo-font (11.1.1)
  - expo-intent-launcher (10.5.2)
  - expo-keep-awake (12.0.1)
  - expo-localization (14.1.1)
  - expo-modules-core (1.2.7)
  - expo-splash-screen (0.18.2)

WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :react-native-reanimated
AAR for react-native-reanimated has been found
/Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/node_modules/react-native-reanimated/android/react-native-reanimated-71-hermes.aar

> Task :expo-constants:createDebugExpoConfig
Execution optimizations have been disabled for task ':expo-constants:createDebugExpoConfig' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/android'. Reason: Task ':expo-constants:createDebugExpoConfig' uses this output of task ':app:checkDebugAarMetadata' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/android'. Reason: Task ':expo-constants:createDebugExpoConfig' uses this output of task ':app:compileDebugAidl' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/android'. Reason: Task ':expo-constants:createDebugExpoConfig' uses this output of task ':app:compileDebugRenderscript' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/android'. Reason: Task ':expo-constants:createDebugExpoConfig' uses this output of task ':app:compileDebugShaders' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/android'. Reason: Task ':expo-constants:createDebugExpoConfig' uses this output of task ':app:createDebugCompatibleScreenManifests' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/android'. Reason: Task ':expo-constants:createDebugExpoConfig' uses this output of task ':app:extractDeepLinksDebug' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/android'. Reason: Task ':expo-constants:createDebugExpoConfig' uses this output of task ':app:generateDebugBuildConfig' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/android'. Reason: Task ':expo-constants:createDebugExpoConfig' uses this output of task ':app:generateDebugResValues' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/android'. Reason: Task ':expo-constants:createDebugExpoConfig' uses this output of task ':app:javaPreCompileDebug' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/android'. Reason: Task ':expo-constants:createDebugExpoConfig' uses this output of task ':app:mapDebugSourceSetPaths' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/android'. Reason: Task ':expo-constants:createDebugExpoConfig' uses this output of task ':app:mergeDebugResources' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/android'. Reason: Task ':expo-constants:createDebugExpoConfig' uses this output of task ':app:mergeDebugShaders' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/android'. Reason: Task ':expo-constants:createDebugExpoConfig' uses this output of task ':app:processDebugMainManifest' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/android'. Reason: Task ':expo-constants:createDebugExpoConfig' uses this output of task ':app:processDebugManifest' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/android'. Reason: Task ':expo-constants:createDebugExpoConfig' uses this output of task ':app:processDebugManifestForPackage' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/android'. Reason: Task ':expo-constants:createDebugExpoConfig' uses this output of task ':app:processDebugResources' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :realm:configureCMakeDebug[x86] FAILED
C/C++: CMake Error at /Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/node_modules/realm/prebuilds/android/x86/share/cmake/Realm/AcquireRealmDependency.cmake:38 (message):
C/C++:   Downloading ...  Failed.  Status: 22;"HTTP response code said error"
C/C++: Call Stack (most recent call first):
C/C++:   /Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/node_modules/realm/prebuilds/android/x86/share/cmake/Realm/RealmConfig.cmake:10 (realm_acquire_dependency)
C/C++:   CMakeLists.txt:51 (find_package)

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.
470 actionable tasks: 58 executed, 412 up-to-date

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':realm:configureCMakeDebug[x86]'.
> [CXX1429] error when building with cmake using /Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/node_modules/realm/binding/android/CMakeLists.txt: -- Android: Targeting API '28' with architecture 'x86', ABI 'x86', and processor 'i686'
  -- Android: Selected unified Clang toolchain
  -- The C compiler identification is Clang 12.0.8
  -- The CXX compiler identification is Clang 12.0.8
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /Users/chrishixon/Library/Android/sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /Users/chrishixon/Library/Android/sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Getting https://static.realm.io/downloads/dependencies/openssl/3.2.0/openssl-3.2.0-x86-android.tar.gz...
  -- Configuring incomplete, errors occurred!
  See also "/Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/node_modules/realm/binding/android/.cxx/Debug/4s52u13y/x86/CMakeFiles/CMakeOutput.log".
  
  C++ build system [configure] failed while executing:
      /Users/chrishixon/Library/Android/sdk/cmake/3.22.1/bin/cmake \
        -H/Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/node_modules/realm/binding/android \
        -DCMAKE_SYSTEM_NAME=Android \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
        -DCMAKE_SYSTEM_VERSION=28 \
        -DANDROID_PLATFORM=android-28 \
        -DANDROID_ABI=x86 \
        -DCMAKE_ANDROID_ARCH_ABI=x86 \
        -DANDROID_NDK=/Users/chrishixon/Library/Android/sdk/ndk/23.1.7779620 \
        -DCMAKE_ANDROID_NDK=/Users/chrishixon/Library/Android/sdk/ndk/23.1.7779620 \
        -DCMAKE_TOOLCHAIN_FILE=/Users/chrishixon/Library/Android/sdk/ndk/23.1.7779620/build/cmake/android.toolchain.cmake \
        -DCMAKE_MAKE_PROGRAM=/Users/chrishixon/Library/Android/sdk/cmake/3.22.1/bin/ninja \
        -DCMAKE_CXX_FLAGS=-std=c++20 \
        -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/node_modules/realm/binding/android/build/intermediates/cxx/Debug/4s52u13y/obj/x86 \
        -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/node_modules/realm/binding/android/build/intermediates/cxx/Debug/4s52u13y/obj/x86 \
        -DCMAKE_BUILD_TYPE=Debug \
        -DCMAKE_FIND_ROOT_PATH=/Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/node_modules/realm/binding/android/.cxx/Debug/4s52u13y/prefab/x86/prefab \
        -B/Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/node_modules/realm/binding/android/.cxx/Debug/4s52u13y/x86 \
        -GNinja \
        -DANDROID_STL=c++_shared \
        -DCMAKE_CXX_VISIBILITY_PRESET=hidden \
        -DREACT_NATIVE_ROOT_DIR=/Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/node_modules/react-native
    from /Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/node_modules/realm/binding/android
  CMake Error at /Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/node_modules/realm/prebuilds/android/x86/share/cmake/Realm/AcquireRealmDependency.cmake:38 (message):
    Downloading ...  Failed.  Status: 22;"HTTP response code said error"
  Call Stack (most recent call first):
    /Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/node_modules/realm/prebuilds/android/x86/share/cmake/Realm/RealmConfig.cmake:10 (realm_acquire_dependency)
    CMakeLists.txt:51 (find_package)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 46s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':realm:configureCMakeDebug[x86]'.
> [CXX1429] error when building with cmake using /Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/node_modules/realm/binding/android/CMakeLists.txt: -- Android: Targeting API '28' with architecture 'x86', ABI 'x86', and processor 'i686'
  -- Android: Selected unified Clang toolchain
  -- The C compiler identification is Clang 12.0.8
  -- The CXX compiler identification is Clang 12.0.8
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /Users/chrishixon/Library/Android/sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /Users/chrishixon/Library/Android/sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Getting https://static.realm.io/downloads/dependencies/openssl/3.2.0/openssl-3.2.0-x86-android.tar.gz...
  -- Configuring incomplete, errors occurred!
  See also "/Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/node_modules/realm/binding/android/.cxx/Debug/4s52u13y/x86/CMakeFiles/CMakeOutput.log".
  
  C++ build system [configure] failed while executing:
      /Users/chrishixon/Library/Android/sdk/cmake/3.22.1/bin/cmake \
        -H/Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/node_modules/realm/binding/android \
        -DCMAKE_SYSTEM_NAME=Android \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
        -DCMAKE_SYSTEM_VERSION=28 \
        -DANDROID_PLATFORM=android-28 \
        -DANDROID_ABI=x86 \
        -DCMAKE_ANDROID_ARCH_ABI=x86 \
        -DANDROID_NDK=/Users/chrishixon/Library/Android/sdk/ndk/23.1.7779620 \
        -DCMAKE_ANDROID_NDK=/Users/chrishixon/Library/Android/sdk/ndk/23.1.7779620 \
        -DCMAKE_TOOLCHAIN_FILE=/Users/chrishixon/Library/Android/sdk/ndk/23.1.7779620/build/cmake/android.toolchain.cmake \
        -DCMAKE_MAKE_PROGRAM=/Users/chrishixon/Library/Android/sdk/cmake/3.22.1/bin/ninja \
        -DCMAKE_CXX_FLAGS=-std=c++20 \
        -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/node_modules/realm/binding/android/build/intermediates/cxx/Debug/4s52u13y/obj/x86 \
        -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/node_modules/realm/binding/android/build/intermediates/cxx/Debug/4s52u13y/obj/x86 \
        -DCMAKE_BUILD_TYPE=Debug \
        -DCMAKE_FIND_ROOT_PATH=/Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/node_modules/realm/binding/android/.cxx/Debug/4s52u13y/prefab/x86/prefab \
        -B/Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/node_modules/realm/binding/android/.cxx/Debug/4s52u13y/x86 \
        -GNinja \
        -DANDROID_STL=c++_shared \
        -DCMAKE_CXX_VISIBILITY_PRESET=hidden \
        -DREACT_NATIVE_ROOT_DIR=/Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/node_modules/react-native
    from /Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/node_modules/realm/binding/android
  CMake Error at /Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/node_modules/realm/prebuilds/android/x86/share/cmake/Realm/AcquireRealmDependency.cmake:38 (message):
    Downloading ...  Failed.  Status: 22;"HTTP response code said error"
  Call Stack (most recent call first):
    /Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/node_modules/realm/prebuilds/android/x86/share/cmake/Realm/RealmConfig.cmake:10 (realm_acquire_dependency)
    CMakeLists.txt:51 (find_package)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 46s

    at makeError (/Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:174:9)
    at /Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async runOnAllDevices (/Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:82:7)
    at async Command.handleAction (/Users/chrishixon/Library/CloudStorage/OneDrive-CargillInc/Documents/Code/cargill/MobileRE/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:108:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Can you reproduce the bug?

Always

### Reproduction Steps

running 'yarn android'

### Version

16.0

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Android 11 MacOS

### Build environment

gradle - 7.5.1
yarn - 1.22.22
openjdk version "17.0.13" 2024-10-15
OpenJDK Runtime Environment Homebrew (build 17.0.13+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.13+0, mixed mode, sharing)
Cocoa pods - 1.16.2

### Cocoapods version

1.16.2

**Comment by kraenhansen** [comment]
You've noted "Version" as "16.0", we don't have a v16 of Realm JS - what is this referring to?
