### ISSUE TITLE
TypeError: hex is not a function

### ISSUE THREAD

**Issue by dalinaum** [realm/realm-js#772]
I used Realm Node.js and encounted the following error:

```
/Users/dalinaum/project/test/realm-blog/node_modules/realm/lib/submit-analytics.js:47
    return Buffer.from(mac, 'hex');
                  ^

TypeError: hex is not a function
    at Function.from (native)
    at Function.from (native)
    at getDarwinIdentifier (/Users/dalinaum/project/test/realm-blog/node_modules/realm/lib/submit-analytics.js:47:19)
    at getAnonymizedMachineIdentifier (/Users/dalinaum/project/test/realm-blog/node_modules/realm/lib/submit-analytics.js:63:27)
    at module.exports (/Users/dalinaum/project/test/realm-blog/node_modules/realm/lib/submit-analytics.js:75:24)
    at Object.<anonymous> (/Users/dalinaum/project/test/realm-blog/node_modules/realm/lib/index.js:60:42)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

If I comment out `nodeRequire('./submit-analytics')('Run');` in `node_modules/realm/lib/index.js`, it works.

**Comment by dalinaum** [comment]
I found the following issue:
https://github.com/nodejs/node/issues/8053

If I uses v4.4.7, I get the above error. If I uses v4.5.0, it works.

**Comment by kristiandupont** [comment]
@dalinaum thank you for reporting this, that's a bug.
