### ISSUE TITLE
Intermittent Async tests fail

### ISSUE THREAD

**Issue by radu-tutueanu** [realm/realm-js#879]
On the node-server-sdk tests, we have seen sporadic failures in the Async tests.

e.g.:

```
1) AsyncTests : testResultsDeleteNotifications
   Error: Failed: Notification count 3 not equal to expected count 4
   
   Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
       at Timer.listOnTimeout timers.js:92:15

2) AsyncTests : testListAddNotifications
   Error: Failed: Notification count 1 not equal to expected count 2
   
   Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
       at Timer.listOnTimeout timers.js:92:15
```

**Comment by kneth** [comment]
I am closing the issue as we have seen these issues for a very long time.
