### ISSUE TITLE
Running realm nodeJS on Raspberry Pi 3

### ISSUE THREAD

**Issue by hengel2810** [realm/realm-js#902]
Hello guys,

I've developed a little smart home app on my Mac using nodeJS and realm. Now I want to run it on an Raspberry Pi 3, but I've no idea how I had to build and install realm for nodeJS.

Doing to normal install via npm gives the following error:

node server.js
/home/pi/localknixapi/node_modules/bindings/bindings.js:91
throw err
^

Error: Could not locate the bindings file. Tried:
→ /home/pi/localknixapi/node_modules/realm/build/realm.node
→ /home/pi/localknixapi/node_modules/realm/build/Debug/realm.node
→ /home/pi/localknixapi/node_modules/realm/build/Release/realm.node
→ /home/pi/localknixapi/node_modules/realm/out/Debug/realm.node
→ /home/pi/localknixapi/node_modules/realm/Debug/realm.node
→ /home/pi/localknixapi/node_modules/realm/out/Release/realm.node
→ /home/pi/localknixapi/node_modules/realm/Release/realm.node
→ /home/pi/localknixapi/node_modules/realm/build/default/realm.node
→ /home/pi/localknixapi/node_modules/realm/compiled/6.10.0/linux/arm/realm.node
at bindings (/home/pi/localknixapi/node_modules/bindings/bindings.js:88:9)
at Object. (/home/pi/localknixapi/node_modules/realm/lib/index.js:35:41)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object. (/home/pi/localknixapi/DatabaseController.js:3:13)

I hope somebody can help building and using realm with nodeJS on Raspberry Pi 3.

**Comment by kristiandupont** [comment]
Sorry, at this point, Realm is not supported on Linux on ARM processors. There should be no technical obstacles, so if you are up for it, you can build it yourself -- it's all open source. :-)
