### ISSUE TITLE
Random failure in SessionTests

### ISSUE THREAD

**Issue by radu-tutueanu** [realm/realm-js#957]
We keep seeing this test fail from time to time on CI:

```
SessionTests : testProperties
   Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
       at ontimeout timers.js:380:14
       at tryOnTimeout timers.js:244:5
       at Timer.listOnTimeout timers.js:214:5
```

cc @fealebenpae

**Comment by blagoev** [comment]
should be addressed in #974
